import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createStore, FixtureFetcher, RadarEngine, decryptGmailRefreshToken, encryptGmailRefreshToken, GMAIL_READONLY_SCOPE, type Opportunity } from '../src/index.js';

function opportunity(id: string, title: string): Opportunity { return { id, createdAt: '2026-01-01T00:00:00.000Z', status: 'open', fields: { title, organizationName: 'North River', type: 'magazine', genres: ['poetry'], deadline: { kind: 'exact', date: '2026-12-01' }, fee: { disclosed: true, amountCents: 0 }, eligibility: [], requiredMaterials: [], contactEmailPresent: false }, sourceId: 'source', sourceUrl: `https://north.example/${id}`, alternateSourceIds: [], scores: { freshness: 100, confidence: 100, trust: 100 }, trustSignals: [], lastCheckedAt: '2026-01-01T00:00:00.000Z', lastChangedAt: '2026-01-01T00:00:00.000Z', lastExtractionConfidence: 100, lastOpenSignal: true, lastClosedSignal: false, lastSuspiciousSignals: [], pastCycles: [], conflicts: [] }; }

test('Gmail refresh tokens are encrypted, versioned, and never equal plaintext', () => {
  const encrypted = encryptGmailRefreshToken('refresh-token-value'); assert.notEqual(encrypted.encrypted, 'refresh-token-value'); assert.match(encrypted.encrypted, /^v\d+\./); assert.equal(decryptGmailRefreshToken(encrypted.encrypted).token, 'refresh-token-value');
});

test('OAuth state is PKCE-bound, account-bound, short-lived, and single-use', () => {
  const engine = new RadarEngine({ store: createStore(), fetcher: new FixtureFetcher() }); engine.addUser({ id: 'gmail_user', displayName: 'Gmail User', genres: [], attributes: {} });
  const state = engine.createGmailOAuthState('gmail_user', { clientId: 'client', redirectUri: 'https://app.example.test/api/auth/gmail/callback' }); const parsed = new URL(state.authorizationUrl); assert.equal(parsed.searchParams.get('access_type'), 'offline'); assert.equal(parsed.searchParams.get('code_challenge_method'), 'S256'); assert.equal(parsed.searchParams.get('scope'), GMAIL_READONLY_SCOPE); assert.equal(engine.store.gmailOAuthStates[0]?.encryptedPkceVerifier.includes(state.codeVerifier), false);
  assert.equal(engine.consumeGmailOAuthState(state.state, 'gmail_user', 'https://app.example.test/api/auth/gmail/callback').codeVerifier, state.codeVerifier); assert.throws(() => engine.consumeGmailOAuthState(state.state, 'gmail_user', 'https://app.example.test/api/auth/gmail/callback'), /expired/);
});

test('Gmail connections default to review, jobs are deduped, and provider subject is isolated', () => {
  const engine = new RadarEngine({ store: createStore(), fetcher: new FixtureFetcher() }); engine.addUser({ id: 'gmail_user', displayName: 'Gmail User', genres: [], attributes: {} }); engine.addUser({ id: 'other_user', displayName: 'Other', genres: [], attributes: {} });
  const connection = engine.connectGmail('gmail_user', { googleSubjectId: 'google-subject', accountEmail: 'creator@gmail.com', refreshToken: 'refresh', grantedScopes: [GMAIL_READONLY_SCOPE] }); assert.equal(connection.mode, 'review'); assert.equal(connection.accountEmailMasked.includes('creator@gmail.com'), false); const first = engine.queueGmailSync('gmail_user', 'initial', 'initial:30'); const second = engine.queueGmailSync('gmail_user', 'initial', 'initial:30'); assert.equal(first.id, second.id); engine.leaseGmailSyncJob(first.id); assert.equal(engine.store.gmailSyncJobs[0]?.status, 'running'); engine.completeGmailSyncJob(first.id, { inspected: 1, candidates: 0, ignored: 1, duplicates: 0 }, 'history-1'); assert.equal(engine.store.gmailSyncJobs[0]?.status, 'succeeded'); assert.throws(() => engine.connectGmail('other_user', { googleSubjectId: 'google-subject', accountEmail: 'creator@gmail.com', refreshToken: 'refresh', grantedScopes: [GMAIL_READONLY_SCOPE] }), /another Missa account/);
});

test('Autopilot gates exact high-confidence non-sensitive updates and blocks sensitive/default review', () => {
  const store = createStore(); const engine = new RadarEngine({ store, fetcher: new FixtureFetcher() }); engine.addUser({ id: 'gmail_user', displayName: 'Gmail User', genres: [], attributes: {} }); const opp = opportunity('opp_gmail', 'North River Review'); store.opportunities.set(opp.id, opp); store.tracked.push({ userId: 'gmail_user', opportunityId: opp.id, trackedAt: '2026-08-01T00:00:00.000Z', notify: true, myStatus: 'submitted', events: [] }); const connection = engine.connectGmail('gmail_user', { googleSubjectId: 'google-subject', accountEmail: 'creator@gmail.com', refreshToken: 'refresh', grantedScopes: [GMAIL_READONLY_SCOPE] });
  const envelope = { provider: 'gmail-sync', providerMessageId: 'gmail-message-1', receivedAt: '2026-08-02T00:00:00.000Z', to: [], from: 'editor@north.example', subject: 'North River Review', textBody: 'Thank you for your submission. It is now under review.', headers: {}, attachments: [] }; const ingested = engine.ingestGmailEnvelope(connection.id, envelope); assert.equal(ingested.accepted, true); const candidate = store.emailCandidates[0]!; assert.equal(candidate.sourceMode, 'gmail-sync'); assert.equal(engine.gmailAutopilotGate(candidate.id).allowed, false); engine.setGmailMode('gmail_user', 'autopilot', true, 'mode-1'); assert.equal(engine.gmailAutopilotGate(candidate.id).allowed, true);
  const sensitive = engine.ingestGmailEnvelope(connection.id, { ...envelope, providerMessageId: 'gmail-message-2', textBody: 'Congratulations, you have been selected.' }); const sensitiveCandidate = store.emailCandidates.find((item) => item.id === sensitive.candidateId)!; assert.equal(engine.gmailAutopilotGate(sensitiveCandidate.id).allowed, false);
  const applied = engine.applyGmailAutopilotCandidate(candidate.id); assert.equal(applied.mutation.trackerUpdated, true); assert.equal(store.tracked[0]!.events[0]?.source, 'email');
  engine.setGmailMode('gmail_user', 'review', false, 'mode-2'); assert.equal(engine.gmailConnection('gmail_user')?.mode, 'review');
});

test('disconnect removes Gmail credentials and pending candidates without touching confirmed tracker history', () => {
  const store = createStore(); const engine = new RadarEngine({ store, fetcher: new FixtureFetcher() }); engine.addUser({ id: 'gmail_user', displayName: 'Gmail User', genres: [], attributes: {} }); const connection = engine.connectGmail('gmail_user', { googleSubjectId: 'google-subject', accountEmail: 'creator@gmail.com', refreshToken: 'refresh', grantedScopes: [GMAIL_READONLY_SCOPE] }); store.emailCandidates.push({ id: 'candidate_1', userId: 'gmail_user', gmailConnectionId: connection.id, provider: 'gmail-sync', providerMessageId: 'message', receivedAt: '2026-08-01T00:00:00.000Z', subject: 'Subject', bodyExcerpt: 'Excerpt', bodyHash: 'hash', attachmentMetadata: [], classification: 'unmatched', state: 'pending', candidates: [], confidence: 'unknown', warnings: [], evidenceReasons: [], createdAt: '2026-08-01T00:00:00.000Z', expiresAt: '2026-09-01T00:00:00.000Z' }); const result = engine.disconnectGmail('gmail_user', true); assert.equal(result.deletedCandidates, 1); assert.equal(engine.gmailConnection('gmail_user'), undefined); assert.equal(store.gmailConnections[0]?.encryptedRefreshToken, ''); assert.equal(store.gmailConnections[0]?.googleSubjectId.startsWith('disconnected:'), true);
});
