import Link from 'next/link';
import { getWorkspacePageAccess } from '@/lib/workspacePage';

export default async function WorkspaceReviewsPage({ searchParams }: { searchParams: Promise<{ organizationId?: string }> }) {
  const access = await getWorkspacePageAccess(searchParams, 'workspace/reviews');
  if (!access.organizationId) return <main className="mx-auto max-w-2xl px-6 py-12"><h1 className="font-heading text-3xl font-medium text-foreground">Reviews</h1><p className="mt-2 text-muted-foreground">Join an organization to view review workflow.</p></main>;
  const submissions = access.workspace.submissionsForOrganization(access.organizationId).filter((submission) => submission.status === 'in-review');
  const assignments = [...access.workspace.store.reviewAssignments.values()].filter((assignment) => { const submission = access.workspace.store.submissions.get(assignment.submissionId); return submission && submissions.some((item) => item.id === submission.id); });
  return <main className="mx-auto max-w-5xl px-5 py-8 sm:px-8"><header><p className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">{access.organizationName}</p><h1 className="mt-2 font-heading text-3xl font-medium tracking-tight text-foreground">Reviews</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Current review queue for this organization. Reviewers continue to record their own assignments through the existing Reviewer surface.</p></header><section className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-border bg-white p-4"><p className="text-xs text-muted-foreground">Submissions in review</p><p className="mt-2 font-mono text-2xl text-foreground">{submissions.length}</p></div><div className="rounded-xl border border-border bg-white p-4"><p className="text-xs text-muted-foreground">Assignments</p><p className="mt-2 font-mono text-2xl text-foreground">{assignments.length}</p></div></section><section className="mt-8 rounded-xl border border-border bg-white p-5"><ul className="divide-y divide-border">{submissions.map((submission) => <li key={submission.id} className="flex flex-wrap items-center justify-between gap-3 py-3 first:pt-0 last:pb-0"><div><p className="text-sm font-medium text-foreground">{submission.openCallTitle}</p><p className="mt-1 font-mono text-[11px] text-muted-foreground">{submission.id} · {submission.submittedAt}</p></div><span className="text-xs text-muted-foreground">{assignments.filter((assignment) => assignment.submissionId === submission.id).length} assignment(s)</span></li>)}{submissions.length === 0 && <li className="py-8 text-sm text-muted-foreground">No submissions are currently in review.</li>}</ul></section><p className="mt-4 text-xs text-muted-foreground"><Link href="/reviewer" className="font-medium text-accent-deep underline decoration-accent-tint underline-offset-4">Open Reviewer queue</Link> for reviewer-owned assignments.</p></main>;
}
