import type {
  TaxonomyFacetKey,
  TaxonomySeedCatalog,
  TaxonomySeedFacet,
  TaxonomySeedTerm,
} from "./types.js";

type TermRef = readonly [TaxonomyFacetKey, string];
type TermInput =
  | string
  | {
      label: string;
      slug?: string;
      aliases?: string[];
      description?: string;
      culturallySensitive?: boolean;
      selectable?: boolean;
      broader?: TermRef[];
    };

const FACET_PREFIX: Record<TaxonomyFacetKey, string> = {
  "practice-family": "pf",
  discipline: "disc",
  form: "form",
  genre: "genre",
  subgenre: "subgenre",
  medium: "medium",
  technique: "technique",
  mode: "mode",
  role: "role",
  theme: "theme",
  audience: "audience",
  language: "language",
};

export function taxonomySlug(value: string): string {
  return value
    .normalize("NFKD")
    .toLocaleLowerCase("en")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/&/g, " and ")
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-+/g, "-");
}

export function taxonomyTermId(
  facet: TaxonomyFacetKey,
  slugOrLabel: string,
): string {
  return `taxterm_${FACET_PREFIX[facet]}-${taxonomySlug(slugOrLabel)}`;
}

const ref = (facet: TaxonomyFacetKey, slugOrLabel: string): TermRef => [
  facet,
  slugOrLabel,
];
const practice = (slugOrLabel: string): TermRef =>
  ref("practice-family", slugOrLabel);
const discipline = (slugOrLabel: string): TermRef =>
  ref("discipline", slugOrLabel);
const genre = (slugOrLabel: string): TermRef => ref("genre", slugOrLabel);

function makeTerm(
  facet: TaxonomyFacetKey,
  input: TermInput,
  defaultBroader: TermRef[] = [],
): TaxonomySeedTerm {
  const options = typeof input === "string" ? { label: input } : input;
  const slug = options.slug ?? taxonomySlug(options.label);
  const broader = options.broader ?? defaultBroader;
  return {
    id: taxonomyTermId(facet, slug),
    facet,
    slug,
    preferredLabel: options.label,
    description: options.description,
    aliases: options.aliases ?? [],
    broaderTermIds: broader.map(([parentFacet, parent]) =>
      taxonomyTermId(parentFacet, parent),
    ),
    culturallySensitive: options.culturallySensitive ?? false,
    selectable: options.selectable ?? true,
  };
}

function group(
  facet: TaxonomyFacetKey,
  broader: TermRef | TermRef[],
  inputs: TermInput[],
): TaxonomySeedTerm[] {
  const broaderTerms = Array.isArray(broader[0])
    ? (broader as TermRef[])
    : [broader as TermRef];
  return inputs.map((input) => makeTerm(facet, input, broaderTerms));
}

export const TAXONOMY_FACETS: TaxonomySeedFacet[] = [
  {
    id: "taxfacet_practice-family",
    key: "practice-family",
    label: "Creative area",
    description: "The broad area the work belongs to.",
    selectionMode: "hierarchical",
    userVisible: true,
    sortOrder: 10,
  },
  {
    id: "taxfacet_discipline",
    key: "discipline",
    label: "Discipline",
    description: "A recognised branch of creative work.",
    selectionMode: "hierarchical",
    userVisible: true,
    sortOrder: 20,
  },
  {
    id: "taxfacet_form",
    key: "form",
    label: "Form",
    description: "The kind of work, unit, object, event, or output being made.",
    selectionMode: "multiple",
    userVisible: true,
    sortOrder: 30,
  },
  {
    id: "taxfacet_genre",
    key: "genre",
    label: "Genre",
    description: "A creative tradition or content convention.",
    selectionMode: "hierarchical",
    userVisible: true,
    sortOrder: 40,
  },
  {
    id: "taxfacet_subgenre",
    key: "subgenre",
    label: "Subgenre",
    description: "A narrower genre tradition.",
    selectionMode: "hierarchical",
    userVisible: true,
    sortOrder: 50,
  },
  {
    id: "taxfacet_medium",
    key: "medium",
    label: "Medium",
    description: "The material, carrier, or technical substrate of a work.",
    selectionMode: "multiple",
    userVisible: true,
    sortOrder: 60,
  },
  {
    id: "taxfacet_technique",
    key: "technique",
    label: "Technique or process",
    description: "How a work is made.",
    selectionMode: "multiple",
    userVisible: true,
    sortOrder: 70,
  },
  {
    id: "taxfacet_mode",
    key: "mode",
    label: "Mode or approach",
    description: "How a work operates, is organised, or meets its context.",
    selectionMode: "multiple",
    userVisible: true,
    sortOrder: 80,
  },
  {
    id: "taxfacet_role",
    key: "role",
    label: "Role",
    description:
      "What a person, group, or organisation does in relation to the work.",
    selectionMode: "multiple",
    userVisible: true,
    sortOrder: 90,
  },
  {
    id: "taxfacet_theme",
    key: "theme",
    label: "Theme or subject",
    description:
      "What the work is about. This vocabulary is deliberately extensible.",
    selectionMode: "multiple",
    userVisible: true,
    sortOrder: 100,
  },
  {
    id: "taxfacet_audience",
    key: "audience",
    label: "Audience",
    description: "Who the work is intended for.",
    selectionMode: "multiple",
    userVisible: true,
    sortOrder: 110,
  },
  {
    id: "taxfacet_language",
    key: "language",
    label: "Language",
    description:
      "The language or language mode used by the work, mapped to BCP 47 where possible.",
    selectionMode: "multiple",
    userVisible: true,
    sortOrder: 120,
  },
];

const practiceFamilies = [
  { label: "Writing & literature", aliases: ["literature", "writing"] },
  { label: "Visual arts", aliases: ["fine art"] },
  "Photography",
  { label: "Film & moving image", aliases: ["film", "cinema", "moving image"] },
  { label: "Music & sound", aliases: ["music", "sound"] },
  { label: "Theatre & dramatic arts", aliases: ["theater", "theatre"] },
  { label: "Dance & choreography", aliases: ["dance"] },
  { label: "Performance & live art", aliases: ["performance art", "live art"] },
  {
    label: "Illustration, comics & sequential art",
    aliases: ["illustration and comics", "graphic narrative"],
  },
  { label: "Craft & material arts", aliases: ["craft", "applied craft"] },
  "Design",
  {
    label: "Architecture, space & public realm",
    slug: "architecture-spatial-practice-and-public-realm",
    aliases: [
      "architecture, spatial practice & public realm",
      "architecture and spatial practice",
      "built environment",
    ],
  },
  {
    label: "Fashion, costume & wearables",
    slug: "fashion-costume-and-wearable-practice",
    aliases: [
      "fashion, costume & wearable practice",
      "fashion and costume",
      "wearable art",
    ],
  },
  {
    label: "Digital, interactive & immersive arts",
    aliases: ["digital art", "new media"],
  },
  { label: "Games & playful media", aliases: ["games", "game arts"] },
  {
    label: "Curating, culture & publishing",
    slug: "curatorial-cultural-and-publishing-practice",
    aliases: [
      "curatorial, cultural & publishing practice",
      "curatorial practice",
      "cultural practice",
    ],
  },
  {
    label: "Social, community & participatory work",
    slug: "social-community-and-participatory-practice",
    aliases: [
      "social, community & participatory practice",
      "community arts",
      "social practice",
    ],
  },
  {
    label: "Research & knowledge production",
    aliases: ["research", "knowledge production"],
  },
  {
    label: "Interdisciplinary, hybrid & emerging work",
    slug: "interdisciplinary-hybrid-and-emerging-practice",
    aliases: [
      "interdisciplinary, hybrid & emerging practice",
      "interdisciplinary",
      "multidisciplinary",
    ],
  },
].map((input) => makeTerm("practice-family", input));

const disciplines = [
  ...group("discipline", practice("Writing & literature"), [
    "Poetry",
    "Fiction",
    { label: "Creative nonfiction", aliases: ["creative non-fiction", "CNF"] },
    "Dramatic writing",
    "Children's writing",
    "Young adult writing",
    "Literary translation",
    "Journalism",
    "Criticism",
    "Arts writing",
    "Editing",
    "Publishing",
    "Comics writing",
    "Oral storytelling",
    "Spoken word",
    "Copywriting",
  ]),
  ...group("discipline", practice("Visual arts"), [
    "Painting",
    "Drawing",
    "Sculpture",
    "Printmaking",
    "Installation art",
    "Conceptual art",
    "Collage",
    "Assemblage",
    "Book arts",
    "Public art",
    "Land art",
    "Environmental art",
    "Digital visual art",
    "Light art",
    "Text art",
    "Miniature art",
  ]),
  ...group("discipline", practice("Photography"), [
    "Photography",
    "Fine-art photography",
    "Documentary photography",
    "Photojournalism",
    "Portrait photography",
    "Street photography",
    "Landscape photography",
    "Nature photography",
    "Wildlife photography",
    "Architectural photography",
    "Fashion photography",
    "Still-life photography",
    "Scientific photography",
    "Experimental photography",
  ]),
  ...group("discipline", practice("Film & moving image"), [
    "Narrative filmmaking",
    "Documentary filmmaking",
    "Experimental film",
    "Artist moving image",
    "Animation",
    "Television",
    "Episodic media",
    "Commercial film",
    "Music video",
    "Immersive film",
    "Interactive film",
    "Cinematography",
    "Film editing",
    "Film producing",
    "Film directing",
    "Production design",
    "Visual effects",
  ]),
  ...group(
    "discipline",
    [practice("Writing & literature"), practice("Film & moving image")],
    [
      { label: "Screenwriting", aliases: ["screenplay writing"] },
      "Television writing",
      "Audio drama",
    ],
  ),
  ...group("discipline", practice("Music & sound"), [
    "Composition",
    "Songwriting",
    "Music performance",
    "Conducting",
    "Music production",
    "Recording engineering",
    "Mixing",
    "Mastering",
    "Beat-making",
    "Sound art",
    "Sound design",
    "Field recording",
    "DJ practice",
    "Live coding",
    "Music programming",
    "Scoring",
  ]),
  ...group("discipline", practice("Theatre & dramatic arts"), [
    "Playwriting",
    "Theatre directing",
    "Acting",
    "Dramaturgy",
    "Theatre producing",
    "Stage management",
    "Musical theatre",
    "Opera",
    "Physical theatre",
    "Devised theatre",
    "Documentary theatre",
    "Immersive theatre",
    "Comedy",
    "Puppetry",
    "Mime",
    "Clowning",
    "Circus arts",
    "Theatre design",
  ]),
  ...group("discipline", practice("Dance & choreography"), [
    "Choreography",
    "Dance performance",
    "Ballet",
    "Contemporary dance",
    "Modern dance",
    "Jazz dance",
    "Tap dance",
    "Street dance",
    "Club dance",
    "African dance",
    "South Asian dance",
    "Folk dance",
    "Traditional dance",
    "Indigenous dance",
    "Ballroom dance",
    "Social dance",
    "Dance theatre",
    "Screendance",
    "Aerial dance",
    "Integrated dance",
  ]),
  ...group("discipline", practice("Performance & live art"), [
    "Performance art",
    "Body art",
    "Durational performance",
    "Live art",
    "Participatory performance",
    "Relational performance",
    "Live literature",
    "Drag",
    "Cabaret",
    "Burlesque",
    "Digital performance",
  ]),
  ...group("discipline", practice("Illustration, comics & sequential art"), [
    "Editorial illustration",
    "Book illustration",
    "Children's illustration",
    "Scientific illustration",
    "Medical illustration",
    "Fashion illustration",
    "Architectural illustration",
    "Concept art",
    "Comics",
    "Graphic novels",
    "Webcomics",
    "Editorial cartoons",
    "Storyboarding",
    "Character design",
    "Visual development",
  ]),
  ...group("discipline", practice("Craft & material arts"), [
    "Ceramics",
    "Pottery",
    "Glass art",
    "Fibre art",
    "Textile art",
    "Weaving",
    "Embroidery",
    "Quilting",
    "Jewellery",
    "Metalsmithing",
    "Woodwork",
    "Furniture making",
    "Leatherwork",
    "Basketry",
    "Papermaking",
    "Bookbinding",
    "Mosaic",
    "Decorative arts",
    "Folk craft",
    "Indigenous craft",
  ]),
  ...group("discipline", practice("Design"), [
    "Graphic design",
    "Visual communication",
    "Brand design",
    "Typography",
    "Type design",
    "Lettering",
    "Calligraphy",
    "Editorial design",
    "Information design",
    "Motion design",
    "Product design",
    "Industrial design",
    "Furniture design",
    "Lighting design",
    "UX design",
    "UI design",
    "Interaction design",
    "Service design",
    "Web design",
    "Experience design",
    "Social design",
    "Civic design",
    "Systems design",
    "Exhibition design",
    "Wayfinding design",
    "Speculative design",
    "Design research",
  ]),
  ...group(
    "discipline",
    practice("Architecture, spatial practice & public realm"),
    [
      "Architecture",
      "Landscape architecture",
      "Interior architecture",
      "Interior design",
      "Urban design",
      "Urbanism",
      "Planning",
      "Placemaking",
      "Spatial practice",
      "Temporary architecture",
      "Set design",
      "Museum design",
      "Heritage conservation",
      "Adaptive reuse",
      "Restoration",
      "Community architecture",
      "Computational architecture",
      "Digital fabrication",
    ],
  ),
  ...group("discipline", practice("Fashion, costume & wearable practice"), [
    "Fashion design",
    "Knitwear design",
    "Textile design",
    "Surface design",
    "Costume design",
    "Footwear design",
    "Accessory design",
    "Millinery",
    "Fashion styling",
    "Fashion direction",
    "Wearable technology",
    "Adaptive fashion",
    "Sustainable fashion",
  ]),
  ...group("discipline", practice("Digital, interactive & immersive arts"), [
    "Creative coding",
    "Generative art",
    "Algorithmic art",
    "Software art",
    "Net art",
    "Browser art",
    "Interactive installation",
    "Physical computing",
    "Electronic art",
    "Robotic art",
    "Data art",
    "Virtual reality art",
    "Augmented reality art",
    "Mixed reality art",
    "Projection mapping",
    "Immersive environments",
    "AI-assisted art",
  ]),
  ...group("discipline", practice("Games & playful media"), [
    "Digital game design",
    "Mobile game design",
    "Browser game design",
    "Interactive fiction",
    "Tabletop game design",
    "Board game design",
    "Role-playing game design",
    "Live-action role-play",
    "Game systems design",
    "Level design",
    "Narrative design",
    "Game writing",
    "Game art",
    "Game animation",
    "Game audio",
    "Technical art",
  ]),
  ...group(
    "discipline",
    practice("Curatorial, cultural & publishing practice"),
    [
      "Curating",
      "Exhibition making",
      "Public programming",
      "Festival programming",
      "Cultural journalism",
      "Museum practice",
      "Gallery practice",
      "Library practice",
      "Archiving",
      "Oral history",
      "Collections management",
      "Cataloguing",
      "Digital humanities",
      "Conservation",
      "Restoration practice",
      "Commissioning",
      "Independent publishing",
      "Arts producing",
      "Arts administration",
      "Artist management",
      "Cultural policy",
    ],
  ),
  ...group(
    "discipline",
    practice("Social, community & participatory practice"),
    [
      "Socially engaged art",
      "Community arts",
      "Participatory arts",
      "Co-creation",
      "Civic practice",
      "Public practice",
      "Creative placemaking",
      "Cultural organising",
      "Arts and health",
      "Arts and wellbeing",
      "Care-based practice",
      "Arts education",
      "Teaching artistry",
      "Youth arts",
      "Intergenerational arts",
      "Ecological practice",
      "Food practice",
      "Land-based practice",
      "Justice arts",
      "Peacebuilding arts",
    ],
  ),
  ...group("discipline", practice("Research & knowledge production"), [
    "Artistic research",
    "Practice-based research",
    "Research-creation",
    "Humanities research",
    "Cultural research",
    "Social science research",
    "Policy research",
    "Science research",
    "Technology research",
    "Public-engagement research",
    "Critical theory",
    "Museum studies",
  ]),
  ...group(
    "discipline",
    practice("Interdisciplinary, hybrid & emerging practice"),
    [
      "Interdisciplinary practice",
      "Multidisciplinary practice",
      "Transdisciplinary practice",
      "Cross-disciplinary practice",
      "Hybrid writing",
      "Expanded publishing",
      "Text-image practice",
      "Moving-image installation",
      "Sound performance",
      "Dance film",
      "Performance lecture",
      "Art-science",
      "Bio art",
      "Eco art",
      "Speculative practice",
    ],
  ),
];

const forms = [
  ...group("form", discipline("Poetry"), [
    "Individual poem",
    "Poetry sequence",
    "Chapbook",
    "Pamphlet",
    "Poetry collection",
    "Book-length poetry manuscript",
    "Visual poem",
  ]),
  ...group("form", discipline("Fiction"), [
    "Microfiction",
    "Flash fiction",
    "Short story",
    "Novelette",
    "Novella",
    "Novel",
    "Serial fiction",
    "Linked story collection",
  ]),
  ...group("form", discipline("Creative nonfiction"), [
    "Personal essay",
    "Lyric essay",
    "Memoir",
    "Autobiography",
    "Biography",
    "Profile",
    "Travel writing",
    "Nature writing",
    "Food writing",
    "Narrative journalism",
    "Nonfiction book",
  ]),
  ...group("form", discipline("Dramatic writing"), [
    "Monologue",
    "One-act play",
    "Full-length play",
    "Stage musical",
    "Opera libretto",
  ]),
  ...group("form", discipline("Screenwriting"), [
    "Short screenplay",
    "Feature screenplay",
    "Television pilot",
    "Television episode",
    "Series bible",
    "Film treatment",
  ]),
  ...group(
    "form",
    [discipline("Children's writing"), discipline("Young adult writing")],
    [
      "Board book",
      "Picture book",
      "Early reader",
      "Chapter book",
      "Middle-grade book",
      "Young adult book",
    ],
  ),
  ...group("form", discipline("Comics"), [
    "Comic strip",
    "Single comic issue",
    "Comics serial",
    "Graphic novel",
    "Webcomic",
    "Minicomic",
  ]),
  ...group("form", discipline("Narrative filmmaking"), [
    "Micro-short film",
    "Short film",
    "Medium-length film",
    "Feature film",
    "Episodic film",
    "Web series",
  ]),
  ...group("form", discipline("Documentary filmmaking"), [
    "Documentary short",
    "Documentary feature",
    "Documentary series",
    "Essay film",
    "News documentary",
  ]),
  ...group("form", discipline("Experimental film"), [
    "Structural film",
    "Abstract film",
    "Found-footage film",
    "Expanded cinema",
    "Gallery film",
    "Video essay",
    "Diary film",
  ]),
  ...group("form", discipline("Animation"), [
    "Animated short",
    "Animated feature",
    "Animated series",
    "Motion graphic",
  ]),
  ...group("form", discipline("Commercial film"), [
    "Music video",
    "Fashion film",
    "Branded film",
    "Advertisement",
    "Trailer",
    "Campaign film",
  ]),
  ...group("form", discipline("Immersive film"), [
    "VR film",
    "AR narrative",
    "360 film",
    "Interactive documentary",
    "Branching narrative",
  ]),
  ...group("form", discipline("Painting"), [
    "Single painting",
    "Painting series",
    "Diptych",
    "Triptych",
    "Mural",
    "Miniature painting",
  ]),
  ...group("form", discipline("Sculpture"), [
    "Freestanding sculpture",
    "Relief sculpture",
    "Kinetic sculpture",
    "Monumental sculpture",
    "Sound sculpture",
  ]),
  ...group("form", discipline("Installation art"), [
    "Room-scale installation",
    "Interactive installation",
    "Sound installation",
    "Light installation",
    "Temporary installation",
  ]),
  ...group("form", discipline("Book arts"), [
    "Artist's book",
    "Altered book",
    "Zine",
    "Edition",
    "Print portfolio",
  ]),
  ...group("form", discipline("Public art"), [
    "Monument",
    "Memorial",
    "Public mural",
    "Civic installation",
    "Temporary public intervention",
  ]),
  ...group("form", discipline("Composition"), [
    "Solo composition",
    "Chamber work",
    "Orchestral work",
    "Choral work",
    "Opera",
    "Electroacoustic work",
    "Score",
  ]),
  ...group("form", discipline("Songwriting"), [
    "Song",
    "Art song",
    "Musical-theatre song",
    "Song cycle",
  ]),
  ...group("form", discipline("Music production"), [
    "Single",
    "EP",
    "Album",
    "Mixtape",
    "Remix",
    "Recorded live set",
  ]),
  ...group("form", discipline("Theatre directing"), [
    "Staged reading",
    "Workshop production",
    "Full production",
    "Promenade performance",
    "Site-specific production",
  ]),
  ...group("form", discipline("Dance performance"), [
    "Solo dance",
    "Duet",
    "Ensemble dance",
    "Dance production",
    "Screendance work",
  ]),
  ...group("form", discipline("Performance art"), [
    "Action",
    "Happening",
    "Intervention",
    "One-to-one performance",
    "Durational work",
  ]),
  ...group("form", discipline("Research-creation"), [
    "Research paper",
    "Abstract",
    "Conference poster",
    "Panel proposal",
    "Workshop proposal",
    "Lecture-performance",
    "Research proposal",
    "Prototype",
    "Dataset",
    "Public research output",
  ]),
  ...group("form", discipline("Digital game design"), [
    "Digital game",
    "Mobile game",
    "Browser game",
    "Game prototype",
  ]),
  ...group("form", discipline("Tabletop game design"), [
    "Board game",
    "Card game",
    "Tabletop role-playing game",
    "Live-action role-playing game",
  ]),
];

const genres = [
  ...group("genre", discipline("Poetry"), [
    "Lyric poetry",
    "Narrative poetry",
    "Dramatic poetry",
    "Epic poetry",
    "Elegy",
    "Pastoral poetry",
    "Devotional poetry",
    "Political poetry",
    "Eco-poetry",
    "Speculative poetry",
    "Confessional poetry",
    "Documentary poetry",
    "Experimental poetry",
    "Concrete poetry",
    "Prose poetry",
  ]),
  ...group("genre", discipline("Fiction"), [
    "Literary fiction",
    "Romance",
    "Science fiction",
    "Fantasy",
    "Horror",
    "Mystery",
    "Crime fiction",
    "Thriller",
    "Historical fiction",
    "Adventure fiction",
    "Western",
    "Satire",
    "Humour",
    "Speculative fiction",
    "Magical realism",
  ]),
  ...group("genre", discipline("Creative nonfiction"), [
    "Literary journalism",
    "Documentary nonfiction",
    "Cultural criticism",
    "True crime",
    "History",
    "Science writing",
    "Environmental writing",
    "Spiritual writing",
    "Humorous nonfiction",
  ]),
  ...group("genre", discipline("Narrative filmmaking"), [
    "Film drama",
    "Film comedy",
    "Film romance",
    "Film science fiction",
    "Film fantasy",
    "Film horror",
    "Film thriller",
    "Film mystery",
    "Film crime",
    "Action film",
    "Adventure film",
    "Historical film",
    "Film musical",
    "War film",
    "Family film",
  ]),
  ...group("genre", discipline("Documentary filmmaking"), [
    "Observational documentary",
    "Participatory documentary",
    "Expository documentary",
    "Poetic documentary",
    "Reflexive documentary",
    "Performative documentary",
    "Investigative documentary",
    "Archival documentary",
    "Biographical documentary",
    "Ethnographic documentary",
    "Nature documentary",
    "Music documentary",
    "Sports documentary",
  ]),
  ...group("genre", discipline("Photography"), [
    "Fine-art photography genre",
    "Social documentary photography",
    "Reportage",
    "Environmental portraiture",
    "Street photography genre",
    "Landscape photography genre",
    "Wildlife photography genre",
    "Fashion photography genre",
    "Still-life photography genre",
    "Experimental photography genre",
  ]),
  ...group("genre", discipline("Music performance"), [
    "Classical music",
    "Contemporary classical music",
    "Jazz",
    "Blues",
    "Gospel",
    "Folk music",
    "Traditional music",
    "Country",
    "Rock",
    "Pop",
    "R&B",
    "Soul",
    "Hip-hop",
    "Electronic music",
    "Reggae",
    "Latin music",
    { label: "African and diasporic music", culturallySensitive: true },
    { label: "Indigenous music", culturallySensitive: true },
  ]),
  ...group("genre", discipline("Theatre directing"), [
    "Documentary theatre genre",
    "Verbatim theatre",
    "Immersive theatre genre",
    "Theatre for young audiences",
    "Comedy theatre",
    "Tragedy",
    "Musical theatre genre",
    "Opera genre",
  ]),
  ...group("genre", discipline("Dance performance"), [
    "Classical dance",
    "Contemporary dance genre",
    "Street and club dance",
    "Folk and traditional dance",
    "Social dance genre",
    "Dance theatre genre",
  ]),
];

const subgenres = [
  ...group("subgenre", genre("Romance"), [
    "Contemporary romance",
    "Historical romance",
    "Paranormal romance",
    "Romantic comedy",
    "Romantic suspense",
  ]),
  ...group("subgenre", genre("Science fiction"), [
    "Afrofuturism",
    "Climate fiction",
    "Cyberpunk",
    "Solarpunk",
    "Space opera",
    "Hard science fiction",
    "Alternate history",
  ]),
  ...group("subgenre", genre("Fantasy"), [
    "Epic fantasy",
    "Urban fantasy",
    "Dark fantasy",
    "Sword and sorcery",
    "Magical fantasy",
  ]),
  ...group("subgenre", genre("Horror"), [
    "Folk horror",
    "Gothic horror",
    "Psychological horror",
    "Body horror",
    "Cosmic horror",
    "Supernatural horror",
  ]),
  ...group("subgenre", genre("Mystery"), [
    "Cosy mystery",
    "Police procedural",
    "Locked-room mystery",
    "Amateur detective fiction",
  ]),
  ...group("subgenre", genre("Crime fiction"), [
    "Noir",
    "Neo-noir",
    "Heist fiction",
    "Legal thriller",
    "Detective fiction",
  ]),
  ...group("subgenre", genre("Thriller"), [
    "Psychological thriller",
    "Political thriller",
    "Techno-thriller",
    "Espionage thriller",
  ]),
  ...group("subgenre", genre("Film horror"), [
    "Film folk horror",
    "Film gothic horror",
    "Film psychological horror",
    "Slasher film",
    "Creature feature",
  ]),
  ...group("subgenre", genre("Film comedy"), [
    "Film romantic comedy",
    "Dark comedy",
    "Satirical comedy",
    "Screwball comedy",
    "Mockumentary",
  ]),
  ...group("subgenre", genre("Jazz"), [
    "Traditional jazz",
    "Swing",
    "Bebop",
    "Hard bop",
    "Cool jazz",
    "Modal jazz",
    "Free jazz",
    "Jazz fusion",
    "Spiritual jazz",
  ]),
  ...group("subgenre", genre("Classical music"), [
    "Medieval music",
    "Renaissance music",
    "Baroque music",
    "Classical-period music",
    "Romantic music",
    "Modernist classical music",
    "Minimalist music",
    "Spectral music",
  ]),
  ...group("subgenre", genre("Rock"), [
    "Alternative rock",
    "Indie rock",
    "Punk rock",
    "Post-punk",
    "Heavy metal",
    "Psychedelic rock",
    "Progressive rock",
  ]),
  ...group("subgenre", genre("Pop"), [
    "Art pop",
    "Indie pop",
    "Synth-pop",
    "Dance-pop",
    "Singer-songwriter",
  ]),
  ...group("subgenre", genre("R&B"), ["Contemporary R&B", "Neo-soul", "Funk"]),
  ...group("subgenre", genre("Hip-hop"), [
    "Conscious hip-hop",
    "Alternative hip-hop",
    "Trap",
    "Drill",
    "Grime",
    "Instrumental hip-hop",
  ]),
  ...group("subgenre", genre("Electronic music"), [
    "Ambient",
    "House",
    "Techno",
    "Jungle",
    "Drum and bass",
    "UK garage",
    "Dubstep",
    "Trance",
    "Experimental electronic",
  ]),
  ...group("subgenre", genre("African and diasporic music"), [
    "Highlife",
    "Afrobeats",
    "Afrobeat",
    "Amapiano",
    "Jùjú",
    "Fújì",
    "Soukous",
    "Makossa",
    "Mbalax",
    "Gqom",
    "Palm-wine music",
    "Afro-jazz",
  ]),
  ...group("subgenre", genre("Latin music"), [
    "Salsa",
    "Son cubano",
    "Reggaeton",
    "Bachata",
    "Merengue",
    "Samba",
    "Bossa nova",
  ]),
  ...group("subgenre", genre("Reggae"), [
    "Roots reggae",
    "Dancehall",
    "Dub",
    "Soca",
    "Calypso",
  ]),
];

const media = [
  ...group("medium", practice("Writing & literature"), [
    "Text",
    "Print",
    "Paper",
    "Book",
    "Manuscript",
    "PDF",
    "Digital text",
  ]),
  ...group("medium", practice("Visual arts"), [
    "Graphite",
    "Charcoal",
    "Pastel",
    "Chalk",
    "Ink",
    "Silverpoint",
    "Coloured pencil",
    "Oil paint",
    "Acrylic paint",
    "Watercolour",
    "Gouache",
    "Tempera",
    "Encaustic",
    "Fresco",
    "Spray paint",
    "Pigment",
    "Stone",
    "Wood",
    "Metal",
    "Plaster",
    "Resin",
    "Found objects",
    "Mixed media",
  ]),
  ...group("medium", practice("Photography"), [
    "Analogue photography",
    "Digital photography",
    "Large-format photography",
    "Medium-format photography",
    "Mobile photography",
    "Instant photography",
  ]),
  ...group("medium", practice("Film & moving image"), [
    "Digital video",
    "16mm film",
    "35mm film",
    "8mm film",
    "Celluloid film",
    "Animation media",
    "Projection",
  ]),
  ...group("medium", practice("Music & sound"), [
    "Audio",
    "Recorded music",
    "Live sound",
    "Radio",
    "Spatial audio",
    "Voice",
    "Musical instruments",
  ]),
  ...group("medium", practice("Craft & material arts"), [
    "Clay",
    "Ceramic",
    "Glass",
    "Fibre",
    "Textile",
    "Leather",
    "Natural fibre",
    "Reed",
    "Cane",
    "Tile",
    "Lacquer",
  ]),
  ...group("medium", practice("Performance & live art"), [
    "Body",
    "Movement",
    "Live performance",
    "Public space",
  ]),
  ...group("medium", practice("Digital, interactive & immersive arts"), [
    "Software",
    "Code",
    "Data",
    "Web",
    "Game engine",
    "Electronics",
    "Robotics",
    "Virtual reality",
    "Augmented reality",
    "Mixed reality",
    "Spatial media",
  ]),
  ...group(
    "medium",
    practice("Architecture, spatial practice & public realm"),
    ["Built space", "Landscape", "Interior space", "Public realm"],
  ),
];

const techniques = [
  ...group("technique", discipline("Printmaking"), [
    "Relief printing",
    "Woodcut",
    "Linocut",
    "Intaglio",
    "Etching",
    "Engraving",
    "Drypoint",
    "Aquatint",
    "Lithography",
    "Screenprinting",
    "Monotype",
    "Risograph",
    "Letterpress",
  ]),
  ...group("technique", discipline("Experimental photography"), [
    "Cyanotype",
    "Tintype",
    "Wet plate",
    "Photogram",
    "Pinhole photography",
    "Infrared photography",
    "Cameraless photography",
    "Image manipulation",
  ]),
  ...group("technique", discipline("Animation"), [
    "2D animation",
    "3D animation",
    "Stop motion",
    "Clay animation",
    "Cut-out animation",
    "Puppet animation",
    "Rotoscoping",
    "Paint-on-glass animation",
    "Sand animation",
  ]),
  ...group("technique", discipline("Music production"), [
    "Sampling",
    "Remixing",
    "Synthesis",
    "Multitrack recording",
    "Improvisation",
    "Live electronics",
  ]),
  ...group("technique", discipline("Textile art"), [
    "Hand weaving",
    "Machine weaving",
    "Knitting",
    "Crochet",
    "Embroidery technique",
    "Quilting technique",
    "Felting",
    "Dyeing",
    "Tapestry",
    "Surface printing",
  ]),
  ...group("technique", discipline("Ceramics"), [
    "Wheel throwing",
    "Hand building",
    "Slip casting",
    "Glazing",
    "Raku",
  ]),
  ...group("technique", discipline("Glass art"), [
    "Glass blowing",
    "Glass casting",
    "Kiln forming",
    "Stained glass",
    "Lampworking",
  ]),
  ...group("technique", discipline("Digital fabrication"), [
    "3D printing",
    "CNC milling",
    "Laser cutting",
    "Parametric modelling",
  ]),
  ...group("technique", discipline("Creative coding"), [
    "Generative coding",
    "Live coding technique",
    "Machine learning",
    "Computer vision",
    "Procedural generation",
  ]),
];

const modes = [
  "Analogue",
  "Digital",
  "Hybrid",
  "Traditional",
  "Contemporary",
  "Experimental",
  "Narrative",
  "Abstract",
  "Figurative",
  "Conceptual",
  "Documentary",
  "Fictional",
  "Speculative",
  "Solo",
  "Collaborative",
  "Collective",
  "Site-specific",
  "Place-based",
  "Public-space",
  "Online",
  "Participatory",
  "Co-created",
  "Community-led",
  "Socially engaged",
  "Immersive",
  "Interactive",
  "Durational",
  "Live",
  "Research-led",
  "Process-led",
  "Material-led",
  "Ecological",
  "Sustainable",
  "Repair-based",
  "Reuse-based",
  "Interdisciplinary",
  "Multidisciplinary",
  "Transdisciplinary",
  "Accessible",
  "Disability-led",
].map((input) => makeTerm("mode", input));

const roles = [
  ...group("role", practice("Writing & literature"), [
    "Writer",
    "Poet",
    "Novelist",
    "Essayist",
    "Playwright",
    "Screenwriter",
    "Translator",
    "Journalist",
    "Critic",
    "Editor",
    "Publisher",
    "Storyteller",
  ]),
  ...group("role", practice("Visual arts"), [
    "Visual artist",
    "Painter",
    "Sculptor",
    "Printmaker",
    "Installation artist",
    "Public artist",
    "Muralist",
  ]),
  ...group("role", practice("Photography"), [
    "Photographer",
    "Photojournalist",
    "Photo editor",
  ]),
  ...group("role", practice("Film & moving image"), [
    "Director",
    "Producer",
    "Filmmaker",
    "Cinematographer",
    "Film editor",
    "Animator",
    "Production designer",
    "Costume designer",
    "Sound designer",
    "Composer for media",
    "Colourist",
    "Visual-effects artist",
    "Casting director",
    "Actor",
    "Distributor",
    "Film programmer",
  ]),
  ...group("role", practice("Music & sound"), [
    "Composer",
    "Songwriter",
    "Musician",
    "Performer",
    "Vocalist",
    "Conductor",
    "Music producer",
    "Recording engineer",
    "Sound artist",
    "DJ",
  ]),
  ...group("role", practice("Dance & choreography"), [
    "Choreographer",
    "Dancer",
    "Rehearsal director",
    "Movement director",
    "Dance filmmaker",
    "Dance dramaturg",
  ]),
  ...group("role", practice("Theatre & dramatic arts"), [
    "Theatre director",
    "Theatre maker",
    "Dramaturg",
    "Stage manager",
    "Lighting designer",
    "Set designer",
    "Puppeteer",
    "Comedian",
  ]),
  ...group("role", practice("Design"), [
    "Designer",
    "Graphic designer",
    "Product designer",
    "UX designer",
    "Interaction designer",
    "Design researcher",
  ]),
  ...group("role", practice("Architecture, spatial practice & public realm"), [
    "Architect",
    "Landscape architect",
    "Urban designer",
    "Planner",
    "Spatial practitioner",
  ]),
  ...group("role", practice("Craft & material arts"), [
    "Craftsperson",
    "Maker",
    "Ceramicist",
    "Jeweller",
    "Metalsmith",
    "Weaver",
    "Woodworker",
  ]),
  ...group("role", practice("Digital, interactive & immersive arts"), [
    "Creative technologist",
    "Developer",
    "Creative coder",
    "Interactive artist",
  ]),
  ...group("role", practice("Games & playful media"), [
    "Game designer",
    "Narrative designer",
    "Game writer",
    "Game artist",
    "Game developer",
  ]),
  ...group("role", practice("Curatorial, cultural & publishing practice"), [
    "Curator",
    "Researcher",
    "Archivist",
    "Conservator",
    "Arts educator",
    "Facilitator",
    "Programmer",
    "Arts producer",
    "Arts administrator",
  ]),
  ...group("role", practice("Interdisciplinary, hybrid & emerging practice"), [
    "Collective",
    "Duo",
    "Ensemble",
    "Band",
    "Company",
    "Organisation",
  ]),
];

const themes = [
  "Identity",
  "Belonging",
  "Memory",
  "History",
  "Heritage",
  "Migration",
  "Diaspora",
  "Place",
  "Home",
  "Community",
  "Family",
  "Childhood",
  "Ageing",
  "Love",
  "Grief",
  "Care",
  "Health",
  "Disability",
  "Gender",
  "Sexuality",
  "Race",
  "Class",
  "Labour",
  "Justice",
  "Human rights",
  "Conflict",
  "Peace",
  "Politics",
  "Democracy",
  "Climate",
  "Environment",
  "Ecology",
  "Land",
  "Food",
  "Technology",
  "Science",
  "Futures",
  "Spirituality",
  "Language",
  "Archive",
].map((input) => makeTerm("theme", input));

const audiences = [
  "General audience",
  "Children",
  "Early readers",
  "Middle grade",
  "Young adult",
  "Adult",
  "Family",
  "Community",
  "Professional",
  "Scholarly",
  "Schools",
  "Educators",
].map((input) => makeTerm("audience", input));

const languages: TaxonomySeedTerm[] = (
  [
    { label: "English", aliases: ["en"] },
    { label: "Yorùbá", aliases: ["yo"] },
    { label: "Igbo", aliases: ["ig"] },
    { label: "Hausa", aliases: ["ha"] },
    { label: "French", aliases: ["fr"] },
    { label: "Portuguese", aliases: ["pt"] },
    { label: "Arabic", aliases: ["ar"] },
    { label: "Spanish", aliases: ["es"] },
    { label: "German", aliases: ["de"] },
    { label: "Swahili", aliases: ["Kiswahili", "sw"] },
    { label: "Nigerian Pidgin", aliases: ["Naijá", "pcm"] },
    "Multilingual",
    "Bilingual",
    "Non-verbal",
    "Language-neutral",
  ] as TermInput[]
).map((input) => makeTerm("language", input));

export const TAXONOMY_TERMS: TaxonomySeedTerm[] = [
  ...practiceFamilies,
  ...disciplines,
  ...forms,
  ...genres,
  ...subgenres,
  ...media,
  ...techniques,
  ...modes,
  ...roles,
  ...themes,
  ...audiences,
  ...languages,
];

export const MISSA_TAXONOMY: TaxonomySeedCatalog = {
  scheme: {
    id: "taxscheme_missa-creative-practice",
    key: "missa-creative-practice",
    label: "Missa creative practice taxonomy",
    description:
      "A versioned, faceted concept graph for creative practices, forms, genres, media, roles, themes, audiences, and languages.",
    version: 1,
  },
  facets: TAXONOMY_FACETS,
  terms: TAXONOMY_TERMS,
};
