// Generated by scripts/build-illustration-sprites.mjs. Do not edit by hand.

export const ILLUSTRATION_SPRITE_ROOT = "/illustrations/library-v2";

export const ILLUSTRATIONS = {
  "cover-award": {
    "sprite": "covers.svg",
    "viewBox": "-14.2 -11.9 614.4 460.8"
  },
  "cover-contest": {
    "sprite": "covers.svg",
    "viewBox": "-4.8 6.2 607.5 455.6"
  },
  "cover-exhibition": {
    "sprite": "covers.svg",
    "viewBox": "-14.4 -12.3 628.8 471.6"
  },
  "cover-fellowship": {
    "sprite": "covers.svg",
    "viewBox": "-39.1 -24 681.2 510.9"
  },
  "cover-festival": {
    "sprite": "covers.svg",
    "viewBox": "7.6 -25.3 628.8 471.6"
  },
  "cover-grant": {
    "sprite": "covers.svg",
    "viewBox": "5.6 -9.4 603.8 452.8"
  },
  "cover-magazine": {
    "sprite": "covers.svg",
    "viewBox": "-19.8 -19.3 647.5 485.6"
  },
  "cover-open-call": {
    "sprite": "covers.svg",
    "viewBox": "22.5 9.4 575 431.2"
  },
  "cover-publication": {
    "sprite": "covers.svg",
    "viewBox": "-37.6 -29.2 679.3 509.5"
  },
  "cover-residency": {
    "sprite": "covers.svg",
    "viewBox": "-55.3 -36.6 693.7 520.3"
  },
  "scene-hero": {
    "sprite": "homepage.svg",
    "viewBox": "-49 -48.5 743.9 495.9"
  },
  "scene-after-find": {
    "sprite": "homepage.svg",
    "viewBox": "-84.6 -65.9 788.3 506.8"
  },
  "scene-questions": {
    "sprite": "homepage.svg",
    "viewBox": "17 -36.3 565.9 471.6"
  },
  "scene-close": {
    "sprite": "homepage.svg",
    "viewBox": "-40 -35 682.1 468.9"
  },
  "spot-tracker": {
    "sprite": "homepage.svg",
    "viewBox": "24.9 15.9 559.1 447.3"
  },
  "spot-reminders": {
    "sprite": "homepage.svg",
    "viewBox": "12.6 6.5 573.8 459"
  },
  "spot-portfolio": {
    "sprite": "homepage.svg",
    "viewBox": "-13.9 -23.5 638.8 511"
  }
} as const;

export type IllustrationId = keyof typeof ILLUSTRATIONS;
