/*
 * The Missa illustration library (v2), drawn from SVG sprites with <use> so
 * the art takes the page's colours (--art-ink, --art-accent,
 * --art-background) and stays out of the JavaScript bundle. Sprites and ids
 * are generated by scripts/build-illustration-sprites.mjs from
 * public/illustrations/library-v2/compact/. Every drawing is decorative.
 */

import {
  ILLUSTRATIONS,
  ILLUSTRATION_SPRITE_ROOT,
  type IllustrationId,
} from "./library-v2.generated";
import styles from "./missa-illustrations.module.css";

function href(id: IllustrationId) {
  return `${ILLUSTRATION_SPRITE_ROOT}/${ILLUSTRATIONS[id].sprite}#${id}`;
}

/**
 * Which cover each call type uses (types from radar-engine OpportunityType);
 * rfp, commission, job and other fall back to the open-call pinboard.
 */
const COVER_FOR_TYPE: Record<string, string> = {
  "open-call": "open-call",
  magazine: "magazine",
  pitch: "publication",
  grant: "grant",
  scholarship: "grant",
  award: "award",
  contest: "contest",
  fellowship: "fellowship",
  conference: "fellowship",
  residency: "residency",
  festival: "festival",
  exhibition: "exhibition",
};

/** The paper tint behind each cover, so a grid of cards reads as a set. */
const COVER_TONE: Record<string, "ochre" | "lichen" | "accent" | "mineral"> = {
  magazine: "ochre",
  publication: "ochre",
  award: "ochre",
  contest: "lichen",
  residency: "lichen",
  grant: "accent",
  "open-call": "accent",
  fellowship: "mineral",
  festival: "mineral",
  exhibition: "mineral",
};

export function coverKey(type: string | null | undefined) {
  return COVER_FOR_TYPE[type ?? ""] ?? "open-call";
}

/** The call type's cover: the 4:3 drawing whole and centred on its tint. */
export function CallCover({ type }: { type: string | null | undefined }) {
  const key = coverKey(type);
  return (
    <svg
      className={styles.cover}
      data-tone={COVER_TONE[key]}
      aria-hidden="true"
      focusable="false"
    >
      <use href={href(`cover-${key}` as IllustrationId)} width="100%" height="100%" />
    </svg>
  );
}

/** A scene or spot at its own proportions, as wide as its container. */
export function MissaArt({
  id,
  reverse = false,
  className,
}: {
  id: Extract<IllustrationId, `scene-${string}` | `spot-${string}`>;
  /** White ink for a Forest ground. */
  reverse?: boolean;
  className?: string;
}) {
  const [, , width, height] = ILLUSTRATIONS[id].viewBox.split(/\s+/).map(Number);
  return (
    <svg
      className={className ? `${styles.art} ${className}` : styles.art}
      data-reverse={reverse || undefined}
      viewBox={`0 0 ${width} ${height}`}
      aria-hidden="true"
      focusable="false"
    >
      <use href={href(id)} width={width} height={height} />
    </svg>
  );
}
