/*
 * The Missa illustration library (v2), drawn from SVG sprites with <use> so
 * the art takes the page's colours (--art-ink, --art-accent,
 * --art-background) and stays out of the JavaScript bundle. Sprites and ids
 * are generated by scripts/build-illustration-sprites.mjs from
 * public/illustrations/library-v2/compact/. Every drawing is decorative.
 */

import {
  ILLUSTRATIONS,
  ILLUSTRATION_SPRITE_ROOT,
  type IllustrationId,
} from "./library-v2.generated";
import { coverKey, type CoverKey } from "@/lib/callCover";
import styles from "./missa-illustrations.module.css";

function href(id: IllustrationId) {
  return `${ILLUSTRATION_SPRITE_ROOT}/${ILLUSTRATIONS[id].sprite}#${id}`;
}

/** The paper tint behind each cover, so a grid of cards reads as a set. */
const COVER_TONE: Record<CoverKey, "ochre" | "lichen" | "accent" | "mineral"> = {
  magazine: "ochre",
  publication: "ochre",
  award: "ochre",
  contest: "lichen",
  residency: "lichen",
  grant: "accent",
  "open-call": "accent",
  fellowship: "mineral",
  festival: "mineral",
  exhibition: "mineral",
};

/**
 * The call's cover: the 4:3 drawing whole and centred on its tint. The type
 * decides it, or the title when the call is filed only as an open call.
 */
export function CallCover({
  type,
  title,
}: {
  type: string | null | undefined;
  title?: string | null;
}) {
  const key = coverKey(type, title);
  return (
    <svg
      className={styles.cover}
      data-tone={COVER_TONE[key]}
      aria-hidden="true"
      focusable="false"
    >
      <use href={href(`cover-${key}` as IllustrationId)} width="100%" height="100%" />
    </svg>
  );
}

/** A scene or spot at its own proportions, as wide as its container. */
export function MissaArt({
  id,
  reverse = false,
  className,
}: {
  id: Extract<IllustrationId, `scene-${string}` | `spot-${string}`>;
  /** White ink for a Forest ground. */
  reverse?: boolean;
  className?: string;
}) {
  const [, , width, height] = ILLUSTRATIONS[id].viewBox.split(/\s+/).map(Number);
  return (
    <svg
      className={className ? `${styles.art} ${className}` : styles.art}
      data-reverse={reverse || undefined}
      viewBox={`0 0 ${width} ${height}`}
      aria-hidden="true"
      focusable="false"
    >
      <use href={href(id)} width={width} height={height} />
    </svg>
  );
}

/**
 * A drawing for an empty state, with the one-line AI label that
 * docs/missa-messaging.md requires wherever an AI illustration appears.
 * "scene" for a whole empty page, "spot" for a small empty list.
 */
export function EmptyStateArt({
  id,
  size = "scene",
}: {
  id: Extract<IllustrationId, `scene-${string}` | `spot-${string}`>;
  size?: "scene" | "spot";
}) {
  return (
    <figure className={styles.emptyArt} data-size={size}>
      <MissaArt id={id} />
      <figcaption>Illustration made with AI.</figcaption>
    </figure>
  );
}
