import Link from 'next/link';
import { getProfileRepository } from '@/lib/profileRepository';

export const dynamic = 'force-dynamic';

export default async function JournalsPage({ searchParams }: { searchParams?: Promise<{ q?: string; kind?: string; page?: string }> }) {
  const params = searchParams ? await searchParams : {};
  const repository = getProfileRepository();
  const page = Math.max(Number(params.page ?? '1') || 1, 1);
  const result = repository ? await repository.browse({ query: params.q, kind: params.kind === 'small_press' ? 'small_press' : params.kind === 'literary_magazine' ? 'literary_magazine' : undefined, limit: 48, offset: (page - 1) * 48 }) : { items: [], total: 0 };
  const pageCount = Math.ceil(result.total / 48);
  const pageHref = (value: number) => `/journals?${new URLSearchParams({ ...(params.q ? { q: params.q } : {}), ...(params.kind ? { kind: params.kind } : {}), page: String(value) }).toString()}`;
  return <main className="mx-auto min-h-screen max-w-6xl px-6 py-16"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-purple-700">Missa directory</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Journals & small presses</h1><p className="mt-4 max-w-2xl text-lg text-slate-600">Explore the publications Gary has learned from Poets & Writers, then open their current and related calls.</p><form className="mt-8 flex flex-wrap gap-3" role="search"><input name="q" defaultValue={params.q} placeholder="Search a journal or press" className="min-w-72 rounded-lg border px-4 py-3" /><select name="kind" defaultValue={params.kind ?? ''} className="rounded-lg border px-4 py-3"><option value="">Journals and presses</option><option value="literary_magazine">Journals</option><option value="small_press">Small presses</option></select><button className="rounded-lg bg-purple-900 px-5 py-3 font-medium text-white">Search</button></form><p className="mt-8 text-sm text-slate-500">{result.total.toLocaleString()} profiles · page {page} of {Math.max(pageCount, 1)}</p>{result.items.length ? <div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{result.items.map((item) => <Link key={item.id} href={`/journals/${encodeURIComponent(item.id)}`} className="rounded-xl border p-5 transition hover:border-purple-700"><div className="flex gap-4">{item.mediaUrl ? <img src={item.mediaUrl} alt="" className="h-14 w-14 rounded-lg object-cover" /> : <div className="h-14 w-14 rounded-lg bg-slate-100" />}<div><h2 className="font-semibold">{item.name}</h2><p className="text-sm text-slate-500">{item.kind === 'small_press' ? 'Small press' : 'Literary journal'}</p></div></div><p className="mt-4 line-clamp-3 text-sm text-slate-600">{item.summary || 'Profile details are being assembled from the canonical source.'}</p><p className="mt-3 text-xs text-slate-500">PW profile checked {item.profileCheckedAt ? new Date(item.profileCheckedAt).toLocaleDateString() : 'not yet'}</p></Link>)}</div> : <div className="mt-8 rounded-xl border border-dashed p-8 text-slate-600">The profile directory is not available in this environment yet.</div>}{pageCount > 1 ? <nav className="mt-8 flex gap-3"><>{page > 1 ? <Link className="rounded-lg border px-4 py-2" href={pageHref(page - 1)}>Previous</Link> : null}{page < pageCount ? <Link className="rounded-lg border px-4 py-2" href={pageHref(page + 1)}>Next</Link> : null}</></nav> : null}</main>;
}
