// Generated by scripts/build-magazine-guidelines.mjs from reviewed research.
// Each fact was quoted from the magazine's own submission guidelines and the
// quote was checked against the live page. Do not edit by hand.
import type { MagazineGuidelineRecord } from "../../live/guidelineFacts.js";

export const MAGAZINE_GUIDELINES: MagazineGuidelineRecord[] = [
  {
    "profileId": "org_krouse_3_am_magazine_22",
    "name": "3:AM Magazine",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "no payment",
      "url": "https://www.3ammagazine.com/3am/submissions/",
      "quote": "Please note, we do not pay for contributions."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_adirondack_review_94",
    "name": "Adirondack Review",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 2,
      "url": "https://theadirondackreview.submittable.com/submit",
      "quote": "we have decided to charge $2 for submissions"
    },
    "pay": {
      "kind": "cash",
      "url": "https://theadirondackreview.submittable.com/submit",
      "quote": "help us pay editors and contributors $25 each for their work"
    },
    "response": null,
    "status": {
      "value": "hiatus",
      "url": "https://theadirondackreview.submittable.com/submit",
      "quote": "UPDATE 2020: we are on hiatus and are not accepting submissions at this time."
    }
  },
  {
    "profileId": "org_litmag_alta_journal_60",
    "name": "Alta Journal",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "less than 3 months",
      "url": "https://altajournal.submittable.com/submit",
      "quote": "We read all submissions within 90 days and will contact you if we’re interested in publishing your work."
    },
    "status": null
  },
  {
    "profileId": "org_subm_1985",
    "name": "American Literary Review",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 4,
      "url": "https://americanliteraryreview.com/submit/",
      "quote": "General submissions can be sent to us through our online submission manager for a fee of $4."
    },
    "pay": {
      "kind": "cash",
      "url": "https://americanliteraryreview.com/submit/",
      "quote": "Yes, we are now paying those selected for publication of from the general poetry, fiction and essay submissions!"
    },
    "response": {
      "band": "greater than 6 months",
      "url": "https://americanliteraryreview.com/submit/",
      "quote": "We respond to submissions in approximately six to eight months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_antioch_review",
    "name": "Antioch Review",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://antiochcollege.edu/antioch-review/writers-guidelines/",
      "quote": "Fee: There is no submission fee."
    },
    "pay": {
      "kind": "cash",
      "url": "https://antiochcollege.edu/antioch-review/writers-guidelines/",
      "quote": "Payment is upon printed publication at the rate of $20.00 per printed page (about 425 words)"
    },
    "response": null,
    "status": {
      "value": "hiatus",
      "url": "https://antiochcollege.edu/antioch-review/writers-guidelines/",
      "quote": "while The Antioch Review is on hiatus, submissions for future issues currently are not being accepted."
    }
  },
  {
    "profileId": "org_litmag_arkansas_review_89",
    "name": "Arkansas Review",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "greater than 6 months",
      "url": "https://arkreview.org/?page_id=605",
      "quote": "Please allow three to twelve months for notification of acceptance or rejection."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_arts_letters",
    "name": "Arts & Letters",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 3,
      "url": "https://artsandletters.gcsu.edu/submit/",
      "quote": "we charge a $3 fee (about the cost of submitting by post)"
    },
    "pay": {
      "kind": "cash",
      "url": "https://artsandletters.gcsu.edu/submit/",
      "quote": "Payment Upon Publication: $10 per printed page (minimum payment: $50), and one contributor copy"
    },
    "response": {
      "band": "less than 3 months",
      "url": "https://artsandletters.gcsu.edu/submit/",
      "quote": "Average notification time for acceptance is 8-12 weeks."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_bamboo_ridge_18",
    "name": "Bamboo Ridge",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://www.bambooridge.org/featured/call-for-submissions-issue-126/",
      "quote": "There is no reading fee. Contributors retain all rights and receive an honorarium of $50"
    },
    "pay": {
      "kind": "cash",
      "url": "https://www.bambooridge.org/featured/call-for-submissions-issue-126/",
      "quote": "receive an honorarium of $50, a copy of the issue"
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_bare_life_review_69",
    "name": "Bare Life Review",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://barelifereview.submittable.com/submit",
      "quote": "We now offer $750 for accepted full-length prose pieces, $300 for accepted poems or shorter print journal prose"
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_barrelhouse",
    "name": "Barrelhouse",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://www.barrelhousemag.com/submission-info",
      "quote": "We pay $50 to each contributor to our print and online issues, as well as two contributor copies."
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://www.barrelhousemag.com/submission-info",
      "quote": "It will probably take us ~six months to get back to you."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_birmingham_poetry_review",
    "name": "Birmingham Poetry Review",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "contributor copies only",
      "url": "https://www.uab.edu/cas/englishpublications/bpr/submit",
      "quote": "Pay is one copy of the Birmingham Poetry Review."
    },
    "response": {
      "band": "less than 3 months",
      "url": "https://www.uab.edu/cas/englishpublications/bpr/submit",
      "quote": "We usually report on submissions within one to three months, and we occasionally comment on rejections."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_bloomsday_literary_12",
    "name": "Bloomsday Literary",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "less than 3 months",
      "url": "https://www.bloomsdayliterary.com/submissions",
      "quote": "Bloomsday accepts only electronic copies and will return an inquiry in 2-6 weeks of submission."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_briar_cliff_review",
    "name": "Briar Cliff Review",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "contributor copies only",
      "url": "https://www.bcreview.org/general",
      "quote": "If accepted, you will receive two contributor's copies of The Briar Cliff Review"
    },
    "response": null,
    "status": {
      "value": "closed",
      "url": "https://www.bcreview.org/general",
      "quote": "Our last issue, Volume 35, will be published on April 20, 2023."
    }
  },
  {
    "profileId": "org_litmag_broadsided_press_19",
    "name": "Broadsided Press",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 3,
      "url": "https://broadsidedpress.submittable.com/submit",
      "quote": "we must charge a $3 fee for each submission"
    },
    "pay": {
      "kind": "no payment",
      "url": "https://broadsidedpress.submittable.com/submit",
      "quote": "We do not, at this time, pay staff or contributors for their work"
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_calyx",
    "name": "Calyx",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "3 to 6 months",
      "url": "https://calyxinc.submittable.com/submit",
      "quote": "It may take up to six months to receive a response from us."
    },
    "status": null
  },
  {
    "profileId": "org_9a6a1b57539b9ecc92a10dfd",
    "name": "CHEAP POP",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "no payment",
      "url": "https://cheappoplit.com/submit/",
      "quote": "We cannot pay authors right now, but we'll do everything we can to promote you and your work."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_chicago_quarterly",
    "name": "Chicago Quarterly",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "contributor copies only",
      "url": "https://www.chicagoquarterlyreview.com/submissions/",
      "quote": "Two copies of the Chicago Quarterly Review."
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://www.chicagoquarterlyreview.com/submissions/",
      "quote": "We try to respond within 6 months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_colorado_review",
    "name": "Colorado Review",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 3,
      "url": "https://coloradoreview.colostate.edu/colorado-review/",
      "quote": "The fee for online submissions is $3."
    },
    "pay": {
      "kind": "cash",
      "url": "https://coloradoreview.colostate.edu/colorado-review/",
      "quote": "Colorado Review pays $300 for short stories and nonfiction"
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://coloradoreview.colostate.edu/colorado-review/",
      "quote": "within four months (and sometimes quicker)"
    },
    "status": null
  },
  {
    "profileId": "org_litmag_comment_77",
    "name": "Comment",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://comment.org/submissions/",
      "quote": "Comment pays all contributors an honorarium."
    },
    "response": {
      "band": "less than 3 months",
      "url": "https://comment.org/submissions/",
      "quote": "We aim to respond to all submissions within six weeks."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_cortland_review_48",
    "name": "Cortland Review",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "3 to 6 months",
      "url": "https://www.cortlandreview.com/submission-guidelines/",
      "quote": "The Cortland Review does its best respond to all submissions within 3-4 months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_crab_orchard_review",
    "name": "Crab Orchard Review",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "no payment",
      "url": "https://www.siucraborchardreview.com/",
      "quote": "No monetary payment, but your work will be promoted online"
    },
    "response": {
      "band": "less than 3 months",
      "url": "https://www.siucraborchardreview.com/",
      "quote": "Response time: 2 weeks to 2 months"
    },
    "status": null
  },
  {
    "profileId": "org_litmag_creative_nonfiction_22",
    "name": "Creative Nonfiction",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": null,
    "status": {
      "value": "closed",
      "url": "https://niemanstoryboard.org/2024/11/27/passing-the-torch-of-the-creative-nonfiction-movement/",
      "quote": "After shutting down the magazine and co-editing the anthology with Leslie Rubinkowski, his former student"
    }
  },
  {
    "profileId": "org_litmag_cutthroat_84",
    "name": "Cutthroat",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": null,
      "url": "https://cutthroatajournalofthearts.submittable.com/submit",
      "quote": "There is a small reading fee."
    },
    "pay": null,
    "response": {
      "band": "3 to 6 months",
      "url": "https://cutthroatajournalofthearts.submittable.com/submit",
      "quote": "Give us two to six months to make a decision."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_deep_wild_journal_62",
    "name": "Deep Wild Journal",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://deepwildjournal.com/submit/",
      "quote": "Writers are allowed one free submission in any open-reading period."
    },
    "pay": {
      "kind": "contributor copies only",
      "url": "https://deepwildjournal.com/submit/",
      "quote": "Contributors will receive two copies of the journal in which their work appears"
    },
    "response": {
      "band": "less than 3 months",
      "url": "https://deepwildjournal.com/submit/",
      "quote": "We will strive to respond to all submissions within three months after our submissions window closes"
    },
    "status": {
      "value": "hiatus",
      "url": "https://deepwildjournal.com/submit/",
      "quote": "Deep Wild Journal is currently on hiatus while we undergo editorial changes."
    }
  },
  {
    "profileId": "org_subm_11395",
    "name": "Denver Quarterly",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 5,
      "url": "https://denverquarterly.submittable.com/submit",
      "quote": "we will be implementing a $5.00 submission fee per submission"
    },
    "pay": {
      "kind": "contributor copies only",
      "url": "https://denverquarterly.submittable.com/submit",
      "quote": "Contributors receive two copies of the issues in which their work appears and a year-long subscription."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_ecw_press_99",
    "name": "ECW Press",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "3 to 6 months",
      "url": "https://ecwpress.com/pages/submissions",
      "quote": "if you do not hear from an editor within four months, please assume that your book is not the right fit"
    },
    "status": null
  },
  {
    "profileId": "org_litmag_el_palacio_0",
    "name": "El Palacio",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://elpalacio.org/contact-us/",
      "quote": "We pay for all commissioned work."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_artconn_16a659ee86802224",
    "name": "Epiphany",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://epiphanymagazine.submittable.com/submit",
      "quote": "In print, we pay $75 per poem and $175 per essay or story."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_epoch",
    "name": "Epoch",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 3,
      "url": "https://www.epochliterary.com/submit",
      "quote": "Each submission costs $3, and a portion of each fee, after processing costs, is donated to the Cornell Prison Education Program"
    },
    "pay": {
      "kind": "cash",
      "url": "https://www.epochliterary.com/submit",
      "quote": "We presently pay between $100 and $500 for poetry, prose, and comics, depending on length"
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_examined_life_5",
    "name": "Examined Life",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 5,
      "url": "https://theexaminedlifejournal.com/submit/",
      "quote": "Note: There is a $5 submission fee charged for each nonfiction or fiction submission."
    },
    "pay": null,
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_field",
    "name": "Field",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": null,
    "status": {
      "value": "closed",
      "url": "https://www2.oberlin.edu/ocpress/submissions.html",
      "quote": "Since FIELD #100 (Spring 2019) will be the final issue, we are no longer considering submissions."
    }
  },
  {
    "profileId": "org_92ae9155b55f1d472d58c4b5",
    "name": "Fractured",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://www.fracturedlit.com/submit",
      "quote": "We do not charge any submission fees"
    },
    "pay": {
      "kind": "cash",
      "url": "https://www.fracturedlit.com/submit",
      "quote": "We pay our authors $50 for original Micro Fiction and $75 for original Flash Fiction."
    },
    "response": {
      "band": "less than 3 months",
      "url": "https://www.fracturedlit.com/submit",
      "quote": "Please allow us up to three months to inform you if we have accepted your work for publication."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_gargoyle",
    "name": "Gargoyle",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "no payment",
      "url": "https://gargoylemagazine.com/faq/",
      "quote": "Nada. We moved online in 2022."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_good_river_review_63",
    "name": "Good River Review",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "3 to 6 months",
      "url": "https://www.goodriverreview.com/submissions",
      "quote": "Response time is up to four months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_gordon_square_review_90",
    "name": "Gordon Square Review",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "http://www.gordonsquarereview.org/submit.html",
      "quote": "Writers accepted for publication receive a $25 honorarium."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_grain_magazine",
    "name": "Grain Magazine",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://grainmagazine.ca/submit",
      "quote": "All contributors, regardless of genre, are paid $50 per page to a maximum of $250"
    },
    "response": {
      "band": "greater than 6 months",
      "url": "https://grainmagazine.ca/submit",
      "quote": "In general, you should receive a response within six to eight months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_grayson_books_51",
    "name": "Grayson Books",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "less than 3 months",
      "url": "https://graysonbooks.com/pages/submissions",
      "quote": "You will receive feedback on your proposal within two months; very often it only takes a couple of weeks."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_grist",
    "name": "Grist",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 4,
      "url": "https://gristjournal.com/submit/",
      "quote": "is $4 for three to five poems, for one work of fiction up to 7,000 words"
    },
    "pay": {
      "kind": "cash",
      "url": "https://gristjournal.com/submit/",
      "quote": "Payment is $10 per poem or 1 cent per word for prose (up to $50), as well as a contributor copy."
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://gristjournal.com/submit/",
      "quote": "Average response time is six months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_gulf_coast",
    "name": "Gulf Coast",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 3,
      "url": "https://gulfcoastmag.org/submit/",
      "quote": "Gulf Coast has instituted a small reading fee ($3) for regular submissions"
    },
    "pay": {
      "kind": "cash",
      "url": "https://gulfcoastmag.org/submit/",
      "quote": "Gulf Coast is now able to pay $50 per .doc or PDF page for poetry, fiction, and nonfiction in our print issues."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_healing_muse",
    "name": "Healing Muse",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "contributor copies only",
      "url": "https://healingmuse.submittable.com/submit",
      "quote": "Contributors will receive two complimentary copies of the issue in which their work appears"
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_heart_poems_13",
    "name": "Heart Poems",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://nostalgiapress.com/submissions-2/",
      "quote": "PAY: $25 upon publication on website and digital copy if published in issue."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_here_a_poetry_journal_33",
    "name": "Here: A Poetry Journal",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "contributor copies only",
      "url": "https://www.easternct.edu/here-poetry-journal/submissions.html",
      "quote": "After the work is published, the author will receive two contributor's copies."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_high_desert_journal_56",
    "name": "High Desert Journal",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://highdesertjournal.submittable.com/submit",
      "quote": "We pay $50 for accepted fiction and nonfiction, and $50 per poet (up to three poems)."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_cf7f2073c7f2662cc6bdad8f",
    "name": "Honey Literary",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "no payment",
      "url": "https://honeyliterary.com/submit/",
      "quote": "We are currently not a paying market"
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_hysterical_rag_84",
    "name": "Hysterical Rag",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://hystericalrag.submittable.com/submit",
      "quote": "At the time of this writing, payment is $50 per accepted prose piece or group of poems."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_indianapolis_review_91",
    "name": "Indianapolis Review",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://theindianapolisreview.com/submit/",
      "quote": "Submissions are FREE. However, because of this, we are not a paying market at this time."
    },
    "pay": {
      "kind": "no payment",
      "url": "https://theindianapolisreview.com/submit/",
      "quote": "Submissions are FREE. However, because of this, we are not a paying market at this time."
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://theindianapolisreview.com/submit/",
      "quote": "Please allow up to 4 months for a response."
    },
    "status": null
  },
  {
    "profileId": "org_subm_17446",
    "name": "Inverted Syntax",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 4,
      "url": "http://www.invertedsyntax.com/fissured-tongue-series-guidelines.html",
      "quote": "The general submission fees ($4) covers our administration costs."
    },
    "pay": null,
    "response": {
      "band": "greater than 6 months",
      "url": "http://www.invertedsyntax.com/fissured-tongue-series-guidelines.html",
      "quote": "our response time can range from 3 months to a year"
    },
    "status": null
  },
  {
    "profileId": "org_litmag_iron_horse_literary_review",
    "name": "Iron Horse Literary Review",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 3,
      "url": "https://ironhorse.submittable.com/submit",
      "quote": "Iron Horse Literary Review charges a $3 submission fee for each regular manuscript submitted to our office"
    },
    "pay": {
      "kind": "cash",
      "url": "https://www.ironhorsereview.com/submit",
      "quote": "We pay $100 per essay or story, and $50 per poem or flash piece for our themed and open issues."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_irreantum_92",
    "name": "Irreantum",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://irreantum.associationmormonletters.org/submission-guidelines/",
      "quote": "We have begun paying for the work we publish"
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_jersey_devil_74",
    "name": "Jersey Devil",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "no payment",
      "url": "https://www.jerseydevilpress.com/?page_id=71",
      "quote": "Speaking of greedy, we can’t pay you."
    },
    "response": {
      "band": "less than 3 months",
      "url": "https://www.jerseydevilpress.com/?page_id=71",
      "quote": "within twelve weeks, feel free to send a follow-up query"
    },
    "status": null
  },
  {
    "profileId": "org_litmag_jewish_currents_66",
    "name": "Jewish Currents",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://jewishcurrents.org/submissions",
      "quote": "commits to paying freelancers 25% upon receipt of a draft, and 75% upon completion"
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_jewish_fiction_86",
    "name": "Jewish Fiction",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "3 to 6 months",
      "url": "https://jewishfiction.com/submit-a-story/",
      "quote": "We aim to reply to all submissions within a timeframe of four months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_juked",
    "name": "Juked",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "no payment",
      "url": "https://juked.submittable.com/submit",
      "quote": "We do not yet pay our contributors with hard currency, but are hopeful that will change sometime in the future."
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://juked.submittable.com/submit",
      "quote": "we will catch up to our goal of responding within four months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_kitchen_work_44",
    "name": "Kitchen Work",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://www.kitchenwork.com/submissions",
      "quote": "Authors of accepted submissions are paid $0.20 per word."
    },
    "response": {
      "band": "less than 3 months",
      "url": "https://www.kitchenwork.com/submissions",
      "quote": "Accepted submissions will receive responses within 30 days of submission."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_laurel_review_30",
    "name": "Laurel Review",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 2,
      "url": "https://thelaurelreview.submittable.com/submit",
      "quote": "Poetry $2.00 $2.00 Guidelines for Poetry Guidelines Submit to Poetry"
    },
    "pay": {
      "kind": "contributor copies only",
      "url": "https://thelaurelreview.submittable.com/submit",
      "quote": "All accepted US contributors will receive two copies of the issue in which they appear."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_leon_literary_review_21",
    "name": "Leon Literary Review",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "less than 3 months",
      "url": "https://leonliteraryreview.submittable.com/submit",
      "quote": "Look for our response within two tp three months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_literal_latte",
    "name": "Literal Latte",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://www.literal-latte.com/submissions/",
      "quote": "There is NO processing fee for submissions mailed via regular post."
    },
    "pay": null,
    "response": {
      "band": "3 to 6 months",
      "url": "https://www.literal-latte.com/submissions/",
      "quote": "it takes us approximately 3-6 months to respond"
    },
    "status": null
  },
  {
    "profileId": "org_litmag_literary_matters_86",
    "name": "Literary Matters",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 3,
      "url": "https://www.literarymatters.org/submissions/",
      "quote": "Non-members pay a $3 fee when submitting work."
    },
    "pay": {
      "kind": "cash",
      "url": "https://www.literarymatters.org/submissions/",
      "quote": "Contributors receive $50 per poem/translation/essay/story and $30 per review/review essay."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_literary_review",
    "name": "Literary Review",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://literaryreview.submittable.com/submit",
      "quote": "No, we do not charge a fee to read your submission."
    },
    "pay": {
      "kind": "cash",
      "url": "https://literaryreview.submittable.com/submit",
      "quote": "we have been able to pay our contributors an honorarium"
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://literaryreview.submittable.com/submit",
      "quote": "We aim to reply in three to six months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_litmag",
    "name": "Litmag",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://litmag.com/submit/",
      "quote": "Upon acceptance, we pay $300 for full-length fiction or nonfiction (5,000+ words)"
    },
    "response": {
      "band": "greater than 6 months",
      "url": "https://litmag.com/submit/",
      "quote": "strive to send a decision within nine months"
    },
    "status": null
  },
  {
    "profileId": "org_litmag_live_encounters_79",
    "name": "Live Encounters",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "no payment",
      "url": "https://liveencounters.net/how-to-contribute-to-live-encounters/",
      "quote": "As we are a not for profit organisation we cannot offer any remuneration."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_longreads_4",
    "name": "Longreads",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://longreads.com/submissions/",
      "quote": "Our rate for personal essays is $500."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_louisiana_literature",
    "name": "Louisiana Literature",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "less than 3 months",
      "url": "https://www.louisianaliterature.org/submissions/",
      "quote": "We endeavor to respond to all submissions within 30-45 days."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_mcneese_review",
    "name": "McNeese Review",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 3,
      "url": "https://www.mcneese.edu/thereview/post-2/submissions/",
      "quote": "There is a $3 charge for submitting to help offset production costs."
    },
    "pay": {
      "kind": "cash",
      "url": "https://www.mcneese.edu/thereview/post-2/submissions/",
      "quote": "All print contributors receive one contributor copy and a $50 honorarium."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_mcsweeney_s",
    "name": "McSweeney's",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://www.mcsweeneys.net/pages/guidelines-for-web-submissions",
      "quote": "We are thrilled to report that there will be payment for all accepted general, open letter, and lists submissions."
    },
    "response": {
      "band": "less than 3 months",
      "url": "https://www.mcsweeneys.net/pages/guidelines-for-web-submissions",
      "quote": "Average response time is 7.39 days."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_mercer_univ_press_99",
    "name": "Mercer Univ. Press",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "3 to 6 months",
      "url": "https://www.mupress.org/Submission-Guidelines.aspx",
      "quote": "This normally takes a few weeks for a proposal or 3-6 months for a complete manuscript."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_midwest_review_94",
    "name": "Midwest Review",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "contributor copies only",
      "url": "https://midwestreview.org/submissions/",
      "quote": "Payment is in one free issue copy."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_midwestern_gothic",
    "name": "Midwestern Gothic",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "contributor copies only",
      "url": "http://midwestgothic.com/submissions/",
      "quote": "you will receive a complimentary digital copy of the issue"
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_mizna",
    "name": "MIZNA",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://mizna.org/literary/submissions/",
      "quote": "There are no submission fees."
    },
    "pay": {
      "kind": "cash",
      "url": "https://mizna.org/literary/submissions/",
      "quote": "Selected contributors will receive a $200 honorarium"
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_moon_tide_press_44",
    "name": "Moon Tide Press",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "3 to 6 months",
      "url": "https://www.moontidepress.com/contact-us",
      "quote": "Please allow at least 3 - 6 months for our team to get back to you on the status of your manuscript."
    },
    "status": null
  },
  {
    "profileId": "org_subm_1597",
    "name": "New Orleans Review",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://neworleansreview.submittable.com/submit",
      "quote": "Honorarium is $175 per piece, regardless of length."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_new_south",
    "name": "New South",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": null,
      "url": "https://www.newsouthjournal.com/submissions-new-south/",
      "quote": "For a small fee that’s roughly the cost of printing and posting paper submissions"
    },
    "pay": null,
    "response": null,
    "status": null
  },
  {
    "profileId": "org_edc5663352b34d77d76b6c30",
    "name": "Nimrod",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://nimrod.utulsa.edu/submissions-guidelines/",
      "quote": "General online submissions are free. Our next window for general poetry"
    },
    "pay": {
      "kind": "cash",
      "url": "https://nimrod.utulsa.edu/submissions-guidelines/",
      "quote": "We pay $20 per poem and page of prose, with a $300 maximum."
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://nimrod.utulsa.edu/submissions-guidelines/",
      "quote": "Turn-around time for general submissions is one to five months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_notre_dame_review",
    "name": "Notre Dame Review",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://ndreview.nd.edu/submissions/",
      "quote": "A small gratuity is paid after publication."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_obsidian",
    "name": "Obsidian",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "3 to 6 months",
      "url": "https://obsidian.submittable.com/submit",
      "quote": "Expect three to six months for a decision."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_on_the_seawall_96",
    "name": "On the Seawall",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://www.ronslate.com/submit/",
      "quote": "There is no submission fee."
    },
    "pay": null,
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_one_story",
    "name": "One Story",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://one-story.com/write/submit-a-story/",
      "quote": "One Story pays $500 and 25 contributors copies for First Serial North American rights."
    },
    "response": {
      "band": "less than 3 months",
      "url": "https://one-story.com/write/submit-a-story/",
      "quote": "We do our best to respond to submissions within 3 months after they are received."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_one_teen_story",
    "name": "One Teen Story",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://one-story.com/write/one-teen-story-contest/",
      "quote": "Stories should have teens as their main characters and be about the teen experience. No entry fee is required."
    },
    "pay": {
      "kind": "cash",
      "url": "https://one-story.com/write/one-teen-story-contest/",
      "quote": "The contest winners will receive $500 upon publication."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_one_throne",
    "name": "One Throne",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "no payment",
      "url": "https://onethrone.submittable.com/submit",
      "quote": "We highly-value writing, but unfortunately do not offer monetary compensation"
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_outlook_springs_87",
    "name": "Outlook Springs",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://outlooksprings.submittable.com/submit",
      "quote": "Payment is $10 per poem, $10 per flash piece (under 1,000 words), $25 for short fiction and essays (over 1,000 words)."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_parentheses_journal_45",
    "name": "Parentheses Journal",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "no payment",
      "url": "http://www.parenthesesjournal.com/submit/",
      "quote": "We are currently a non-paying market."
    },
    "response": {
      "band": "less than 3 months",
      "url": "http://www.parenthesesjournal.com/submit/",
      "quote": "Please allow up to 3 months for us to inform you if we’ve selected your work for publication."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_pidgeonholes_7",
    "name": "Pidgeonholes",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "less than 3 months",
      "url": "https://pidgeonholes.submittable.com/submit",
      "quote": "We hope to respond to all submissions within three months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_pitt_poetry_series_23",
    "name": "Pitt Poetry Series",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 25,
      "url": "https://upittpress.org/poetry-submissions/",
      "quote": "Each manuscript must be accompanied by a $25.00 fee, paid through Submittable at the time of your submission."
    },
    "pay": null,
    "response": null,
    "status": null
  },
  {
    "profileId": "org_subm_6983",
    "name": "Porkbelly Press",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "contributor copies only",
      "url": "https://porkbellypress.com/subs",
      "quote": "Compensation for chaps/micros is offered in the form of 10 handsewn copies"
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://porkbellypress.com/subs",
      "quote": "We do our best to reply to submissions within 5-20 weeks, but the time does vary with a high submission volume."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_pulp_literature",
    "name": "Pulp Literature",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://pulpliterature.com/submissions/submission-guidelines/",
      "quote": "We pay $0.05 – $0.08 per word for short stories (to 5000 words)"
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://pulpliterature.com/submissions/submission-guidelines/",
      "quote": "It takes us roughly six months to read submissions."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_purple_passion_press",
    "name": "Purple Passion Press",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://purplepassionpress.com/submissions/",
      "quote": "Purple Passion Press pays $15 for any one accepted piece."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_pushcart_press_40",
    "name": "Pushcart Press",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "http://pushcartprize.com/nomination.html",
      "quote": "There is no entry fee and no form to fill out."
    },
    "pay": null,
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_qwerty",
    "name": "QWERTY",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://qwertymagazine.submittable.com/submit",
      "quote": "Authors curated for this issue will receive $15 per selection."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_cs_cc3abcf4426bff80",
    "name": "Room",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://roommagazine.com/submit-poetry-prose/",
      "quote": "We charge an optional fee for regular submissions, with a free option for accessibility."
    },
    "pay": {
      "kind": "cash",
      "url": "https://roommagazine.com/submit-poetry-prose/",
      "quote": "We pay $50 CAD per page (up to a maximum of $200)"
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://roommagazine.com/submit-poetry-prose/",
      "quote": "Our average response time is between two weeks and six months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_ruminate",
    "name": "Ruminate",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://ruminatemagazine.submittable.com/submit",
      "quote": "Ruminate Magazine currently pays $20/page for poetry and prose."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_salmagundi_magazine",
    "name": "Salmagundi Magazine",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "greater than 6 months",
      "url": "https://salmagundi.skidmore.edu/submissions",
      "quote": "If you do not hear back from us within a year, it means we did not find a space for your work in our magazine"
    },
    "status": null
  },
  {
    "profileId": "org_krouse_sand_10",
    "name": "SAND",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://sandjournal.com/submit",
      "quote": "We currently pay semi-professional rates, which vary based on our funding situation"
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://sandjournal.com/submit",
      "quote": "Please allow six months for a response before sending an inquiry."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_shade_journal",
    "name": "Shade Journal",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "less than 3 months",
      "url": "https://www.shadeliteraryarts.org/submit",
      "quote": "You will receive a response within a month of your submission."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_sixfold",
    "name": "Sixfold",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 5,
      "url": "https://www.sixfold.org/how-it-works/submission-guidelines",
      "quote": "In order to participate in a vote, you must submit a $5.00 USD payment through your Sixfold account."
    },
    "pay": null,
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_slice",
    "name": "Slice",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://slice.submittable.com/submit",
      "quote": "We offer contributors $400 for long stories and essays, $150 for flash fiction, and $100 for poems."
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://slice.submittable.com/submit",
      "quote": "Please allow up to four months after the end of the reading period for us to reply to your submission."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_smoke_long_quarterly",
    "name": "Smoke Long Quarterly",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://www.smokelong.com/guidelines/",
      "quote": "We will always have a free-submission period."
    },
    "pay": {
      "kind": "cash",
      "url": "https://www.smokelong.com/guidelines/",
      "quote": "We pay $100/$150 with audio, upon publication in the quarterly issue."
    },
    "response": {
      "band": "less than 3 months",
      "url": "https://www.smokelong.com/guidelines/",
      "quote": "please allow us up to four weeks to inform you if we have accepted your work for publication."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_southern_indiana_review",
    "name": "Southern Indiana Review",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 4,
      "url": "https://www.usi.edu/sir/submission-guidelines",
      "quote": "The $4.00 upload charge for"
    },
    "pay": {
      "kind": "cash",
      "url": "https://www.usi.edu/sir/submission-guidelines",
      "quote": "SIR pays contributing authors at two rates: $125 (five layout pages or fewer accepted for publication)"
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_sparks_of_calliope_68",
    "name": "Sparks of Calliope",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "no payment",
      "url": "https://sparksofcalliope.com/submission-guidelines/",
      "quote": "No payment is given for accepted poems, and authors retain their copyright."
    },
    "response": {
      "band": "less than 3 months",
      "url": "https://sparksofcalliope.com/submission-guidelines/",
      "quote": "You should receive a response within 90 days."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_springhouse",
    "name": "Springhouse",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "3 to 6 months",
      "url": "https://www.springhousejournal.com/Issue1/Submissions",
      "quote": "We strive to respond within six months of receipt of the submission."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_tar_river",
    "name": "Tar River",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 3,
      "url": "https://tarriverpoetry.com/submit-page/",
      "quote": "the $3 reading fee per submission funds the journal."
    },
    "pay": null,
    "response": {
      "band": "less than 3 months",
      "url": "https://tarriverpoetry.com/submit-page/",
      "quote": "our response time for regular submissions is usually within three months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_terminus_17",
    "name": "Terminus",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": null,
    "status": {
      "value": "hiatus",
      "url": "https://poetry.gatech.edu/terminus",
      "quote": "Terminus is currently on hiatus. Stay tuned for our return!"
    }
  },
  {
    "profileId": "org_american_scholar",
    "name": "The American Scholar",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://theamericanscholar.org/contact-us/",
      "quote": "We pay up to $500 for accepted pieces."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_subm_12788",
    "name": "The Comstock Review",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "http://comstockreview.org/open-reading-period/",
      "quote": "There is NO FEE for poems submitted during this Open Reading Period."
    },
    "pay": null,
    "response": {
      "band": "less than 3 months",
      "url": "http://comstockreview.org/open-reading-period/",
      "quote": "Replies may be sent up to 2 months after the close of the reading period."
    },
    "status": null
  },
  {
    "profileId": "org_cs_f76e3bc0ddc043c3",
    "name": "The Forge",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://forgelitmag.com/submit/",
      "quote": "Free submissions open on the 1st of each month January"
    },
    "pay": {
      "kind": "cash",
      "url": "https://forgelitmag.com/about/",
      "quote": "we pay our contributors, and our taste is wide-ranging and eclectic"
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_hopper_the_65",
    "name": "The Hopper",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 3,
      "url": "http://www.hoppermag.org/submit",
      "quote": "From June 22 to July 31, submissions will be $3 to cover our essential operating costs."
    },
    "pay": null,
    "response": null,
    "status": null
  },
  {
    "profileId": "org_hudson_review",
    "name": "The Hudson Review",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://hudsonreview.com/about-us/regular-submissions/",
      "quote": "We do not charge submission fees."
    },
    "pay": null,
    "response": {
      "band": "3 to 6 months",
      "url": "https://hudsonreview.com/about-us/regular-submissions/",
      "quote": "Please note that as we take great care in considering submissions, a decision may take up to six months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_lake_the",
    "name": "The Lake",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "no payment",
      "url": "https://www.thelakepoetry.co.uk/submit/",
      "quote": "The Lake is run on a super-low budget out of my bank account so cannot pay for publication of your work."
    },
    "response": {
      "band": "less than 3 months",
      "url": "https://www.thelakepoetry.co.uk/submit/",
      "quote": "I will respond to all submissions within two to three"
    },
    "status": null
  },
  {
    "profileId": "org_yale_review",
    "name": "The Yale Review",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://yalereview.org/submissions",
      "quote": "we pay between $250 and $1,000 for prose, and $150 for poems online or in print."
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_tin_house",
    "name": "Tin House",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": null,
    "status": {
      "value": "closed",
      "url": "https://www.shelf-awareness.com/theshelf/2018-12-14/tin_house_magazine_to_cease_publication_in_2019.html",
      "quote": "Respected literary journal Tin House will cease publication next year with its 20th anniversary issue in June"
    }
  },
  {
    "profileId": "org_litmag_tint_journal",
    "name": "Tint Journal",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://tintjournal.com/submit/submission-guidelines",
      "quote": "There is no submission fee."
    },
    "pay": {
      "kind": "no payment",
      "url": "https://tintjournal.com/submit/submission-guidelines",
      "quote": "We do not have the financial resources to compensate the contributing writers to our literary issues at this point"
    },
    "response": {
      "band": "less than 3 months",
      "url": "https://tintjournal.com/submit/submission-guidelines",
      "quote": "Allow for a time period of up to two months between the end of a call and an answer."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_torch_literary_arts_46",
    "name": "Torch Literary Arts",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://www.torchliteraryarts.org/torchmagazine",
      "quote": "There is no fee to submit and all accepted features are paid for publication."
    },
    "pay": {
      "kind": "cash",
      "url": "https://www.torchliteraryarts.org/torchmagazine",
      "quote": "There is no fee to submit and all accepted features are paid for publication."
    },
    "response": {
      "band": "less than 3 months",
      "url": "https://torchliteraryarts.submittable.com/submit",
      "quote": "Expect up to three months for a decision."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_transition",
    "name": "Transition",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "3 to 6 months",
      "url": "https://transition.submittable.com/submit",
      "quote": "We generally respond to all submissions within four months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_true_story_42",
    "name": "True Story",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 3,
      "url": "https://creativenonfiction.org/submission/true-story-2/",
      "quote": "There is a $3 reading fee, waived for current True Story and/or Creative Nonfiction subscribers."
    },
    "pay": {
      "kind": "cash",
      "url": "https://creativenonfiction.org/submission/true-story-2/",
      "quote": "pay $750 on publication and give you 10 free copies of"
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://creativenonfiction.org/submission/true-story-2/",
      "quote": "do our best to respond to submissions within four months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_tule_review",
    "name": "Tule Review",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": false,
      "amountUSD": null,
      "url": "https://www.sacramentopoetrycenter.com/tule-review-submissions/",
      "quote": "There is no fee for submissions."
    },
    "pay": null,
    "response": null,
    "status": null
  },
  {
    "profileId": "org_virginia_quarterly_review",
    "name": "Virginia Quarterly Review",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://www.vqronline.org/about-vqr/submissions",
      "quote": "For short fiction, we generally pay $1,000 and above."
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://www.vqronline.org/about-vqr/submissions",
      "quote": "We make every effort to respond within six months, but response time will vary according to the number of submissions."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_volta",
    "name": "Volta",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "no payment",
      "url": "https://voltamagazine.org/submissions",
      "quote": "we are not able to offer any fiscal compensation for authors at this time"
    },
    "response": {
      "band": "less than 3 months",
      "url": "https://voltamagazine.org/submissions",
      "quote": "We aim to respond to all general submissions within 2-3 months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_war_horse_81",
    "name": "War Horse",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "cash",
      "url": "https://thewarhorse.org/freelance-pitches/",
      "quote": "Most freelance assignments fall between $1,000 and $3,500"
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_water_stone_review",
    "name": "Water-Stone Review",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "contributor copies only",
      "url": "https://waterstonereview.com/submissions/",
      "quote": "Payment is in two copies of the issue in which the author"
    },
    "response": null,
    "status": null
  },
  {
    "profileId": "org_litmag_waxwing_literary_journal_78",
    "name": "Waxwing Literary Journal",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "no payment",
      "url": "https://waxwing.submittable.com/submit",
      "quote": "Unfortunately, Waxwing is not a paying market at this time."
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://waxwing.submittable.com/submit",
      "quote": "We try to respond to submissions within six months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_western_humanities_review",
    "name": "Western Humanities Review",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": {
      "kind": "contributor copies only",
      "url": "https://www.westernhumanitiesreview.com/submissions/",
      "quote": "Western Humanities Review will pay you two copies of the print version of the magazine; there will be no other payment or royalty."
    },
    "response": {
      "band": "greater than 6 months",
      "url": "https://www.westernhumanitiesreview.com/submissions/",
      "quote": "It can take 9 months or more for your submission to go through our review process"
    },
    "status": null
  },
  {
    "profileId": "org_litmag_white_pine_press",
    "name": "White Pine Press",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": {
      "band": "3 to 6 months",
      "url": "https://www.whitepine.org/submissions",
      "quote": "It generally takes between three and six months for unsolicited material to be read by our editorial staff."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_worcester_review_85",
    "name": "Worcester Review",
    "checkedOn": "2026-10-04",
    "fee": {
      "charges": true,
      "amountUSD": 4,
      "url": "https://www.theworcesterreview.org/submit/",
      "quote": "$4 per submission in Submittable."
    },
    "pay": {
      "kind": "cash",
      "url": "https://www.theworcesterreview.org/submit/",
      "quote": "a small honorarium (via PayPal). In recent years, the honorarium was $20 for each writer."
    },
    "response": {
      "band": "3 to 6 months",
      "url": "https://www.theworcesterreview.org/submit/",
      "quote": "Our response time ranges from two weeks to four months."
    },
    "status": null
  },
  {
    "profileId": "org_litmag_wordfarm_2",
    "name": "Wordfarm",
    "checkedOn": "2026-10-04",
    "fee": null,
    "pay": null,
    "response": null,
    "status": {
      "value": "hiatus",
      "url": "https://www.wordfarm.net/submissions.php",
      "quote": "We are currently on hiatus and closed to new submissions"
    }
  }
];
