import {
  createWork,
  emptyPortfolio,
  type PortfolioData,
  type PortfolioWork,
} from "./creator-portfolio-schema";

/**
 * A fictional creator used by design reviews and the homepage. Every
 * organization named here is fictional too; contact actions stay inert.
 */
export function sampleCreatorPortfolio(): PortfolioData {
  const year = new Date().getUTCFullYear();
  return {
    ...emptyPortfolio(),
    handle: "rileychen",
    name: "Riley Chen",
    statement:
      "Poems, images and field recordings about how places carry memory.",
    bio: "Riley works across text, field recording and photography to trace the quiet geographies that hold us, and the ones we leave behind. Based between Vancouver and Taipei. Teaches occasional workshops on writing from sound.",
    location: "Vancouver ↔ Taipei",
    photo: "/media/creator-preview-portrait.webp",
    selected: ["Poet", "Sound artist", "Photographer"],
    lens: "writing",
    hero: "portrait",
    theme: "sage",
    now: {
      text: "In residence at Saltmarsh Writers’ House. Finishing a second collection.",
      until: `${year + 1}-01-31`,
    },
    openTo: [
      { id: "o_1", label: "Commissions", state: "open", date: "" },
      { id: "o_2", label: "Readings and talks", state: "open", date: "" },
      {
        id: "o_3",
        label: "Residencies",
        state: "from",
        date: `${year + 1}-03-01`,
      },
    ],
    works: (
      [
        {
          id: "w_atlas",
          title: "An atlas of small departures",
          kind: "Poem sequence",
          year: String(year),
          summary:
            "Poems and photographs made on trains, one per trip, over three years.",
          caption: "Archival pigment prints and nine poems",
          text: "The train window holds the lake\nthe way a palm holds water —\nbriefly, and with all of itself.\n\nA heron lifts. The carriage keeps\nits small promises: the next stop,\nthe next stop, the tea gone cold.\n\nI write the hills down as they leave.\nNot to keep them. To be the kind\nof person who was there.",
          image: "/media/creator-preview-landscape.webp",
          audio: "",
          url: "",
          formats: [],
          featured: true,
        },
        {
          id: "w_glossary",
          title: "Tidal glossary",
          kind: "Poem",
          year: String(year),
          summary: "",
          caption: "",
          text: "Ebb: what the water owes the shore.\nNeap: a month that forgets to pull.\nWrack: the line where we left things,\nand the things that stayed.\n\nSlack: the hour before turning,\nwhen nothing is decided\nand the boats lean the same way.",
          image: "",
          audio: "",
          url: "",
          formats: [],
          featured: false,
        },
        {
          id: "w_rooms",
          title: "The rooms remember us",
          kind: "Photographic essay",
          year: String(year - 1),
          summary:
            "Homes photographed after the people who shaped them have moved on.",
          caption: "22 photographs",
          text: "",
          image: "/media/home/portfolio-still-life.webp",
          audio: "",
          url: "",
          formats: [],
          featured: false,
        },
        {
          id: "w_threshold",
          title: "Threshold studies",
          kind: "Photographs and notes",
          year: String(year - 2),
          summary: "Images and notes made between rehearsal and performance.",
          caption: "9 photographs, 3 texts",
          text: "A room holding its breath.\nThe chairs facing the same way.",
          image: "/media/home/artist-at-work.webp",
          audio: "",
          url: "",
          formats: [],
          featured: false,
        },
      ] as Partial<PortfolioWork>[]
    ).map(createWork),
    shelf: [
      {
        id: "s_field",
        kind: "book",
        title: "Field notes from the in-between",
        publisher: "Northlight Press",
        year: String(year - 1),
        cover: "/media/creator-preview-book.webp",
        url: "",
        note: "Forty-one poems written between ferries, trains and waiting rooms.",
      },
      {
        id: "s_weather",
        kind: "chapbook",
        title: "Small weather",
        publisher: "Harbour Editions",
        year: String(year - 3),
        cover: "",
        url: "",
        note: "Edition of 200. Out of print.",
      },
    ],
    record: [
      {
        id: "r_1",
        kind: "publication",
        title: "“Tidal glossary”, Issue 14",
        venue: "The Quiet Review",
        year: String(year),
        url: "",
        provenance: "confirmed",
      },
      {
        id: "r_2",
        kind: "prize",
        title: "Longlisted, Harbour Prize for Poetry",
        venue: "Harbour Arts Council",
        year: String(year),
        url: "",
        provenance: "linked",
      },
      {
        id: "r_3",
        kind: "residency",
        title: "Writer in residence, six weeks",
        venue: "Saltmarsh Writers’ House",
        year: String(year - 1),
        url: "",
        provenance: "linked",
      },
      {
        id: "r_4",
        kind: "grant",
        title: "Research grant",
        venue: "Coastline Arts Fund",
        year: String(year - 2),
        url: "",
        provenance: "added",
      },
    ],
    events: [
      {
        id: "e_1",
        kind: "Reading",
        title: "Reading from Field notes",
        date: `${year + 1}-01-18`,
        time: "19:00",
        place: "Saltmarsh Writers’ House, Fife",
        url: "",
        status: "free",
      },
      {
        id: "e_2",
        kind: "Listening session",
        title: "A frequency for the footpath",
        date: `${year + 1}-02-02`,
        time: "15:00",
        place: "Ferry Building Gallery, Vancouver",
        url: "",
        status: "few",
      },
    ],
    press: [
      {
        id: "p_1",
        quote:
          "Chen listens the way a field recorder does — patiently, and to everything at once.",
        source: "Editor’s note, The Quiet Review",
        url: "https://example.com/quiet-review",
      },
    ],
    editions: [
      {
        id: "ed_1",
        title: "Indigo Hours III",
        image: "/media/home/gallery-interior.webp",
        medium: "Relief print",
        size: "56 × 76 cm",
        year: String(year),
        total: 12,
        available: 4,
        note: "Printed by hand on cotton rag paper.",
      },
    ],
    shows: [
      {
        id: "sh_1",
        year: String(year),
        title: "Indigo Hours",
        venue: "Saltmarsh Writers’ House, Fife",
        kind: "solo",
        url: "",
      },
      {
        id: "sh_2",
        year: String(year - 1),
        title: "Salt and Iron",
        venue: "Ferry Building Gallery, Vancouver",
        kind: "group",
        url: "",
      },
      {
        id: "sh_3",
        year: String(year - 1),
        title: "Undertow, for voice and tape",
        venue: "Harbour Arts Council",
        kind: "premiere",
        url: "",
      },
    ],
    collaborators: [
      {
        id: "c_1",
        handle: "tonioliver",
        name: "Toni Oliver",
        role: "Composed the score for Cloth Choir",
        confirmed: true,
      },
      {
        id: "c_2",
        handle: "anareis",
        name: "Ana Reis",
        role: "Designed Field notes from the in-between",
        confirmed: true,
      },
    ],
    booking: {
      shortBio:
        "Riley Chen is a poet, sound artist and photographer based between Vancouver and Taipei.",
      longBio:
        "Riley Chen writes poems, records fields and photographs rooms to trace the quiet geographies that hold us. Their first collection, Field notes from the in-between, appeared with Northlight Press.",
      // Design samples have no server, so these carry the facts a server would
      // have read from the stored files. Their addresses are not real downloads.
      files: [
        {
          id: "bf_1",
          label: "Tech rider",
          file: "/api/creator/portfolio-media/0a0a0a0a-0a0a-4a0a-8a0a-0a0a0a0a0a01",
          type: "pdf",
          bytes: 245_760,
        },
        {
          id: "bf_2",
          label: "Press kit",
          file: "/api/creator/portfolio-media/0a0a0a0a-0a0a-4a0a-8a0a-0a0a0a0a0a02",
          type: "zip",
          bytes: 18 * 1024 * 1024,
        },
      ],
    },
    services: [
      {
        id: "sv_1",
        title: "Commissioned poems",
        timing: "3–4 weeks",
        price: "On request",
        note: "For occasions, books and rooms.",
      },
      {
        id: "sv_2",
        title: "Readings and talks",
        timing: "Booked a season ahead",
        price: "",
        note: "",
      },
    ],
    teaching: [
      {
        id: "t_1",
        title: "Writing from sound, two days",
        date: `${year + 1}-03-09`,
        place: "Lisbon",
        places: 3,
        note: "For writers who want to work from recordings.",
      },
    ],
    support: {
      label: "Support Riley’s next collection",
      url: "https://example.com/support-riley",
      note: "Payments happen outside Missa.",
    },
    contact: {
      email: "",
      website: "https://example.com",
      instagram: "",
      newsletter: "",
    },
    modules: [
      { id: "work", visible: true },
      { id: "shelf", visible: true },
      { id: "record", visible: true },
      { id: "upcoming", visible: true },
      { id: "press", visible: true },
      { id: "about", visible: true },
      { id: "shows", visible: true, added: true },
      { id: "editions", visible: true, added: true },
      { id: "collaborators", visible: true, added: true },
      { id: "booking", visible: true, added: true },
      { id: "services", visible: true, added: true },
      { id: "teaching", visible: true, added: true },
      { id: "support", visible: true, added: true },
    ],
  };
}
