export const opportunityTypes = [
  "open-call",
  "magazine",
  "grant",
  "award",
  "fellowship",
  "residency",
  "festival",
  "scholarship",
  "conference",
  "rfp",
  "contest",
  "pitch",
  "exhibition",
  "commission",
  "job",
  "other",
] as const;
export const goalDirections = [
  {
    id: "publish",
    label: "Publish my work",
    types: ["magazine", "pitch"],
    noun: "submissions",
    next: "Choose a piece to submit",
  },
  {
    id: "residency",
    label: "Apply for a residency",
    types: ["residency"],
    noun: "residency applications",
    next: "Choose a work sample",
  },
  {
    id: "fellowship",
    label: "Apply for a fellowship",
    types: ["fellowship"],
    noun: "fellowship applications",
    next: "Outline my project proposal",
  },
  {
    id: "grant",
    label: "Find funding",
    types: ["grant"],
    noun: "grant applications",
    next: "Draft my project budget",
  },
  {
    id: "prize",
    label: "Enter a prize",
    types: ["award", "contest"],
    noun: "prize entries",
    next: "Choose work to enter",
  },
  {
    id: "other",
    label: "Something else",
    types: [],
    noun: "applications",
    next: "Choose an opportunity to prepare for",
  },
] as const;
