import {fileURLToPath} from 'node:url';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import nextEnv from '@next/env';
import pg from 'pg';
import {chromium} from 'playwright';
import {expect} from '@playwright/test';
import {createSessionToken} from '@missa/radar-engine';
import AxeBuilder from '@axe-core/playwright';
nextEnv.loadEnvConfig(fileURLToPath(new URL('../../apps/web/',import.meta.url)),true,{info(){},error(){}});
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL}),id=`goal-ui-${randomUUID()}`,email=`${id}@example.invalid`,browser=await chromium.launch();
try {
 await pool.query('insert into radar_accounts(id,email,data) values($1,$2,$3)',[id,email,JSON.stringify({id,email,userId:id,active:true})]);
 await pool.query('insert into notification_preferences(account_id) values($1)',[id]);
 const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();
 await page.context().addCookies([{name:'missa_session',value:createSessionToken(id,process.env.MISSA_SESSION_SECRET,new Date()),url:'http://localhost:3100'}]);
 await page.goto('http://localhost:3100/goals');
 await page.getByRole('button',{name:'Create your first goal'}).click();
 await page.getByRole('button',{name:'Poetry',exact:true}).click();
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('button',{name:'6',exact:true}).click();
 await page.getByLabel('By when?').fill('2027-12-31');
 await page.getByRole('button',{name:/Choose organizations/}).click();
 await page.getByRole('dialog').getByRole('button',{pressed:false}).first().waitFor();
 const orgResponse=await page.request.get('http://localhost:3100/api/me/goals?search=&kind=organization&discipline=poetry');
 const orgs=(await orgResponse.json()).targets;assert(orgs.length>0);assert(orgs.every(t=>t.kind==='organization'));
 await page.getByRole('dialog').getByRole('button',{name:new RegExp(orgs[0].name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'))}).click();
 await page.getByRole('button',{name:'Done',exact:true}).click();
 await page.getByRole('button',{name:/Choose opportunities/}).click();
 await page.getByRole('textbox',{name:'Search opportunities'}).waitFor();
 const callsResponse=await page.request.get('http://localhost:3100/api/me/goals?search=&kind=opportunity&discipline=poetry');
 const calls=(await callsResponse.json()).targets;assert(calls.length>0);assert(calls.every(t=>t.kind==='opportunity'));
 await page.getByRole('button',{name:'Done',exact:true}).click();
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('button',{name:'Back',exact:true}).click();assert.equal(await page.getByLabel('Submissions to make').inputValue(),'6');
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByLabel('What will you do first?').fill('Revise three poems');
 let body;page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/api/me/goals'))body=r.postDataJSON();});
 await page.route('**/api/me/goals',async route=>{if(route.request().method()==='POST'){await route.fulfill({status:503,json:{error:'Temporary test error'}});await page.unroute('**/api/me/goals');}else await route.continue();});
 await page.getByRole('button',{name:'Create my goal',exact:true}).click();await page.getByText('Temporary test error',{exact:false}).waitFor();
 assert.equal(await page.getByLabel('What will you do first?').inputValue(),'Revise three poems');
 await page.getByRole('button',{name:'Create my goal',exact:true}).click();await page.getByRole('heading',{name:'Submit 6 poetry applications',exact:true}).waitFor();
 await page.reload();await page.getByRole('heading',{name:'Submit 6 poetry applications',exact:true}).waitFor();
 const replay=await page.request.post('http://localhost:3100/api/me/goals',{data:body});assert(replay.ok());
 const saved=(await (await page.request.get('http://localhost:3100/api/me/goals')).json()).goals;assert.equal(saved.length,1);assert.equal(saved[0].discipline,'poetry');assert.equal(saved[0].targets[0].id,orgs[0].id);
 await page.getByRole('button',{name:'Check in',exact:true}).click();await page.getByLabel('Next step',{exact:true}).fill('Read the latest issue');await page.getByRole('button',{name:'Save check-in',exact:true}).click();await page.getByText('Read the latest issue',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Pause',exact:true}).click();await page.getByRole('button',{name:'Resume',exact:true}).waitFor();assert(await page.getByRole('button',{name:'Check in',exact:true}).isDisabled());await page.getByRole('button',{name:'Resume',exact:true}).click();
 await page.goto('http://localhost:3100/goals');await page.getByRole('heading',{name:'Submit 6 poetry applications',exact:true}).waitFor();await page.screenshot({path:'apps/web/outputs/goals-connected-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 let axe=await new AxeBuilder({page}).analyze();assert.deepEqual(axe.violations.filter(v=>['serious','critical'].includes(v.impact??'')),[]);
 await page.goto('http://localhost:3100/goals');await page.getByRole('heading',{name:'Submit 6 poetry applications',exact:true}).waitFor();await page.screenshot({path:'apps/web/outputs/goals-connected-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'New goal',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:/Choose organizations/}).click();await page.getByRole('textbox',{name:'Search organizations'}).waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await expect(page.getByRole('dialog')).toHaveCSS('opacity','1');await expect(page.getByRole('dialog').getByText('Searching…',{exact:true})).toBeHidden();await page.screenshot({path:'apps/web/outputs/goals-organization-picker.png',fullPage:false,animations:'disabled'});await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:/Choose organizations/})).toBeFocused();
 await page.setViewportSize({width:640,height:450});await page.evaluate(()=>document.documentElement.style.fontSize='200%');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 console.log('PASS: discipline wizard, separate real target pickers, Back preservation, failed-save retry, persisted discipline/targets, idempotency, check-in, pause/resume, mobile and axe.');
} finally {await browser.close();await pool.query('delete from radar_accounts where id=$1',[id]);await pool.end();}
