import { NextResponse } from 'next/server';
import { EmailForwardingError } from '@missa/radar-engine';
import { getSessionAccount } from '@/lib/auth';
import { getEngine, persistRadar } from '@/lib/engine';
import { consumeEmailLifecycleLimit } from '@/lib/email-rate-limit';
function json(value: unknown, status = 200) { return NextResponse.json(value, { status, headers: { 'Cache-Control': 'private, no-store' } }); }
function message(error: unknown): { status: 400 | 401 | 404 | 500; error: string } { if (error instanceof EmailForwardingError) return { status: error.code === 'not-found' ? 404 : error.code === 'forbidden' ? 401 : 400, error: error.message }; return { status: 500, error: 'We could not update Email Sync. Please try again.' }; }
export async function GET(request: Request) { const session = await getSessionAccount(request.headers.get('cookie')); if (!session) return json({ error: 'Not authenticated' }, 401); if (!session.account.userId) return json({ error: 'Profile not found' }, 404); const engine = await getEngine(); return json(engine.forwardingAddress(session.account.userId)); }
export async function POST(request: Request) { const session = await getSessionAccount(request.headers.get('cookie')); if (!session) return json({ error: 'Not authenticated' }, 401); if (!session.account.userId) return json({ error: 'Profile not found' }, 404); const retryAfter = consumeEmailLifecycleLimit(session.account.id); if (retryAfter !== undefined) return NextResponse.json({ error: 'Too many Email Sync changes. Try again later.' }, { status: 429, headers: { 'Cache-Control': 'private, no-store', 'Retry-After': String(retryAfter) } }); const engine = await getEngine(); try { const result = engine.createForwardingAddress(session.account.userId); if (result.created) { engine.recordAudit(session.account.id, 'email.forwarding_enabled', 'forwarding_address', result.view.addressId ?? 'unknown', JSON.stringify({ userId: session.account.userId, sourceMode: 'forwarding-address' })); await persistRadar(); } return json(result, result.created ? 201 : 200); } catch (error) { const result = message(error); return json({ error: result.error }, result.status); } }
export async function DELETE(request: Request) { const session = await getSessionAccount(request.headers.get('cookie')); if (!session) return json({ error: 'Not authenticated' }, 401); if (!session.account.userId) return json({ error: 'Profile not found' }, 404); const body = await request.json().catch(() => ({})); if (body?.confirmation !== true) return json({ error: 'Confirm deletion to revoke the forwarding address.' }, 400); const engine = await getEngine(); try { const result = engine.revokeForwardingAddress(session.account.userId, body?.deletePendingCandidates === true); engine.recordAudit(session.account.id, 'email.forwarding_revoked', 'forwarding_address', result.view.addressId ?? 'unknown', JSON.stringify({ userId: session.account.userId, sourceMode: 'forwarding-address', deletedPendingCandidates: result.deletedCandidates })); await persistRadar(); return json({ ...result, address: undefined }); } catch (error) { const result = message(error); return json({ error: result.error }, result.status); } }
