import type { RegistryVertical } from './types.js';

/** Canonical vertical taxonomy for the opportunity source registry. */
export const REGISTRY_VERTICALS: RegistryVertical[] = [
  // ── Literary ──────────────────────────────────────────────────────────────
  {
    id: 'literary-fiction',
    label: 'Literary Fiction',
    group: 'literary',
    opportunityTypes: ['magazine', 'contest', 'open-call'],
    disciplines: ['fiction', 'short-fiction'],
    description: 'Literary magazines, journals, and fiction contests accepting short stories and novels.',
  },
  {
    id: 'poetry',
    label: 'Poetry',
    group: 'literary',
    opportunityTypes: ['magazine', 'contest', 'award'],
    disciplines: ['poetry'],
    description: 'Poetry magazines, chapbook prizes, and poem contests.',
  },
  {
    id: 'creative-nonfiction',
    label: 'Creative Nonfiction & Essays',
    group: 'literary',
    opportunityTypes: ['magazine', 'contest', 'grant'],
    disciplines: ['nonfiction', 'essay', 'memoir'],
    description: 'CNF magazines, essay prizes, and narrative journalism open calls.',
  },
  {
    id: 'flash-hybrid',
    label: 'Flash, Hybrid & Experimental Writing',
    group: 'literary',
    opportunityTypes: ['magazine', 'contest'],
    disciplines: ['flash-fiction', 'hybrid', 'experimental'],
    description: 'Flash fiction, prose poetry, hybrid forms, and experimental lit mags.',
  },
  {
    id: 'novel-book',
    label: 'Novel & Book Prizes',
    group: 'literary',
    opportunityTypes: ['contest', 'award', 'fellowship'],
    disciplines: ['novel', 'debut', 'manuscript'],
    description: 'First-novel awards, manuscript contests, and book publication prizes.',
  },
  {
    id: 'ya-children',
    label: 'YA, Middle Grade & Children\'s',
    group: 'literary',
    opportunityTypes: ['magazine', 'contest', 'grant'],
    disciplines: ['ya', 'middle-grade', 'children', 'picture-book'],
    description: 'Young reader markets, kidlit contests, and children\'s writing grants.',
  },
  {
    id: 'translation',
    label: 'Translation & Bilingual',
    group: 'literary',
    opportunityTypes: ['magazine', 'grant', 'fellowship'],
    disciplines: ['translation', 'bilingual'],
    description: 'Translation prizes, bilingual journals, and translator fellowships.',
  },
  {
    id: 'writing-residency',
    label: 'Writing Residencies',
    group: 'literary',
    opportunityTypes: ['residency', 'fellowship'],
    disciplines: ['writing', 'literature'],
    description: 'Residencies primarily for writers, poets, and literary translators.',
  },
  {
    id: 'science-nature-writing',
    label: 'Science & Nature Writing',
    group: 'literary',
    opportunityTypes: ['magazine', 'grant', 'fellowship'],
    disciplines: ['science-writing', 'nature-writing', 'environmental'],
    description: 'Science journalism, nature writing grants, and environmental lit markets.',
  },
  {
    id: 'literary-festivals',
    label: 'Literary Festivals & Readings',
    group: 'literary',
    opportunityTypes: ['festival', 'open-call', 'pitch'],
    disciplines: ['reading', 'panel', 'workshop'],
    description: 'Festival programming open calls, reading series, and writer appearances.',
  },

  // ── Visual arts ───────────────────────────────────────────────────────────
  {
    id: 'visual-residency',
    label: 'Visual Arts Residencies',
    group: 'visual-arts',
    opportunityTypes: ['residency', 'fellowship'],
    disciplines: ['visual-arts', 'interdisciplinary'],
    description: 'Studio residencies for painters, sculptors, and mixed-media artists.',
  },
  {
    id: 'visual-open-call',
    label: 'Visual Arts Open Calls & Exhibitions',
    group: 'visual-arts',
    opportunityTypes: ['open-call', 'contest', 'award'],
    disciplines: ['painting', 'sculpture', 'mixed-media', 'installation'],
    description: 'Gallery open calls, group shows, and visual art prizes.',
  },
  {
    id: 'photography',
    label: 'Photography',
    group: 'visual-arts',
    opportunityTypes: ['contest', 'open-call', 'magazine', 'grant'],
    disciplines: ['photography', 'photojournalism'],
    description: 'Photo contests, lens-based residencies, and photography grants.',
  },
  {
    id: 'public-art',
    label: 'Public Art & Commissions',
    group: 'visual-arts',
    opportunityTypes: ['rfp', 'open-call', 'grant'],
    disciplines: ['public-art', 'mural', 'sculpture'],
    description: 'Percent-for-art programs, mural RFPs, and civic commissions.',
  },
  {
    id: 'printmaking-ceramics',
    label: 'Printmaking, Ceramics & Craft Media',
    group: 'visual-arts',
    opportunityTypes: ['residency', 'open-call', 'contest'],
    disciplines: ['printmaking', 'ceramics', 'fiber', 'glass'],
    description: 'Medium-specific residencies and craft-art open calls.',
  },
  {
    id: 'curatorial',
    label: 'Curatorial Open Calls',
    group: 'visual-arts',
    opportunityTypes: ['open-call', 'fellowship', 'grant'],
    disciplines: ['curating', 'criticism'],
    description: 'Curatorial fellowships, exhibition proposals, and arts writing.',
  },

  // ── Performing arts ───────────────────────────────────────────────────────
  {
    id: 'theater-playwriting',
    label: 'Theater & Playwriting',
    group: 'performing-arts',
    opportunityTypes: ['contest', 'festival', 'residency', 'open-call'],
    disciplines: ['playwriting', 'theater', 'dramaturgy'],
    description: 'Play contests, theater festivals, and dramatist residencies.',
  },
  {
    id: 'dance-choreography',
    label: 'Dance & Choreography',
    group: 'performing-arts',
    opportunityTypes: ['residency', 'grant', 'festival'],
    disciplines: ['dance', 'choreography'],
    description: 'Choreographic fellowships, dance residencies, and performance grants.',
  },
  {
    id: 'performance-art',
    label: 'Performance & Live Art',
    group: 'performing-arts',
    opportunityTypes: ['open-call', 'festival', 'residency'],
    disciplines: ['performance', 'live-art', 'interdisciplinary'],
    description: 'Live art festivals, performance residencies, and interdisciplinary calls.',
  },

  // ── Film & media ──────────────────────────────────────────────────────────
  {
    id: 'film-festival',
    label: 'Film Festivals',
    group: 'film-media',
    opportunityTypes: ['festival', 'contest'],
    disciplines: ['film', 'short-film', 'documentary'],
    description: 'Film festival entry pages and short-film competitions.',
  },
  {
    id: 'screenwriting',
    label: 'Screenwriting & TV Writing',
    group: 'film-media',
    opportunityTypes: ['contest', 'fellowship', 'pitch'],
    disciplines: ['screenwriting', 'television'],
    description: 'Screenplay contests, TV writing fellowships, and pitch labs.',
  },
  {
    id: 'documentary',
    label: 'Documentary & Nonfiction Film',
    group: 'film-media',
    opportunityTypes: ['grant', 'festival', 'fellowship'],
    disciplines: ['documentary'],
    description: 'Documentary funds, doc festivals, and filmmaker grants.',
  },
  {
    id: 'animation-new-media',
    label: 'Animation & New Media',
    group: 'film-media',
    opportunityTypes: ['festival', 'grant', 'residency'],
    disciplines: ['animation', 'new-media', 'digital-art'],
    description: 'Animation festivals, new-media grants, and digital art residencies.',
  },

  // ── Music ───────────────────────────────────────────────────────────────────
  {
    id: 'music-composition',
    label: 'Music Composition & Sound',
    group: 'music',
    opportunityTypes: ['grant', 'residency', 'fellowship', 'contest'],
    disciplines: ['composition', 'sound-art', 'electroacoustic'],
    description: 'Composer grants, sound-art residencies, and music prizes.',
  },

  // ── Grants & funding ────────────────────────────────────────────────────────
  {
    id: 'grants-us-national',
    label: 'US National Arts Grants',
    group: 'grants-funding',
    opportunityTypes: ['grant', 'fellowship'],
    disciplines: ['all-disciplines'],
    description: 'Federal and national US arts funders (NEA, foundations).',
  },
  {
    id: 'grants-us-state',
    label: 'US State & Regional Arts Grants',
    group: 'grants-funding',
    opportunityTypes: ['grant', 'fellowship'],
    disciplines: ['all-disciplines'],
    description: 'State arts councils and regional arts funders across the US.',
  },
  {
    id: 'grants-international',
    label: 'International Arts Grants & Mobility',
    group: 'grants-funding',
    opportunityTypes: ['grant', 'fellowship', 'scholarship'],
    disciplines: ['all-disciplines'],
    description: 'EU mobility funds, national arts councils abroad, and global foundations.',
  },
  {
    id: 'fellowships',
    label: 'Fellowships & Professional Development',
    group: 'grants-funding',
    opportunityTypes: ['fellowship', 'residency'],
    disciplines: ['all-disciplines'],
    description: 'Career fellowships, emerging-artist programs, and professional development.',
  },
  {
    id: 'scholarships',
    label: 'Scholarships & Student Awards',
    group: 'grants-funding',
    opportunityTypes: ['scholarship', 'award'],
    disciplines: ['all-disciplines'],
    description: 'MFA scholarships, student prizes, and academic arts funding.',
  },

  // ── Awards & festivals ────────────────────────────────────────────────────
  {
    id: 'awards-prizes',
    label: 'Arts Awards & Prizes',
    group: 'awards-festivals',
    opportunityTypes: ['award', 'contest'],
    disciplines: ['all-disciplines'],
    description: 'Major arts prizes and discipline-spanning awards.',
  },
  {
    id: 'arts-festivals',
    label: 'Multidisciplinary Arts Festivals',
    group: 'awards-festivals',
    opportunityTypes: ['festival', 'open-call'],
    disciplines: ['interdisciplinary'],
    description: 'Cross-disciplinary festivals and open-call programming.',
  },

  // ── Academic & professional ─────────────────────────────────────────────────
  {
    id: 'conference-cfp',
    label: 'Conference & Symposium CFPs',
    group: 'academic-professional',
    opportunityTypes: ['conference', 'rfp'],
    disciplines: ['academic', 'research'],
    description: 'Call-for-papers, abstracts, and symposium proposals.',
  },
  {
    id: 'museum-gallery',
    label: 'Museum & Institutional Open Calls',
    group: 'academic-professional',
    opportunityTypes: ['open-call', 'rfp', 'fellowship'],
    disciplines: ['visual-arts', 'curating'],
    description: 'Museum exhibitions, institutional commissions, and museum fellowships.',
  },

  // ── Craft & design ──────────────────────────────────────────────────────────
  {
    id: 'comics-illustration',
    label: 'Comics, Illustration & Graphic Narrative',
    group: 'craft-design',
    opportunityTypes: ['magazine', 'contest', 'grant', 'open-call'],
    disciplines: ['comics', 'illustration', 'graphic-novel'],
    description: 'Comics anthologies, illustration prizes, and graphic narrative grants.',
  },
  {
    id: 'craft-design',
    label: 'Craft, Design & Applied Arts',
    group: 'craft-design',
    opportunityTypes: ['grant', 'open-call', 'residency'],
    disciplines: ['craft', 'design', 'furniture', 'textile'],
    description: 'Craft council grants, design residencies, and applied arts open calls.',
  },
  {
    id: 'architecture-built',
    label: 'Architecture & Built Environment',
    group: 'craft-design',
    opportunityTypes: ['rfp', 'contest', 'fellowship'],
    disciplines: ['architecture', 'urbanism'],
    description: 'Architecture competitions, design-build RFPs, and spatial art calls.',
  },

  // ── Identity & community-focused ────────────────────────────────────────────
  {
    id: 'bipoc-focused',
    label: 'BIPOC-Focused Opportunities',
    group: 'literary',
    opportunityTypes: ['grant', 'residency', 'magazine', 'fellowship'],
    disciplines: ['bipoc'],
    description: 'Opportunities explicitly serving Black, Indigenous, and artists of color.',
  },
  {
    id: 'lgbtq-focused',
    label: 'LGBTQ+ Focused Opportunities',
    group: 'literary',
    opportunityTypes: ['magazine', 'grant', 'residency'],
    disciplines: ['lgbtq'],
    description: 'Queer-focused journals, grants, and residency programs.',
  },
  {
    id: 'disability-arts',
    label: 'Disability Arts & Accessibility',
    group: 'literary',
    opportunityTypes: ['grant', 'residency', 'open-call'],
    disciplines: ['disability-arts'],
    description: 'Disability-led arts grants, accessible residencies, and Deaf arts programs.',
  },
  {
    id: 'indigenous-arts',
    label: 'Indigenous Arts & Cultural Programs',
    group: 'literary',
    opportunityTypes: ['grant', 'fellowship', 'residency'],
    disciplines: ['indigenous'],
    description: 'Indigenous arts councils, cultural fellowships, and tribal arts funding.',
  },

  // ── Platforms (tier 1–2) ────────────────────────────────────────────────────
  {
    id: 'platform-submittable',
    label: 'Submittable Discover',
    group: 'platforms',
    opportunityTypes: ['open-call', 'grant', 'contest', 'magazine'],
    disciplines: ['all-disciplines'],
    description: 'Submittable-hosted public opportunity marketplace.',
  },
  {
    id: 'platform-cafe',
    label: 'CaFÉ / CallForEntry',
    group: 'platforms',
    opportunityTypes: ['open-call', 'contest', 'award'],
    disciplines: ['visual-arts', 'public-art'],
    description: 'CallForEntry.org public calls for visual and public artists.',
  },
  {
    id: 'platform-filmfreeway',
    label: 'FilmFreeway',
    group: 'platforms',
    opportunityTypes: ['festival', 'contest'],
    disciplines: ['film'],
    description: 'Film festival discovery and submission platform.',
  },
  {
    id: 'platform-duotrope',
    label: 'Duotrope',
    group: 'platforms',
    opportunityTypes: ['magazine', 'contest'],
    disciplines: ['fiction', 'poetry', 'nonfiction'],
    description: 'Writer market database — discovery seed; crawl outbound guideline links.',
  },
  {
    id: 'platform-chill-subs',
    label: 'Chill Subs',
    group: 'platforms',
    opportunityTypes: ['magazine', 'contest'],
    disciplines: ['fiction', 'poetry', 'nonfiction'],
    description: 'Literary opportunity discovery — seed for outbound guideline crawling.',
  },
  {
    id: 'platform-resartis',
    label: 'Res Artis',
    group: 'platforms',
    opportunityTypes: ['residency', 'open-call'],
    disciplines: ['visual-arts', 'interdisciplinary'],
    description: 'Global residency network open-call directory.',
  },
  {
    id: 'platform-transartists',
    label: 'TransArtists',
    group: 'platforms',
    opportunityTypes: ['residency'],
    disciplines: ['visual-arts', 'interdisciplinary'],
    description: 'European residency aggregator — discovery seed.',
  },
  {
    id: 'platform-poets-writers',
    label: 'Poets & Writers',
    group: 'platforms',
    opportunityTypes: ['contest', 'grant', 'magazine'],
    disciplines: ['fiction', 'poetry', 'nonfiction'],
    description: 'Editorially vetted writing contests and literary magazine database.',
  },
  {
    id: 'platform-opportunity-feeds',
    label: 'Opportunity Feeds & Newsletters',
    group: 'platforms',
    opportunityTypes: ['open-call', 'grant'],
    disciplines: ['all-disciplines'],
    description: 'RSS feeds, newsletters, and syndicated opportunity listings.',
  },
];
