import { AgentGraphTable, DataAreaHeader, LifecycleTable, MaturityBadge, MetricCard, SectionHeading, WarningList, WorkerLaneTable, WorkerStatus } from '@/components/platform-admin';
import type { AdminArea } from '@/lib/platformAdmin';
import type { PlatformAdminGovernanceData } from '@/lib/platformAdminContinuation';

function value(value: number | null): string {
  return value === null ? '—' : String(value);
}

export default function PlatformAdminGovernance({ area }: { area: AdminArea<PlatformAdminGovernanceData> }) {
  const data = area.data;
  return <div className="space-y-8">
    <DataAreaHeader area={area} title="Governance" description="A read-only control surface for support readiness, billing/provider state, policy maturity, and the bounded agent loop. Mutations remain on their owning contracts." />
    <WarningList warnings={area.warnings} />
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5" aria-label="Governance summary"><MetricCard label="Needs attention" value={data.support.highAttention} detail="High-severity Operations rows" href="/admin/operations?severity=high" /><MetricCard label="Verification" value={data.support.verificationOpen} detail="Source checks awaiting review" href="/admin/radar?focus=verification" /><MetricCard label="Claims" value={data.support.claimsPending} detail="Organization claims pending" href="/admin/radar?focus=claims" /><MetricCard label="Email review" value={data.support.emailReviewPending} detail="Compatibility candidates awaiting review" href="/admin/messaging" /><MetricCard label="Audit entries" value={data.support.auditEntries} detail="Recent compatibility/platform entries" href="/admin/audit" /></section>
    <section><SectionHeading eyebrow="Billing and provider state" title="Observed commercial readiness" description="Plan/status fields are compatibility observations. No invoices, refunds, revenue facts, or provider mutations are exposed here." /><div className="mt-4 grid gap-5 lg:grid-cols-2"><div className="rounded-xl border border-border bg-white p-5"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-medium text-foreground">Billing status</h3><span className={`text-xs font-medium ${data.billing.stripeConfigured ? 'text-green-700' : 'text-amber-700'}`}>{data.billing.stripeConfigured ? 'Stripe config present' : 'Stripe config missing'}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><p className="text-xs text-muted-foreground">Past due</p><p className="mt-1 font-mono text-2xl text-foreground">{data.billing.pastDue}</p></div><div><p className="text-xs text-muted-foreground">Canceled</p><p className="mt-1 font-mono text-2xl text-foreground">{data.billing.canceled}</p></div><div><p className="text-xs text-muted-foreground">Connect pending</p><p className="mt-1 font-mono text-2xl text-foreground">{data.billing.connectPending}</p></div></div></div><div className="grid gap-5 sm:grid-cols-2"><div className="rounded-xl border border-border bg-white p-5"><h3 className="text-sm font-medium text-foreground">By tier</h3><div className="mt-3"><LifecycleTable label="Billing tiers" counts={data.billing.byTier} /></div></div><div className="rounded-xl border border-border bg-white p-5"><h3 className="text-sm font-medium text-foreground">By status</h3><div className="mt-3"><LifecycleTable label="Billing statuses" counts={data.billing.byStatus} /></div></div></div></div></section>
    <section><SectionHeading eyebrow="Policy" title="Taxonomy governance readiness" description="The canonical taxonomy graph fails closed when its additive schema is absent. Compatibility labels remain distinct from governed policy state." /><div className="mt-4 rounded-xl border border-border bg-white p-5"><div className="flex flex-wrap items-center gap-3"><MaturityBadge maturity={data.policy.maturity} /><span className="text-sm text-muted-foreground">{data.policy.available ? data.policy.scheme ?? 'Canonical scheme observed' : 'Canonical taxonomy dashboard unavailable'}</span></div><dl className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs text-muted-foreground">Open proposals</dt><dd className="mt-1 font-mono text-xl text-foreground">{value(data.policy.openProposals)}</dd></div><div><dt className="text-xs text-muted-foreground">Coverage gaps</dt><dd className="mt-1 font-mono text-xl text-foreground">{value(data.policy.coverageGaps)}</dd></div><div><dt className="text-xs text-muted-foreground">Discovery failures</dt><dd className="mt-1 font-mono text-xl text-foreground">{value(data.policy.discoveryFailures)}</dd></div><div><dt className="text-xs text-muted-foreground">Candidates to review</dt><dd className="mt-1 font-mono text-xl text-foreground">{value(data.policy.candidatesAwaitingReview)}</dd></div></dl><p className="mt-4 text-xs leading-5 text-muted-foreground">Open the dedicated Policy → Taxonomy surface for the existing read dashboard. Approval, rejection, and apply actions still need governed contracts.</p></div></section>
    <section><SectionHeading eyebrow="Agent loop" title="Lanes and handoffs" description="The graph and durable records show ownership and state; the worker still owns execution and publication remains fail-closed." /><div className="mt-4 space-y-5"><WorkerStatus worker={{ ...({ status: data.agentLoop.workerStatus } as Parameters<typeof WorkerStatus>[0]['worker']), caveat: 'Governance summarizes the same worker signal shown in Operations.', running: data.agentLoop.lanes.filter((lane) => lane.status === 'running').length, failed: data.agentLoop.lanes.filter((lane) => lane.status === 'failed').length, completed: data.agentLoop.lanes.filter((lane) => lane.status === 'stopped').length, lanes: data.agentLoop.lanes }} /><WorkerLaneTable lanes={data.agentLoop.lanes} /><AgentGraphTable graph={data.agentLoop.graph} /></div></section>
    <section><SectionHeading eyebrow="Durable state" title="Queue availability" description="A missing target table is shown as unavailable, not as an empty healthy queue." /><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.agentLoop.durableQueues.map((queue) => <div key={queue.label} className="rounded-xl border border-border bg-white p-4"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-medium text-foreground">{queue.label}</h3><MaturityBadge maturity={queue.maturity} /></div><div className="mt-3"><LifecycleTable label={queue.label} counts={queue.counts} /></div></div>)}</div></section>
    <section className="border-t border-border pt-6"><h2 className="text-lg font-semibold tracking-tight text-foreground">What is intentionally not a control</h2><ul className="mt-3 grid gap-2 text-sm text-muted-foreground sm:grid-cols-2">{data.planned.map((item) => <li key={item} className="border border-border bg-white px-3 py-2">{item}</li>)}</ul></section>
  </div>;
}
