import type { AdminArea } from "@/lib/platformAdmin";
import type { PlatformAdminAnalyticsData } from "@/lib/platformAdminViews";
import { MaturityBadge, WarningList } from "./platform-admin";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "./ui/table";

function SectionHeading({ title, detail }: { title: string; detail: string }) {
  return <div><h2 className="text-xl font-semibold tracking-tight text-foreground">{title}</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></div>;
}

function MetricCard({ label, value, detail }: { label: string; value: number | string; detail: string }) {
  return <div className="border border-border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-mono text-2xl tabular-nums text-foreground">{value}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></div>;
}

export default function PlatformAdminAnalytics({ area }: { area: AdminArea<PlatformAdminAnalyticsData> }) {
  const { data } = area;
  return <div className="min-w-0 max-w-full space-y-8">
    <div><p className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">Platform Admin · Product</p><h1 className="mt-2 font-heading text-4xl font-medium tracking-tight text-foreground">Analytics</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Transparent product and operational summaries from the current runtime records. Every number stays attached to its grain and calculation.</p><div className="mt-3 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-muted-foreground"><MaturityBadge maturity={area.provenance.maturity} /><span>Data source: {area.provenance.source}</span><span>Freshness: {area.provenance.freshness}</span></div></div>
    <WarningList warnings={area.warnings} />

    <section aria-label="Current metrics"><SectionHeading title="Current metrics" detail="Derived on read; no event warehouse is implied." /><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.metrics.map((metric) => <div key={metric.label} className="border border-border bg-card p-4"><p className="text-xs text-muted-foreground">{metric.label}</p><p className="mt-1 font-mono text-2xl tabular-nums text-foreground">{metric.value}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{metric.detail}</p><dl className="mt-3 space-y-1 border-t border-border pt-3 text-[11px]"><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Grain</dt><dd className="font-mono text-foreground">{metric.grain}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Source</dt><dd className="max-w-[65%] truncate text-end text-foreground">{metric.source}</dd></div></dl></div>)}</div></section>

    <section className="grid min-w-0 gap-6 [&>div]:min-w-0 lg:grid-cols-[1.4fr_1fr]" aria-label="Workflow records and source quality">
      <div><SectionHeading title="Workflow records" detail="Counts remain at their native grain; the table is not a conversion claim between unlike records." /><div className="mt-4 border border-border bg-card"><Table><TableHeader><TableRow><TableHead>Stage</TableHead><TableHead className="text-end">Count</TableHead><TableHead>Grain</TableHead><TableHead>Calculation</TableHead></TableRow></TableHeader><TableBody>{data.funnel.map((stage) => <TableRow key={stage.label}><TableCell className="font-medium">{stage.label}</TableCell><TableCell className="text-end font-mono tabular-nums">{stage.value}</TableCell><TableCell className="text-xs text-muted-foreground">{stage.grain}</TableCell><TableCell className="text-xs text-muted-foreground">{stage.calculation}</TableCell></TableRow>)}</TableBody></Table></div></div>
      <div><SectionHeading title="Source quality" detail="Freshness and review signals remain separate from worker liveness." /><div className="mt-4 divide-y divide-border border border-border bg-card">{data.quality.map((item) => <div key={item.label} className="flex items-center justify-between gap-3 px-4 py-3"><div><p className="text-sm font-medium text-foreground">{item.label}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{item.detail}</p></div><span className="font-mono text-lg tabular-nums text-foreground">{item.value}</span></div>)}</div></div>
    </section>

    <section aria-label="Creator journey"><SectionHeading title="Creator journey" detail="Unique accounts or anonymous sessions completing each step in order. Apply means an official destination opened; Confirm requires a user record or hosted receipt." /><div className="mt-4 border border-border bg-card">{data.durable.journeyFunnel.length ? <Table><TableHeader><TableRow><TableHead>Stage</TableHead><TableHead className="text-end">People or sessions</TableHead><TableHead className="text-end">From prior stage</TableHead></TableRow></TableHeader><TableBody>{data.durable.journeyFunnel.map((stage) => <TableRow key={stage.key}><TableCell className="font-medium">{stage.label}</TableCell><TableCell className="text-end font-mono tabular-nums">{stage.actors}</TableCell><TableCell className="text-end font-mono tabular-nums text-muted-foreground">{stage.conversionFromPrevious === null ? "—" : `${stage.conversionFromPrevious}%`}</TableCell></TableRow>)}</TableBody></Table> : <p className="px-4 py-10 text-center text-xs text-muted-foreground">No complete journey events are available for this window.</p>}</div></section>

    <section className="grid gap-6 lg:grid-cols-2" aria-label="Behavioral segments and retention">
      <div><SectionHeading title="Behavioral segments" detail="Account-level cohorts derived from observed behavior, not inferred identity or eligibility." /><div className="mt-4 divide-y divide-border border border-border bg-card">{data.durable.segments.length ? data.durable.segments.map((segment) => <div key={segment.key} className="flex items-start justify-between gap-4 px-4 py-3"><div><p className="text-sm font-medium text-foreground">{segment.label}</p><p className="mt-1 text-[11px] leading-5 text-muted-foreground">{segment.definition}</p></div><span className="font-mono text-lg tabular-nums text-foreground">{segment.accounts}</span></div>) : <p className="px-4 py-10 text-center text-xs text-muted-foreground">No authenticated behavior is available for segmentation.</p>}</div></div>
      <div><SectionHeading title="Week-one retention" detail="Accounts returning 7–13 days after their first observed authenticated event. Incomplete cohorts are excluded." /><div className="mt-4 border border-border bg-card">{data.durable.retention.length ? <Table><TableHeader><TableRow><TableHead>Cohort week</TableHead><TableHead className="text-end">Accounts</TableHead><TableHead className="text-end">Returned</TableHead><TableHead className="text-end">Rate</TableHead></TableRow></TableHeader><TableBody>{data.durable.retention.map((cohort) => <TableRow key={cohort.cohortWeek}><TableCell className="font-mono text-xs">{cohort.cohortWeek}</TableCell><TableCell className="text-end font-mono tabular-nums">{cohort.accounts}</TableCell><TableCell className="text-end font-mono tabular-nums">{cohort.returnedWeekOne}</TableCell><TableCell className="text-end font-mono tabular-nums">{cohort.rate === null ? "—" : `${cohort.rate}%`}</TableCell></TableRow>)}</TableBody></Table> : <p className="px-4 py-10 text-center text-xs text-muted-foreground">No mature retention cohorts are available yet.</p>}</div></div>
    </section>

    <section aria-label="Acquisition segments"><SectionHeading title="Acquisition segments" detail="Bounded campaign, referrer, and device values attached to observed events; raw URLs and personal identifiers are excluded." /><div className="mt-4 border border-border bg-card">{data.durable.dimensions.length ? <Table><TableHeader><TableRow><TableHead>Dimension</TableHead><TableHead>Value</TableHead><TableHead className="text-end">People or sessions</TableHead><TableHead className="text-end">Events</TableHead></TableRow></TableHeader><TableBody>{data.durable.dimensions.map((row) => <TableRow key={`${row.dimension}:${row.value}`}><TableCell className="font-medium">{row.dimension}</TableCell><TableCell className="max-w-72 truncate font-mono text-xs">{row.value}</TableCell><TableCell className="text-end font-mono tabular-nums">{row.actors}</TableCell><TableCell className="text-end font-mono tabular-nums text-muted-foreground">{row.events}</TableCell></TableRow>)}</TableBody></Table> : <p className="px-4 py-10 text-center text-xs text-muted-foreground">No bounded acquisition properties are available for this window.</p>}</div></section>

    <section aria-label="Analytics quality"><SectionHeading title="Analytics quality" detail="Unregistered or authority-mismatched events need investigation before reports are trusted." /><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Missing actor" value={data.durable.quality.missingActor} detail="No account or session identifier" /><MetricCard label="Anonymous events" value={data.durable.quality.anonymousEvents} detail="Session-scoped; excluded from retention" /><MetricCard label="Unregistered events" value={data.durable.quality.unregisteredEvents} detail="Absent from the tracking plan" /><MetricCard label="Authority mismatches" value={data.durable.quality.authorityMismatches} detail="Server events received from the browser" /></div></section>

    <section aria-label="Observed monthly flow"><SectionHeading title="Observed monthly flow" detail="Only months present in current timestamps are shown; an empty month is not backfilled." /><div className="mt-4 border border-border bg-card"><Table><TableHeader><TableRow><TableHead>Month UTC</TableHead><TableHead className="text-end">Submissions</TableHead><TableHead className="text-end">Decisions</TableHead><TableHead className="text-end">Accepted Works</TableHead><TableHead className="text-end">Completed delivery</TableHead></TableRow></TableHeader><TableBody>{data.trends.map((trend) => <TableRow key={trend.month}><TableCell className="font-mono text-xs">{trend.month}</TableCell><TableCell className="text-end font-mono tabular-nums">{trend.submissions}</TableCell><TableCell className="text-end font-mono tabular-nums">{trend.decisions}</TableCell><TableCell className="text-end font-mono tabular-nums">{trend.acceptedWorks}</TableCell><TableCell className="text-end font-mono tabular-nums">{trend.completedDelivery}</TableCell></TableRow>)}</TableBody></Table>{data.trends.length === 0 ? <p className="px-4 py-10 text-center text-xs text-muted-foreground">No timestamped monthly records are available.</p> : null}</div></section>

    <section aria-label="Durable product events"><div className="flex flex-wrap items-end justify-between gap-3"><SectionHeading title="Durable product events" detail="First-party event ledger, separate from workflow counts and optional external analytics." /><span className="text-xs text-muted-foreground">{data.durable.source}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><MetricCard label="Events observed" value={data.durable.summary.events} detail="Selected retention window" /><MetricCard label="Last 24 hours" value={data.durable.summary.last24h} detail="Recorded events" /><MetricCard label="Last 7 days" value={data.durable.summary.last7d} detail="Recorded events" /><MetricCard label="Unique accounts" value={data.durable.summary.uniqueAccounts} detail="Explicit account IDs only" /><MetricCard label="Unique organizations" value={data.durable.summary.uniqueOrganizations} detail="Explicit organization IDs only" /></div><div className="mt-4 grid gap-6 lg:grid-cols-[1fr_1.2fr]"><div className="border border-border bg-card"><div className="border-b border-border px-4 py-3 text-xs font-medium text-foreground">Events by name</div>{data.durable.byEvent.length === 0 ? <p className="px-4 py-8 text-center text-xs text-muted-foreground">No durable product events recorded.</p> : <div className="divide-y divide-border">{data.durable.byEvent.slice(0, 12).map((item) => <div key={item.eventName} className="flex items-center justify-between gap-3 px-4 py-3"><span className="truncate font-mono text-xs text-foreground">{item.eventName}</span><span className="font-mono text-sm tabular-nums text-muted-foreground">{item.count}</span></div>)}</div>}</div><div className="border border-border bg-card"><Table><TableHeader><TableRow><TableHead>Day UTC</TableHead><TableHead className="text-end">Events</TableHead></TableRow></TableHeader><TableBody>{data.durable.daily.map((item) => <TableRow key={item.day}><TableCell className="font-mono text-xs">{item.day}</TableCell><TableCell className="text-end font-mono tabular-nums">{item.count}</TableCell></TableRow>)}</TableBody></Table>{data.durable.daily.length === 0 ? <p className="px-4 py-8 text-center text-xs text-muted-foreground">No daily event history is available.</p> : null}</div></div></section>

    <section className="border border-dashed border-border bg-card p-4" aria-label="Metric boundaries"><h2 className="text-sm font-semibold text-foreground">Metric boundaries</h2><ul className="mt-3 grid gap-2 text-xs leading-5 text-muted-foreground sm:grid-cols-2">{data.definitions.map((definition) => <li key={definition} className="border-s-2 border-border ps-3">{definition}</li>)}</ul></section>
  </div>;
}
