import Link from 'next/link';
import { ArrowRight, CircleAlert, Clock3, Database, RefreshCw, ShieldAlert } from 'lucide-react';
import type { PlatformAdminOverview, PlatformAdminQueueRow } from '@/lib/platformAdmin';
import { MaturityBadge, WarningList } from './platform-admin';

function attentionRows(rows: PlatformAdminQueueRow[]) {
  const severity = { high: 0, medium: 1, low: 2 } as const;
  return rows
    .filter((row) => row.severity !== 'low')
    .sort((a, b) => severity[a.severity] - severity[b.severity] || (a.ageAt ?? '').localeCompare(b.ageAt ?? ''))
    .slice(0, 8);
}

function attentionColor(row: PlatformAdminQueueRow) {
  return row.severity === 'high' ? 'text-red-700' : row.severity === 'medium' ? 'text-amber-700' : 'text-muted-foreground';
}

export default function PlatformAdminControlRoom({ overview }: { overview: PlatformAdminOverview }) {
  const operations = overview.operations.data;
  const sourceHealth = overview.radar.data.sourceHealth.summary;
  const attention = attentionRows(operations.queue.rows);
  const workerLabel = operations.worker.status === 'unknown' ? 'Not observed' : operations.worker.status.replaceAll('-', ' ');
  const stateItems = [
    { label: 'Worker signal', value: workerLabel, detail: operations.worker.caveat, href: '/admin/agents', maturity: overview.operations.provenance.maturity },
    { label: 'Source processing', value: `${sourceHealth.processed} / ${sourceHealth.active}`, detail: `${sourceHealth.stale} stale · ${sourceHealth.fetchFailures + sourceHealth.processingFailures} failures`, href: '/admin/radar', maturity: overview.radar.provenance.maturity },
    { label: 'Customer scope', value: overview.customers.data.organizationCount ?? 'Unavailable', detail: 'Organizations in the current minimum read', href: '/admin/customers', maturity: overview.customers.provenance.maturity },
    { label: 'Audit evidence', value: overview.audit.data.count, detail: 'Entries retained in the current stores', href: '/admin/audit', maturity: overview.audit.provenance.maturity },
  ];

  return <div className="space-y-7">
    <header className="flex flex-wrap items-start justify-between gap-5 border-b border-border pb-6"><div><p className="text-xs font-medium uppercase tracking-[0.14em] text-accent-deep">Platform Admin · Evidence control room</p><h1 className="mt-2 font-heading text-4xl font-medium tracking-tight text-foreground sm:text-5xl">Control Room</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Start with the consequence. Inspect the current evidence, then move to the domain that owns the next safe action.</p></div><Link href="/admin" className="inline-flex min-h-11 items-center gap-2 border border-border bg-white px-3 text-xs font-medium text-foreground hover:bg-muted focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"><RefreshCw className="size-3.5" aria-hidden="true" />Refresh read</Link></header>
    <aside className="flex gap-3 border border-amber-200 bg-amber-50/50 px-4 py-3"><ShieldAlert className="mt-0.5 size-4 shrink-0 text-amber-700" aria-hidden="true" /><div><p className="text-xs font-semibold text-amber-900">One broad Admin role is still the authorization boundary</p><p className="mt-1 text-xs leading-5 text-amber-800">This interface can distinguish evidence domains, but it cannot yet prove read, investigate, request, approve, execute, or administer capability separately. Treat every consequential action as compatibility behavior.</p></div></aside>
    <WarningList warnings={overview.warnings} />

    <section aria-labelledby="needs-attention-title" className="overflow-hidden border border-border bg-white">
      <header className="flex flex-wrap items-end justify-between gap-4 border-b border-border px-4 py-4 sm:px-5"><div><p className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">Prioritized operator queue</p><h2 id="needs-attention-title" className="mt-1 text-xl font-semibold tracking-tight text-foreground">Needs attention</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Ordered by current severity, then observed age. Counts and rows are bounded by the loaded read model.</p></div><Link href="/admin/operations" className="inline-flex min-h-11 items-center gap-2 text-xs font-medium text-accent-deep underline decoration-accent-tint underline-offset-4">Open full worklist<ArrowRight className="size-3.5" aria-hidden="true" /></Link></header>
      {attention.length ? <div className="divide-y divide-border">{attention.map((row) => <Link key={row.id} href={`/admin/operations?item=${encodeURIComponent(row.id)}`} className="grid min-h-20 grid-cols-[20px_minmax(0,1fr)_auto] items-center gap-3 px-4 py-3 hover:bg-muted/25 focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-primary sm:grid-cols-[20px_minmax(220px,1.15fr)_minmax(180px,.85fr)_auto_auto]"><CircleAlert className={`size-4 ${attentionColor(row)}`} aria-hidden="true" /><span className="min-w-0"><strong className="block truncate text-sm text-foreground">{row.title}</strong><small className="mt-1 block truncate text-muted-foreground">{row.subtitle ?? row.lane}</small></span><span className="col-span-2 text-xs leading-5 text-muted-foreground sm:col-span-1">{row.reason}</span><span className="hidden sm:block"><MaturityBadge maturity={row.maturity} /></span><span className={`flex items-center gap-1 font-mono text-[11px] ${attentionColor(row)}`}><Clock3 className="size-3" aria-hidden="true" />{row.age}</span></Link>)}</div> : <div className="grid min-h-52 justify-items-center content-center px-6 text-center"><Database className="size-7 text-muted-foreground" aria-hidden="true" /><p className="mt-3 text-sm font-medium text-foreground">No high- or medium-severity rows were observed</p><p className="mt-1 max-w-lg text-xs leading-5 text-muted-foreground">This is an empty attention slice, not a claim that every worker, source, provider, or customer flow is healthy.</p></div>}
      <footer className="flex flex-wrap justify-between gap-2 border-t border-border px-4 py-3 text-[11px] text-muted-foreground sm:px-5"><span>{operations.queue.summary.open} open rows in the current read</span><span>Each lane may be capped · generated {overview.generatedAt}</span></footer>
    </section>

    <section aria-labelledby="platform-state-title"><header><p className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">Current observations</p><h2 id="platform-state-title" className="mt-1 font-heading text-2xl font-medium tracking-tight text-foreground">Platform state</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Each observation keeps its own grain, source maturity, and destination. Unavailable is not converted to zero.</p></header><div className="mt-4 grid border border-border bg-white sm:grid-cols-2 xl:grid-cols-4">{stateItems.map((item, index) => <Link key={item.label} href={item.href} className={`group min-w-0 p-4 hover:bg-muted/25 focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-primary ${index < stateItems.length - 1 ? 'border-b border-border sm:border-r xl:border-b-0' : ''} ${index === 1 ? 'sm:border-r-0 xl:border-r' : ''}`}><div className="flex items-start justify-between gap-2"><p className="text-xs font-medium text-muted-foreground">{item.label}</p><ArrowRight className="size-3.5 shrink-0 text-muted-foreground" aria-hidden="true" /></div><p className="mt-2 break-words font-mono text-xl capitalize text-foreground">{item.value}</p><p className="mt-2 line-clamp-3 text-[11px] leading-4 text-muted-foreground">{item.detail}</p><span className="mt-3 inline-block"><MaturityBadge maturity={item.maturity} /></span></Link>)}</div></section>

    <section className="grid gap-4 lg:grid-cols-2" aria-label="Control Room evidence boundaries"><article className="border border-border bg-white p-4"><p className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">Read-model boundary</p><h2 className="mt-2 text-base font-semibold text-foreground">Observed is not complete</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Latest-run, compatibility, derived, partial, and durable records remain labelled. A healthy-looking zero is never substituted for a store that was not available.</p><Link href="/admin/system" className="mt-4 inline-flex min-h-11 items-center text-xs font-medium text-accent-deep underline decoration-accent-tint underline-offset-4">Inspect runtime readiness</Link></article><article className="border border-border bg-white p-4"><p className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">Action boundary</p><h2 className="mt-2 text-base font-semibold text-foreground">Request is not execution proof</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Queue request, worker acknowledgement, provider acceptance, application, delivery, and customer-visible state are independent. Use the owning domain to inspect the complete evidence chain.</p><Link href="/admin/audit" className="mt-4 inline-flex min-h-11 items-center text-xs font-medium text-accent-deep underline decoration-accent-tint underline-offset-4">Open audit evidence</Link></article></section>
  </div>;
}
