import { DataAreaHeader, MaturityBadge, MetricCard, SectionHeading, WarningList } from '@/components/platform-admin';
import type { AdminArea } from '@/lib/platformAdmin';
import type { PlatformAdminMessagingData } from '@/lib/platformAdminContinuation';

function value(value: number | null): string {
  return value === null ? '—' : String(value);
}

function statusStyle(status: string): string {
  return status === 'attention' ? 'text-amber-700' : status === 'configured' ? 'text-green-700' : status === 'unconfigured' ? 'text-red-700' : 'text-muted-foreground';
}

export default function PlatformAdminMessaging({ area }: { area: AdminArea<PlatformAdminMessagingData> }) {
  return <div className="space-y-8">
    <DataAreaHeader area={area} title="Messaging & delivery" description="Observe the current notification, email-review, Gmail, decision-email, and Workspace delivery loops. This page reports state and configuration presence; it does not expose private messages or send controls." />
    <WarningList warnings={area.warnings} />
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4" aria-label="Messaging summary"><MetricCard label="Alert email pending" value={value(area.data.summary.pendingAlertEmails)} detail="User alerts without an emailSentAt" /><MetricCard label="Email reviews" value={value(area.data.summary.pendingEmailReviews)} detail="Pending or needs-review candidates" href="/admin/messaging" /><MetricCard label="Sync failures" value={value(area.data.summary.syncFailures)} detail="Gmail sync jobs in failed state" /><MetricCard label="Delivery pending" value={value(area.data.summary.pendingDelivery)} detail="Workspace tasks not complete" href="/admin/organizations" /></section>
    <section><SectionHeading eyebrow="Channels" title="Current delivery surfaces" description="Each row names the owning runtime source and preserves unavailable or unconfigured state." /><div className="mt-4 overflow-x-auto rounded-xl border border-border bg-white"><table className="w-full min-w-[920px] text-left text-sm"><caption className="sr-only">Messaging and delivery channel health</caption><thead className="border-b border-border bg-muted/40 text-xs text-muted-foreground"><tr><th scope="col" className="px-4 py-3 font-medium">Channel</th><th scope="col" className="px-4 py-3 font-medium">State</th><th scope="col" className="px-4 py-3 font-medium">Pending</th><th scope="col" className="px-4 py-3 font-medium">Completed</th><th scope="col" className="px-4 py-3 font-medium">Latest observed</th><th scope="col" className="px-4 py-3 font-medium">Source / boundary</th></tr></thead><tbody>{area.data.channels.map((channel) => <tr key={channel.id} className="border-b border-border align-top last:border-0"><th scope="row" className="px-4 py-3 font-medium text-foreground">{channel.label}<span className="mt-1 block font-mono text-[11px] font-normal text-muted-foreground">{channel.id}</span></th><td className={`px-4 py-3 text-xs font-medium capitalize ${statusStyle(channel.status)}`}>{channel.status}</td><td className="px-4 py-3 font-mono text-xs text-foreground">{value(channel.pending)}</td><td className="px-4 py-3 font-mono text-xs text-foreground">{value(channel.completed)}</td><td className="whitespace-nowrap px-4 py-3 font-mono text-[11px] text-muted-foreground">{channel.lastObservedAt ?? 'Not observed'}</td><td className="max-w-[360px] px-4 py-3 text-xs leading-5 text-muted-foreground"><span className="block">{channel.detail}</span><span className="mt-1 block">{channel.source}</span><span className="mt-2 block"><MaturityBadge maturity={channel.maturity} /></span></td></tr>)}</tbody></table></div></section>
    <section><SectionHeading eyebrow="Configuration" title="Provider readiness" description="Presence only; secret values and provider identifiers never render." /><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{area.data.configuration.map((item) => <div key={item.label} className="rounded-xl border border-border bg-white p-4"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-medium text-foreground">{item.label}</h3><span className={`text-xs font-medium ${item.configured ? 'text-green-700' : 'text-amber-700'}`}>{item.configured ? 'Present' : 'Missing'}</span></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{item.detail}</p></div>)}</div></section>
    <section className="border-t border-border pt-6"><h2 className="text-lg font-semibold tracking-tight text-foreground">Automation boundary</h2><ul className="mt-3 grid gap-2 text-sm text-muted-foreground sm:grid-cols-2">{area.data.boundaries.map((item) => <li key={item} className="border border-border bg-white px-3 py-2">{item}</li>)}</ul></section>
  </div>;
}
