import type { AdminArea } from '@/lib/platformAdmin';
import type { PlatformAdminAnalyticsData } from '@/lib/platformAdminViews';
import { MaturityBadge, WarningList } from './platform-admin';

export default function PlatformAdminAnalytics({ area }: { area: AdminArea<PlatformAdminAnalyticsData> }) {
  const { data } = area;
  return <div className="space-y-8">
    <div><p className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">Platform Admin · Product</p><h1 className="mt-2 font-heading text-4xl font-medium tracking-tight text-foreground">Analytics</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Transparent product and operational summaries from the current runtime records. Every number stays attached to its grain and calculation.</p><div className="mt-3 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-muted-foreground"><MaturityBadge maturity={area.provenance.maturity} /><span>Data source: {area.provenance.source}</span><span>Freshness: {area.provenance.freshness}</span></div></div>
    <WarningList warnings={area.warnings} />

    <section aria-labelledby="analytics-metrics-title"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 id="analytics-metrics-title" className="text-xl font-semibold tracking-tight text-foreground">Current metrics</h2><p className="mt-1 text-xs text-muted-foreground">Derived on read; no event warehouse is implied.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.metrics.map((metric) => <div key={metric.label} className="border border-border bg-white p-4"><p className="text-xs text-muted-foreground">{metric.label}</p><p className="mt-1 font-mono text-2xl tabular-nums text-foreground">{metric.value}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{metric.detail}</p><dl className="mt-3 space-y-1 border-t border-border pt-3 text-[11px]"><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Grain</dt><dd className="font-mono text-foreground">{metric.grain}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Source</dt><dd className="max-w-[65%] truncate text-right text-foreground">{metric.source}</dd></div></dl></div>)}</div></section>

    <section className="grid gap-6 lg:grid-cols-[1.4fr_1fr]" aria-label="Funnel and Radar quality">
      <div><h2 className="text-xl font-semibold tracking-tight text-foreground">Workflow funnel</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Counts remain at their native grain; the strip is not a conversion claim between unlike records.</p><div className="mt-4 overflow-x-auto border border-border bg-white"><table className="w-full min-w-[680px] text-left text-sm"><caption className="sr-only">Workflow funnel counts and definitions</caption><thead className="border-b border-border bg-muted/30 text-[11px] text-muted-foreground"><tr><th scope="col" className="px-4 py-3 font-medium">Stage</th><th scope="col" className="px-4 py-3 font-medium">Count</th><th scope="col" className="px-4 py-3 font-medium">Grain</th><th scope="col" className="px-4 py-3 font-medium">Calculation</th></tr></thead><tbody>{data.funnel.map((stage) => <tr key={stage.label} className="border-b border-border last:border-0"><th scope="row" className="px-4 py-3 font-medium text-foreground">{stage.label}</th><td className="px-4 py-3 font-mono tabular-nums">{stage.value}</td><td className="px-4 py-3 text-xs text-muted-foreground">{stage.grain}</td><td className="px-4 py-3 text-xs text-muted-foreground">{stage.calculation}</td></tr>)}</tbody></table></div></div>
      <div><h2 className="text-xl font-semibold tracking-tight text-foreground">Radar quality</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Freshness and review signals remain separate from worker liveness.</p><div className="mt-4 divide-y divide-border border border-border bg-white">{data.quality.map((item) => <div key={item.label} className="flex items-center justify-between gap-3 px-4 py-3"><div><p className="text-sm font-medium text-foreground">{item.label}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{item.detail}</p></div><span className="font-mono text-lg tabular-nums text-foreground">{item.value}</span></div>)}</div></div>
    </section>

    <section aria-labelledby="analytics-trends-title"><h2 id="analytics-trends-title" className="text-xl font-semibold tracking-tight text-foreground">Observed monthly flow</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Only months present in current timestamps are shown; an empty month is not backfilled.</p><div className="mt-4 overflow-x-auto border border-border bg-white"><table className="w-full min-w-[680px] text-left text-sm"><caption className="sr-only">Monthly submissions, decisions, accepted works, and completed delivery</caption><thead className="border-b border-border bg-muted/30 text-[11px] text-muted-foreground"><tr><th scope="col" className="px-4 py-3 font-medium">Month UTC</th><th scope="col" className="px-4 py-3 font-medium">Submissions</th><th scope="col" className="px-4 py-3 font-medium">Decisions</th><th scope="col" className="px-4 py-3 font-medium">Accepted works</th><th scope="col" className="px-4 py-3 font-medium">Completed delivery</th></tr></thead><tbody>{data.trends.map((trend) => <tr key={trend.month} className="border-b border-border last:border-0"><th scope="row" className="px-4 py-3 font-mono text-xs font-medium text-foreground">{trend.month}</th><td className="px-4 py-3 font-mono tabular-nums">{trend.submissions}</td><td className="px-4 py-3 font-mono tabular-nums">{trend.decisions}</td><td className="px-4 py-3 font-mono tabular-nums">{trend.acceptedWorks}</td><td className="px-4 py-3 font-mono tabular-nums">{trend.completedDelivery}</td></tr>)}</tbody></table>{data.trends.length === 0 && <p className="px-4 py-10 text-center text-xs text-muted-foreground">No timestamped monthly records are available.</p>}</div></section>

    <section className="border border-dashed border-border bg-white p-4" aria-labelledby="analytics-definitions-title"><h2 id="analytics-definitions-title" className="text-sm font-semibold text-foreground">Metric boundaries</h2><ul className="mt-3 grid gap-2 text-xs leading-5 text-muted-foreground sm:grid-cols-2">{data.definitions.map((definition) => <li key={definition} className="border-l-2 border-border pl-3">{definition}</li>)}</ul></section>
  </div>;
}
