'use client';

import { useCallback, useEffect, useState, useTransition } from 'react';
import { Check, Circle, Plus, RefreshCw, Link2 } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

type Item = { id: string; label: string; state: 'missing' | 'ready' | 'complete' | 'not-applicable'; source: string; revision?: number; note?: string; libraryWorkId?: string; libraryFileId?: string; savedAnswerId?: string };
type View = { checklist: { revision?: number }; items: Item[]; progress: { total: number; complete: number; ready: number; notApplicable: number; percent: number }; requirementsConfirmed: boolean };
type Library = { works: { id: string; title: string }[]; files: { id: string; filename: string }[]; savedAnswers: { id: string; name: string }[] };
export function PrepareChecklist({ opportunityId, enabled }: { opportunityId: string; enabled: boolean }) {
  const [view, setView] = useState<View | null>(null);
  const [library, setLibrary] = useState<Library>({ works: [], files: [], savedAnswers: [] });
  const [pending, startTransition] = useTransition();
  const load = useCallback(() => fetch(`/api/me/opportunities/${opportunityId}/checklist`, { cache: 'no-store' }).then((res) => res.ok ? res.json() as Promise<View> : null).then(setView), [opportunityId]);
  useEffect(() => { if (enabled) void load(); }, [enabled, load]);
  useEffect(() => { if (enabled) void fetch('/api/me/library', { cache: 'no-store' }).then((res) => res.ok ? res.json() as Promise<Library> : null).then((data) => { if (data) setLibrary(data); }); }, [enabled]);
  if (!enabled || !view) return null;
  const toggle = (item: Item) => startTransition(async () => {
    // Widen the ternary before calculating progress: TypeScript otherwise
    // narrows `next` to only `missing | complete` and rejects the other
    // checklist states used by the readiness denominator.
    const next: Item['state'] = item.state === 'complete' ? 'missing' : 'complete';
    const res = await fetch(`/api/me/checklist-items/${item.id}`, { method: 'PATCH', headers: { 'content-type': 'application/json', ...(item.revision ? { 'Idempotency-Key':crypto.randomUUID(),'If-Match':String(item.revision) } : {}) }, body: JSON.stringify({ state: next }) });
    if (!res.ok) { toast.error('Could not update that requirement'); return; }
    await load();
    toast.success(next === 'complete' ? 'Requirement marked complete' : 'Requirement reopened');
  });
  const add = () => { const label = window.prompt('What else do you need?')?.trim(); if (!label) return; startTransition(async () => { const res = await fetch(`/api/me/opportunities/${opportunityId}/checklist/items`, { method: 'POST', headers: { 'content-type': 'application/json', ...(view.checklist.revision ? { 'Idempotency-Key':crypto.randomUUID(),'If-Match':String(view.checklist.revision) } : {}) }, body: JSON.stringify({ label }) }); if (!res.ok) { const body=await res.json().catch(()=>({})); toast.error(body.error ?? 'Could not add requirement'); return; } await load(); }); };
  const refresh = () => startTransition(async () => { const res = await fetch(`/api/me/opportunities/${opportunityId}/checklist`, { method: 'POST', headers:view.checklist.revision ? { 'Idempotency-Key':crypto.randomUUID(),'If-Match':String(view.checklist.revision) } : undefined }); if (!res.ok) { const body=await res.json().catch(()=>({})); toast.error(body.error ?? 'Could not refresh requirements'); return; } await load(); toast.success('Requirements reviewed'); });
  const attach = (item: Item, value: string) => startTransition(async () => { const [kind, id] = value.split(':'); const body = kind === 'work' ? { libraryWorkId: id } : kind === 'file' ? { libraryFileId: id } : { savedAnswerId: id }; const res = await fetch(`/api/me/checklist-items/${item.id}`, { method: 'PATCH', headers: { 'content-type': 'application/json', ...(item.revision ? { 'Idempotency-Key': crypto.randomUUID(), 'If-Match': String(item.revision) } : {}) }, body: JSON.stringify(body) }); if (!res.ok) { toast.error('Could not attach that Library item'); return; } await load(); toast.success('Library item attached'); });
  const markNotApplicable = (item: Item) => { if (!window.confirm(`Mark “${item.label}” as not applicable?`)) return; startTransition(async () => { const res = await fetch(`/api/me/checklist-items/${item.id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ state: 'not-applicable' }) }); if (!res.ok) { toast.error('Could not update that requirement'); return; } await load(); }); };
  return <Card aria-live="polite"><CardHeader className="flex-row items-center justify-between space-y-0"><div><CardTitle>Prepare to submit</CardTitle><p className="mt-1 text-sm text-muted-foreground">{view.requirementsConfirmed ? `${view.progress.complete + view.progress.ready + view.progress.notApplicable} of ${view.progress.total} ready` : 'Requirements are not confirmed yet.'}</p></div><Button variant="ghost" size="sm" disabled={pending} onClick={refresh}><RefreshCw className="mr-2 size-4" />Review changes</Button></CardHeader><CardContent className="space-y-2"><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-[width]" style={{ width: `${view.progress.percent}%` }} /></div>{view.items.map((item) => <div key={item.id} className="flex min-h-11 flex-wrap items-center gap-3 rounded-lg border border-border px-3 py-2"><button type="button" aria-label={`${item.state === 'complete' ? 'Reopen' : 'Complete'} ${item.label}`} aria-pressed={item.state === 'complete'} disabled={pending} onClick={() => toggle(item)} className="inline-flex size-8 shrink-0 items-center justify-center rounded-full text-primary outline-none ring-offset-background focus-visible:ring-2 focus-visible:ring-ring">{item.state === 'complete' ? <Check className="size-4" /> : item.state === 'not-applicable' ? <span className="text-xs">—</span> : <Circle className="size-4 text-muted-foreground" />}</button><span className={item.state === 'complete' ? 'text-sm line-through text-muted-foreground' : 'text-sm'}>{item.label}</span>{item.source === 'user-added' && <span className="text-xs text-muted-foreground">Added by you</span>}<select aria-label={`Attach Library item to ${item.label}`} disabled={pending} value={item.libraryWorkId ? `work:${item.libraryWorkId}` : item.libraryFileId ? `file:${item.libraryFileId}` : item.savedAnswerId ? `answer:${item.savedAnswerId}` : ''} onChange={(event) => { if (event.target.value) attach(item, event.target.value); }} className="min-h-11 rounded-md border border-border bg-white px-2 text-xs sm:ml-auto"><option value="">Attach from Library</option>{library.works.map((work) => <option key={work.id} value={`work:${work.id}`}>Work · {work.title}</option>)}{library.files.map((file) => <option key={file.id} value={`file:${file.id}`}>File · {file.filename}</option>)}{library.savedAnswers.map((answer) => <option key={answer.id} value={`answer:${answer.id}`}>Answer · {answer.name}</option>)}</select>{item.state !== 'not-applicable' && <Button variant="ghost" size="sm" onClick={() => markNotApplicable(item)} disabled={pending}>Not applicable</Button>}</div>)}<div className="flex flex-wrap gap-2 pt-2"><Button variant="outline" size="sm" onClick={add} disabled={pending}><Plus className="mr-2 size-4" />Add requirement</Button><span className="inline-flex items-center gap-2 px-2 text-xs text-muted-foreground"><Link2 className="size-3.5" />Library items stay private</span></div></CardContent></Card>;
}
