/**
 * Writers people name when describing where their work sits. The matcher
 * compares these with the "author comps" Missa records for each magazine;
 * anyone not listed can still be typed in. `forms` drives the suggestions
 * shown for the chosen form, in the order listed here.
 */
export type WriterForm = "fiction" | "poetry" | "nonfiction";

export interface ComparableWriter {
  name: string;
  forms: WriterForm[];
}

const F: WriterForm[] = ["fiction"];
const P: WriterForm[] = ["poetry"];
const N: WriterForm[] = ["nonfiction"];
const FN: WriterForm[] = ["fiction", "nonfiction"];
const PN: WriterForm[] = ["poetry", "nonfiction"];
const FP: WriterForm[] = ["fiction", "poetry"];
const FPN: WriterForm[] = ["fiction", "poetry", "nonfiction"];

export const COMPARABLE_WRITERS: ComparableWriter[] = [
  // Fiction: suggestions first
  { name: "Carmen Maria Machado", forms: FN },
  { name: "George Saunders", forms: FN },
  { name: "Kelly Link", forms: F },
  { name: "Chimamanda Ngozi Adichie", forms: FN },
  { name: "Lorrie Moore", forms: F },
  { name: "Lydia Davis", forms: F },
  { name: "Lesley Nneka Arimah", forms: F },
  { name: "Sally Rooney", forms: F },
  { name: "Jhumpa Lahiri", forms: FN },
  { name: "Ted Chiang", forms: F },
  { name: "Ottessa Moshfegh", forms: F },
  { name: "Danielle Evans", forms: F },
  // Fiction
  { name: "Toni Morrison", forms: FN },
  { name: "Alice Munro", forms: F },
  { name: "Raymond Carver", forms: FP },
  { name: "Denis Johnson", forms: FP },
  { name: "Amy Hempel", forms: F },
  { name: "Grace Paley", forms: FP },
  { name: "Flannery O'Connor", forms: F },
  { name: "Mavis Gallant", forms: F },
  { name: "Joy Williams", forms: F },
  { name: "Mary Gaitskill", forms: FN },
  { name: "Deborah Eisenberg", forms: F },
  { name: "Lauren Groff", forms: F },
  { name: "Karen Russell", forms: F },
  { name: "Aimee Bender", forms: F },
  { name: "Etgar Keret", forms: F },
  { name: "Jenny Offill", forms: F },
  { name: "Rachel Cusk", forms: FN },
  { name: "Ben Lerner", forms: FPN },
  { name: "Teju Cole", forms: FN },
  { name: "Ocean Vuong", forms: FP },
  { name: "Colson Whitehead", forms: F },
  { name: "Jesmyn Ward", forms: FN },
  { name: "Edwidge Danticat", forms: FN },
  { name: "Junot Díaz", forms: F },
  { name: "Yiyun Li", forms: FN },
  { name: "Kazuo Ishiguro", forms: F },
  { name: "Zadie Smith", forms: FN },
  { name: "Helen Oyeyemi", forms: F },
  { name: "Ali Smith", forms: F },
  { name: "Sarah Hall", forms: F },
  { name: "Claire Keegan", forms: F },
  { name: "Kevin Barry", forms: F },
  { name: "Sally Rooney", forms: F },
  { name: "Anne Enright", forms: F },
  { name: "Edna O'Brien", forms: F },
  { name: "Ling Ma", forms: F },
  { name: "R. F. Kuang", forms: F },
  { name: "Ted Chiang", forms: F },
  { name: "N. K. Jemisin", forms: F },
  { name: "Octavia E. Butler", forms: F },
  { name: "Ursula K. Le Guin", forms: FPN },
  { name: "Samuel R. Delany", forms: FN },
  { name: "Shirley Jackson", forms: F },
  { name: "Angela Carter", forms: F },
  { name: "Jorge Luis Borges", forms: FP },
  { name: "Italo Calvino", forms: F },
  { name: "Clarice Lispector", forms: F },
  { name: "Mariana Enríquez", forms: F },
  { name: "Samanta Schweblin", forms: F },
  { name: "Yoko Ogawa", forms: F },
  { name: "Han Kang", forms: FP },
  { name: "Olga Tokarczuk", forms: F },
  { name: "Elena Ferrante", forms: F },
  { name: "Roberto Bolaño", forms: FP },
  { name: "Haruki Murakami", forms: F },
  { name: "Banana Yoshimoto", forms: F },
  { name: "Sayaka Murata", forms: F },
  { name: "Brandon Taylor", forms: F },
  { name: "Bryan Washington", forms: F },
  { name: "Nana Kwame Adjei-Brenyah", forms: F },
  { name: "Deesha Philyaw", forms: F },
  { name: "Kristen Arnett", forms: F },
  { name: "Lucia Berlin", forms: F },
  { name: "Leonora Carrington", forms: F },
  { name: "Sofia Samatar", forms: FPN },
  { name: "Kij Johnson", forms: F },
  { name: "Ken Liu", forms: F },
  { name: "Rebecca Makkai", forms: F },
  { name: "Tommy Orange", forms: F },
  { name: "Louise Erdrich", forms: FPN },
  { name: "Sandra Cisneros", forms: FP },
  { name: "Ayşegül Savaş", forms: F },
  { name: "Weike Wang", forms: F },
  { name: "Elizabeth McCracken", forms: FN },
  { name: "Joyce Carol Oates", forms: FPN },
  { name: "Margaret Atwood", forms: FPN },
  { name: "Percival Everett", forms: F },
  { name: "Viet Thanh Nguyen", forms: FN },
  { name: "Ruth Ozeki", forms: F },
  { name: "Ali Smith", forms: F },
  { name: "Max Porter", forms: F },
  { name: "Daisy Johnson", forms: F },
  { name: "Ottessa Moshfegh", forms: F },
  { name: "Ling Ma", forms: F },
  { name: "Hilary Mantel", forms: FN },
  { name: "Ann Quin", forms: F },
  { name: "Diane Williams", forms: F },
  { name: "Gary Lutz", forms: F },
  { name: "Kathy Fish", forms: F },
  { name: "Sherrie Flick", forms: F },
  { name: "Robert Coover", forms: F },
  { name: "Donald Barthelme", forms: F },
  // African and diaspora fiction
  { name: "Chinua Achebe", forms: FPN },
  { name: "Ngũgĩ wa Thiong'o", forms: FN },
  { name: "Ben Okri", forms: FP },
  { name: "Chigozie Obioma", forms: F },
  { name: "Akwaeke Emezi", forms: FP },
  { name: "Ayọ̀bámi Adébáyọ̀", forms: F },
  { name: "Oyinkan Braithwaite", forms: F },
  { name: "Chibundu Onuzo", forms: F },
  { name: "Sefi Atta", forms: F },
  { name: "Chika Unigwe", forms: F },
  { name: "Helon Habila", forms: FN },
  { name: "A. Igoni Barrett", forms: F },
  { name: "Jowhor Ile", forms: F },
  { name: "Abi Daré", forms: F },
  { name: "Nnedi Okorafor", forms: F },
  { name: "Tomi Adeyemi", forms: F },
  { name: "Buchi Emecheta", forms: F },
  { name: "Flora Nwapa", forms: F },
  { name: "Amos Tutuola", forms: F },
  { name: "Wole Soyinka", forms: FPN },
  { name: "Okey Ndibe", forms: FN },
  { name: "Adaobi Tricia Nwaubani", forms: FN },
  { name: "Elnathan John", forms: FN },
  { name: "Abubakar Adam Ibrahim", forms: F },
  { name: "Uwem Akpan", forms: F },
  { name: "Chris Abani", forms: FP },
  { name: "Tsitsi Dangarembga", forms: F },
  { name: "NoViolet Bulawayo", forms: F },
  { name: "Yaa Gyasi", forms: F },
  { name: "Ama Ata Aidoo", forms: FP },
  { name: "Ayi Kwei Armah", forms: F },
  { name: "Nadine Gordimer", forms: F },
  { name: "J. M. Coetzee", forms: FN },
  { name: "Zakes Mda", forms: F },
  { name: "Bessie Head", forms: F },
  { name: "Nuruddin Farah", forms: F },
  { name: "Abdulrazak Gurnah", forms: F },
  { name: "Binyavanga Wainaina", forms: FN },
  { name: "Yvonne Adhiambo Owuor", forms: F },
  { name: "Maaza Mengiste", forms: F },
  { name: "Dinaw Mengestu", forms: F },
  { name: "Leila Aboulela", forms: F },
  { name: "Nadifa Mohamed", forms: F },
  { name: "Petina Gappah", forms: F },
  { name: "Imbolo Mbue", forms: F },
  { name: "Mohammed Naseehu Ali", forms: F },
  { name: "Damon Galgut", forms: F },
  { name: "Mia Couto", forms: FP },
  { name: "Mariama Bâ", forms: F },
  { name: "Tade Thompson", forms: F },
  { name: "Wole Talabi", forms: F },
  { name: "Suyi Davies Okungbowa", forms: F },
  { name: "Irenosen Okojie", forms: F },
  { name: "Bernardine Evaristo", forms: FP },
  { name: "Caryl Phillips", forms: FN },
  { name: "Jamaica Kincaid", forms: FN },
  { name: "Marlon James", forms: F },
  { name: "Kei Miller", forms: FP },
  { name: "Earl Lovelace", forms: F },
  { name: "Edwidge Danticat", forms: FN },
  { name: "Arundhati Roy", forms: FN },
  { name: "Salman Rushdie", forms: FN },
  { name: "Mohsin Hamid", forms: F },
  { name: "Kamila Shamsie", forms: F },
  { name: "Anuk Arudpragasam", forms: F },
  // Poetry: suggestions first
  { name: "Ada Limón", forms: P },
  { name: "Ocean Vuong", forms: FP },
  { name: "Kaveh Akbar", forms: FP },
  { name: "Natalie Diaz", forms: P },
  { name: "Warsan Shire", forms: P },
  { name: "Ross Gay", forms: PN },
  { name: "Tracy K. Smith", forms: PN },
  { name: "Danez Smith", forms: P },
  { name: "Safia Elhillo", forms: P },
  { name: "Louise Glück", forms: PN },
  { name: "Mary Oliver", forms: PN },
  { name: "Claudia Rankine", forms: PN },
  // Poetry
  { name: "Terrance Hayes", forms: P },
  { name: "Hanif Abdurraqib", forms: PN },
  { name: "Jericho Brown", forms: P },
  { name: "Joy Harjo", forms: PN },
  { name: "Layli Long Soldier", forms: P },
  { name: "Franny Choi", forms: P },
  { name: "Chen Chen", forms: P },
  { name: "Aimee Nezhukumatathil", forms: PN },
  { name: "Diane Seuss", forms: P },
  { name: "Carl Phillips", forms: PN },
  { name: "Morgan Parker", forms: PN },
  { name: "Eduardo C. Corral", forms: P },
  { name: "Fatimah Asghar", forms: FP },
  { name: "Solmaz Sharif", forms: P },
  { name: "Mosab Abu Toha", forms: P },
  { name: "Victoria Chang", forms: PN },
  { name: "Sharon Olds", forms: P },
  { name: "Lucille Clifton", forms: P },
  { name: "Gwendolyn Brooks", forms: P },
  { name: "Elizabeth Bishop", forms: P },
  { name: "Sylvia Plath", forms: FP },
  { name: "Anne Carson", forms: PN },
  { name: "Jorie Graham", forms: P },
  { name: "Brenda Shaughnessy", forms: P },
  { name: "Mary Ruefle", forms: PN },
  { name: "Maggie Smith", forms: PN },
  { name: "Ilya Kaminsky", forms: P },
  { name: "Tishani Doshi", forms: FP },
  { name: "Raymond Antrobus", forms: P },
  { name: "Ocean Vuong", forms: FP },
  { name: "Roger Reeves", forms: P },
  { name: "Robin Coste Lewis", forms: P },
  { name: "Patricia Smith", forms: P },
  { name: "Yusef Komunyakaa", forms: P },
  { name: "Rita Dove", forms: FP },
  { name: "Seamus Heaney", forms: PN },
  { name: "Derek Walcott", forms: P },
  { name: "Kamau Brathwaite", forms: P },
  { name: "Dionne Brand", forms: FPN },
  { name: "Mahmoud Darwish", forms: P },
  { name: "Wisława Szymborska", forms: P },
  { name: "Pablo Neruda", forms: P },
  { name: "Agha Shahid Ali", forms: P },
  { name: "Mary Jean Chan", forms: P },
  { name: "Ocean Vuong", forms: FP },
  { name: "Hala Alyan", forms: FP },
  { name: "Marwa Helal", forms: P },
  { name: "Jos Charles", forms: P },
  { name: "CAConrad", forms: P },
  { name: "Ilya Kaminsky", forms: P },
  { name: "Cathy Park Hong", forms: PN },
  { name: "Natalie Shapero", forms: P },
  { name: "Tyehimba Jess", forms: P },
  { name: "Camille T. Dungy", forms: PN },
  { name: "Saeed Jones", forms: PN },
  { name: "Paisley Rekdal", forms: PN },
  { name: "Sarah Kay", forms: P },
  { name: "Kim Addonizio", forms: FP },
  // African and diaspora poetry
  { name: "Romeo Oriogun", forms: P },
  { name: "Gbenga Adeoba", forms: P },
  { name: "Logan February", forms: P },
  { name: "Ladan Osman", forms: P },
  { name: "Kechi Nomu", forms: P },
  { name: "Tolu Oloruntoba", forms: P },
  { name: "Ijeoma Umebinyuo", forms: P },
  { name: "Inua Ellams", forms: P },
  { name: "Tade Ipadeola", forms: P },
  { name: "Gabriel Okara", forms: FP },
  { name: "Christopher Okigbo", forms: P },
  { name: "Niyi Osundare", forms: P },
  { name: "Tanure Ojaide", forms: P },
  { name: "Ama Ata Aidoo", forms: FP },
  { name: "Kwame Dawes", forms: PN },
  { name: "Koleka Putuma", forms: P },
  { name: "Gabeba Baderoon", forms: P },
  { name: "Tjawangwa Dema", forms: P },
  { name: "Nick Makoha", forms: P },
  { name: "Dami Ajayi", forms: P },
  { name: "Theresa Lola", forms: P },
  { name: "Caleb Femi", forms: P },
  { name: "Yomi Ṣode", forms: P },
  { name: "Chris Abani", forms: FP },
  { name: "Warsan Shire", forms: P },
  { name: "Nikky Finney", forms: P },
  { name: "Aja Monet", forms: P },
  // Nonfiction: suggestions first
  { name: "Maggie Nelson", forms: PN },
  { name: "Joan Didion", forms: FN },
  { name: "Rebecca Solnit", forms: N },
  { name: "Leslie Jamison", forms: FN },
  { name: "Jia Tolentino", forms: N },
  { name: "Hilton Als", forms: N },
  { name: "Annie Dillard", forms: FPN },
  { name: "James Baldwin", forms: FN },
  { name: "Kiese Laymon", forms: FN },
  { name: "Eula Biss", forms: N },
  { name: "Robin Wall Kimmerer", forms: N },
  { name: "Saidiya Hartman", forms: N },
  // Nonfiction
  { name: "Zadie Smith", forms: FN },
  { name: "Elif Batuman", forms: FN },
  { name: "Alexander Chee", forms: FN },
  { name: "Melissa Febos", forms: N },
  { name: "Esmé Weijun Wang", forms: FN },
  { name: "Durga Chew-Bose", forms: N },
  { name: "Brian Doyle", forms: FN },
  { name: "John Jeremiah Sullivan", forms: N },
  { name: "David Foster Wallace", forms: FN },
  { name: "Ta-Nehisi Coates", forms: FN },
  { name: "Audre Lorde", forms: PN },
  { name: "bell hooks", forms: N },
  { name: "Susan Sontag", forms: FN },
  { name: "Virginia Woolf", forms: FN },
  { name: "Olivia Laing", forms: FN },
  { name: "Helen Macdonald", forms: N },
  { name: "Robert Macfarlane", forms: N },
  { name: "Kathleen Jamie", forms: PN },
  { name: "Elizabeth Alexander", forms: PN },
  { name: "Natasha Trethewey", forms: PN },
  { name: "Brian Blanchfield", forms: PN },
  { name: "Wendy S. Walters", forms: N },
  { name: "Cheryl Strayed", forms: FN },
  { name: "Roxane Gay", forms: FN },
  { name: "Ingrid Rojas Contreras", forms: FN },
  { name: "Cristina Rivera Garza", forms: FN },
  { name: "Valeria Luiselli", forms: FN },
  { name: "Emmanuel Iduma", forms: N },
  { name: "Pumla Dineo Gqola", forms: N },
  { name: "Sisonke Msimang", forms: N },
  { name: "Siddhartha Mukherjee", forms: N },
  { name: "Atul Gawande", forms: N },
  { name: "Patrick Radden Keefe", forms: N },
];

const SUGGESTION_COUNT = 8;

/** The catalogue with repeats removed, in the order above. */
export const WRITER_NAMES: string[] = Array.from(
  new Set(COMPARABLE_WRITERS.map((writer) => writer.name)),
);

const formsByName = new Map<string, WriterForm[]>();
for (const writer of COMPARABLE_WRITERS) {
  if (!formsByName.has(writer.name)) formsByName.set(writer.name, writer.forms);
}

const FORM_LABELS: Record<WriterForm, string> = {
  fiction: "Fiction",
  poetry: "Poetry",
  nonfiction: "Nonfiction",
};

/** "Fiction · Nonfiction" for a catalogue name, or null for a typed name. */
export function writerFormsLabel(name: string): string | null {
  const forms = formsByName.get(name);
  return forms ? forms.map((form) => FORM_LABELS[form]).join(" · ") : null;
}

/** The first catalogue names for a manuscript form. */
export function suggestedWriters(
  genre: "fiction" | "poetry" | "nonfiction" | "flash" | "hybrid",
): string[] {
  const form: WriterForm =
    genre === "poetry"
      ? "poetry"
      : genre === "nonfiction"
        ? "nonfiction"
        : "fiction";
  return WRITER_NAMES.filter((name) =>
    formsByName.get(name)?.includes(form),
  ).slice(0, SUGGESTION_COUNT);
}
