import { canonicalTaxonomySelection } from "@missa/taxonomy";
import type { LibraryFile, LibraryWork, LibraryWorkTaxonomyAssignment, SavedAnswer, TrackerExportV1 } from "@missa/radar-engine";
import type { Pool, PoolClient } from "pg";
import { randomUUID } from "node:crypto";
import { CreatorConflictError, CreatorRepositoryBase, type CreatorCommandEnvelope, type CreatorReceipt } from "./creatorRepository.js";
import { loadCanonicalTrackerImportStore } from "./canonicalTrackerImport.js";
import { canonicalPublicOpportunityPredicate } from "./canonicalOpportunityProjection.js";

export class CreatorLibraryValidationError extends Error {}
export class CreatorLibraryConflictError extends Error {}
export type CreatorLibraryWork = LibraryWork & { revision: number; trackerCount: number; checklistCount: number };
export type CreatorLibraryFile = LibraryFile & { revision: number; linkedWorks: Array<{ id: string; title: string }>; checklistCount: number };
export type CreatorSavedAnswer = SavedAnswer & { revision: number; checklistCount: number };
export type CreatorLibraryView = { works: CreatorLibraryWork[]; files: CreatorLibraryFile[]; savedAnswers: CreatorSavedAnswer[] };
export type CreatorWorkConnections = {
  tracker: Array<{ opportunityId: string; title: string; organizationName?: string; status: string; deadline?: string }>;
  checklists: Array<{ opportunityId: string; title: string; itemCount: number }>;
};

type WorkRow = { id:string;title:string;description:string|null;metadata:Record<string,unknown>;revision:number;created_at:Date|string;updated_at:Date|string;tracker_count:number|string;checklist_count:number|string };
type FileRow = { id:string;storage_key:string;name:string;mime_type:string|null;size_bytes:number|null;revision:number;created_at:Date|string;linked_works:Array<{id:string;title:string}>|null;checklist_count:number|string };
type AnswerRow = { id:string;label:string;answer:string;revision:number;created_at:Date|string;updated_at:Date|string;checklist_count:number|string };
const iso=(value:Date|string)=>new Date(value).toISOString();
const count=(value:number|string)=>Number(value)||0;
function required(value:unknown,label:string,max:number){ if(typeof value!=="string"||!value.trim()||value.trim().length>max) throw new CreatorLibraryValidationError(`${label} must be between 1 and ${max} characters.`); return value.trim(); }
function optional(value:unknown,label:string,max:number){ if(value===undefined||value===null||value==='') return undefined; if(typeof value!=="string"||value.trim().length>max) throw new CreatorLibraryValidationError(`${label} must be ${max} characters or fewer.`); return value.trim()||undefined; }
function assignments(value:unknown):LibraryWorkTaxonomyAssignment[]|undefined { if(value===undefined)return undefined;if(value===null)return [];if(!Array.isArray(value)||value.length>32)throw new CreatorLibraryValidationError("Choose no more than 32 canonical Work terms.");const selection=canonicalTaxonomySelection(value.map((id)=>typeof id==='string'?id.trim():''));if(selection.invalidTermIds.length||selection.termIds.length!==value.length)throw new CreatorLibraryValidationError(`Unknown Work taxonomy term: ${selection.invalidTermIds[0]??'duplicate term'}.`);return selection.termIds.map((termId,index)=>({termId,primary:index===0,assignmentOrigin:'user'}));}
function work(row:WorkRow,userId:string):CreatorLibraryWork { const metadata=row.metadata??{};return {id:row.id,userId,title:row.title,...(row.description?{description:row.description}:{}),...(typeof metadata.fileId==='string'?{fileId:metadata.fileId}:{}),...(Array.isArray(metadata.taxonomyAssignments)?{taxonomyAssignments:metadata.taxonomyAssignments as LibraryWorkTaxonomyAssignment[]}:{}),createdAt:iso(row.created_at),updatedAt:iso(row.updated_at),revision:row.revision,trackerCount:count(row.tracker_count),checklistCount:count(row.checklist_count)}; }
function file(row:FileRow,userId:string):CreatorLibraryFile{return{id:row.id,userId,filename:row.name,contentType:row.mime_type??'application/octet-stream',byteLength:row.size_bytes??0,storageKey:row.storage_key,createdAt:iso(row.created_at),revision:row.revision,linkedWorks:row.linked_works??[],checklistCount:count(row.checklist_count)};}
function answer(row:AnswerRow,userId:string):CreatorSavedAnswer{return{id:row.id,userId,name:row.label,body:row.answer,createdAt:iso(row.created_at),updatedAt:iso(row.updated_at),revision:row.revision,checklistCount:count(row.checklist_count)};}

export class PostgresCreatorLibraryRepository extends CreatorRepositoryBase {
  constructor(pool:Pool){super(pool);}
  async recordExportAudit(input:{accountId:string;userId:string;format:'json'|'csv';scope:'all'|'tracker'|'library';trackerRows:number;libraryRows:number}):Promise<void>{const correlationId=randomUUID();await this.query(`insert into audit_events(account_id,action,target_type,target_id,detail,correlation_id) values($1,'data.exported','user_profile',$2,$3::jsonb,$4)`,[input.accountId,input.userId,JSON.stringify({format:input.format,scope:input.scope,trackerRows:input.trackerRows,libraryRows:input.libraryRows}),correlationId]);}
  async library(accountId:string,userId:string):Promise<CreatorLibraryView>{
    const [works,files,answers]=await Promise.all([
      this.query<WorkRow>(`select w.*,(select count(*) from tracked_opportunities t where t.account_id=w.account_id and t.work_id=w.id) tracker_count,(select count(*) from tracker_checklist_items i where i.account_id=w.account_id and i.work_id=w.id) checklist_count from creator_library_works w where w.account_id=$1 order by w.updated_at desc,w.id desc`,[accountId]),
      this.query<FileRow>(`select f.*,(select coalesce(jsonb_agg(jsonb_build_object('id',w.id,'title',w.title) order by w.title),'[]'::jsonb) from creator_library_works w where w.account_id=f.account_id and w.metadata->>'fileId'=f.id) linked_works,(select count(*) from tracker_checklist_items i where i.account_id=f.account_id and i.file_id=f.id) checklist_count from creator_library_files f where f.account_id=$1 order by f.created_at desc,f.id desc`,[accountId]),
      this.query<AnswerRow>(`select a.*,(select count(*) from tracker_checklist_items i where i.account_id=a.account_id and i.saved_answer_id=a.id) checklist_count from creator_saved_answers a where a.account_id=$1 order by a.updated_at desc,a.id desc`,[accountId]),
    ]);
    return{works:works.rows.map((r)=>work(r,userId)),files:files.rows.map((r)=>file(r,userId)),savedAnswers:answers.rows.map((r)=>answer(r,userId))};
  }
  async trackerExport(accountId:string,userId:string,now=new Date()):Promise<TrackerExportV1>{
    const store=await loadCanonicalTrackerImportStore(this.pool,accountId,userId);
    const canonical:TrackerExportV1['tracker']=store.tracked.filter((item)=>item.userId===userId).map((item)=>{const opportunity=store.opportunities.get(item.opportunityId);return{opportunityId:item.opportunityId,myStatus:item.myStatus,trackedAt:item.trackedAt,...(item.submittedAt?{submittedAt:item.submittedAt}:{}),dataState:opportunity?'available' as const:'unavailable' as const,statusEvents:item.events.map((event)=>({...event})),...(opportunity?{title:opportunity.fields.title,...(opportunity.fields.organizationName?{organizationName:opportunity.fields.organizationName}:{}),type:opportunity.fields.type,opportunityStatus:opportunity.status,...(opportunity.fields.deadline.date?{deadline:opportunity.fields.deadline.date}:{}),deadlineKind:opportunity.fields.deadline.kind,sourceUrl:opportunity.sourceUrl}:{})};});
    const manual:TrackerExportV1['tracker']=store.manualTrackerEntries.filter((entry)=>entry.userId===userId).map((entry)=>({opportunityId:entry.id,title:entry.title,organizationName:entry.organizationName,type:'manual-import',opportunityStatus:'private-import',myStatus:entry.myStatus,trackedAt:entry.importedAt,...(entry.submittedAt?{submittedAt:entry.submittedAt}:{}),...(entry.deadline?{deadline:entry.deadline}:{}),deadlineKind:entry.deadline?'exact' as const:'unknown' as const,...(entry.sourceUrl?{sourceUrl:entry.sourceUrl}:{}),dataState:'unavailable' as const,statusEvents:entry.events?.map((event)=>({...event}))??[]}));
    const tracker=[...canonical,...manual].sort((a,b)=>a.trackedAt.localeCompare(b.trackedAt)||a.opportunityId.localeCompare(b.opportunityId));
    return{exportVersion:1,generatedAt:now.toISOString(),included:['tracker'],omitted:['library'],tracker};
  }
  async workConnections(accountId:string,workId:string):Promise<CreatorWorkConnections>{
    const [tracker,checklists]=await Promise.all([
      this.query<{opportunity_id:string;title:string;organization_name:string|null;status:string;deadline_date:string|null}>(`select t.opportunity_id,o.title,coalesce(org.data->>'name',o.organization_id) organization_name,t.status,o.deadline_date from tracked_opportunities t join opportunities o on o.id=t.opportunity_id left join radar_organizations org on org.id=o.organization_id where t.account_id=$1 and t.work_id=$2 and ${canonicalPublicOpportunityPredicate("o")} order by o.title`,[accountId,workId]),
      this.query<{opportunity_id:string;title:string;item_count:number|string}>(`select t.opportunity_id,o.title,count(*) item_count from tracker_checklist_items i join tracker_checklists c on c.id=i.checklist_id and c.account_id=i.account_id join tracked_opportunities t on t.id=c.tracked_opportunity_id join opportunities o on o.id=t.opportunity_id where i.account_id=$1 and i.work_id=$2 and ${canonicalPublicOpportunityPredicate("o")} group by t.opportunity_id,o.title order by o.title`,[accountId,workId]),
    ]);
    return{tracker:tracker.rows.map((r)=>({opportunityId:r.opportunity_id,title:r.title,...(r.organization_name?{organizationName:r.organization_name}:{}),status:r.status,...(r.deadline_date?{deadline:r.deadline_date}:{})})),checklists:checklists.rows.map((r)=>({opportunityId:r.opportunity_id,title:r.title,itemCount:count(r.item_count)}))};
  }
  async linkTrackerWork(envelope:CreatorCommandEnvelope,opportunityId:string,workId?:string){return this.executeOwnerCommand(envelope,async(client)=>{const tracked=await client.query<{id:string;revision:number}>(`select id,revision from tracked_opportunities where account_id=$1 and opportunity_id=$2 for update`,[envelope.accountId,opportunityId]);const row=tracked.rows[0];if(!row)throw new CreatorLibraryValidationError('Tracker item not found.');if(row.revision!==envelope.expectedRevision)throw new CreatorConflictError('tracked-opportunity',opportunityId,envelope.expectedRevision,row.revision);if(workId){await client.query("select pg_advisory_xact_lock(hashtext($1))",[`library-work:${workId}`]);const owned=await client.query('select id from creator_library_works where id=$1 and account_id=$2 for share',[workId,envelope.accountId]);if(!owned.rows[0])throw new CreatorLibraryValidationError('Work not found.');}const updated=(await client.query<{revision:number}>(`update tracked_opportunities set work_id=$3,revision=revision+1,updated_at=now() where id=$1 and account_id=$2 and revision=$4 returning revision`,[row.id,envelope.accountId,workId??null,row.revision])).rows[0]!;return{resourceType:'tracked-opportunity',resourceId:opportunityId,revision:updated.revision};});}
  async createWork(envelope:CreatorCommandEnvelope,userId:string,input:{id:string;title:unknown;description?:unknown;fileId?:unknown;taxonomyTermIds?:unknown}){const title=required(input.title,'Title',200),description=optional(input.description,'Description',4000),fileId=optional(input.fileId,'File',200),taxonomyAssignments=assignments(input.taxonomyTermIds);return this.executeOwnerCommand(envelope,async(client)=>{if(fileId)await this.requireFile(client,envelope.accountId,fileId);const row=(await client.query<{revision:number}>(`insert into creator_library_works(id,account_id,title,description,metadata) values($1,$2,$3,$4,$5::jsonb) returning revision`,[input.id,envelope.accountId,title,description??null,JSON.stringify({...(fileId?{fileId}:{}),...(taxonomyAssignments?.length?{taxonomyAssignments}:{})})])).rows[0]!;return{resourceType:'library-work',resourceId:input.id,revision:row.revision};});}
  async updateWork(envelope:CreatorCommandEnvelope,workId:string,input:{title?:unknown;description?:unknown;fileId?:unknown|null;taxonomyTermIds?:unknown}){return this.executeOwnerCommand(envelope,async(client)=>{const current=await client.query<{title:string;description:string|null;metadata:Record<string,unknown>;revision:number}>(`select title,description,metadata,revision from creator_library_works where id=$1 and account_id=$2 for update`,[workId,envelope.accountId]);const row=current.rows[0];if(!row)throw new CreatorLibraryValidationError('Work not found.');if(row.revision!==envelope.expectedRevision)throw new CreatorConflictError('library-work',workId,envelope.expectedRevision,row.revision);const fileId=input.fileId===null?undefined:input.fileId===undefined?(typeof row.metadata.fileId==='string'?row.metadata.fileId:undefined):optional(input.fileId,'File',200);if(fileId)await this.requireFile(client,envelope.accountId,fileId);const taxonomyAssignments=input.taxonomyTermIds===undefined?row.metadata.taxonomyAssignments:assignments(input.taxonomyTermIds);const updated=(await client.query<{revision:number}>(`update creator_library_works set title=$3,description=$4,metadata=$5::jsonb,revision=revision+1,updated_at=now() where id=$1 and account_id=$2 and revision=$6 returning revision`,[workId,envelope.accountId,input.title===undefined?row.title:required(input.title,'Title',200),input.description===undefined?row.description:optional(input.description,'Description',4000)??null,JSON.stringify({...(fileId?{fileId}:{}),...(Array.isArray(taxonomyAssignments)&&taxonomyAssignments.length?{taxonomyAssignments}:{})}),row.revision])).rows[0]!;return{resourceType:'library-work',resourceId:workId,revision:updated.revision};});}
  async deleteWork(envelope:CreatorCommandEnvelope,workId:string){return this.executeOwnerCommand(envelope,async(client)=>{await client.query("select pg_advisory_xact_lock(hashtext($1))",[`library-work:${workId}`]);const refs=await client.query<{revision:number;tracker_count:number|string;checklist_count:number|string}>(`select w.revision,(select count(*) from tracked_opportunities t where t.account_id=w.account_id and t.work_id=w.id) tracker_count,(select count(*) from tracker_checklist_items i where i.account_id=w.account_id and i.work_id=w.id) checklist_count from creator_library_works w where w.id=$1 and w.account_id=$2 for update`,[workId,envelope.accountId]);const row=refs.rows[0];if(!row)throw new CreatorLibraryValidationError('Work not found.');if(row.revision!==envelope.expectedRevision)throw new CreatorConflictError('library-work',workId,envelope.expectedRevision,row.revision);if(count(row.tracker_count)||count(row.checklist_count))throw new CreatorLibraryConflictError('This Work is still linked to Tracker or a checklist. Remove those links before deleting it.');await client.query('delete from creator_library_works where id=$1 and account_id=$2',[workId,envelope.accountId]);return{resourceType:'library-work',resourceId:workId,revision:row.revision+1};});}
  async createFile(envelope:CreatorCommandEnvelope,userId:string,input:{id:string;filename:unknown;contentType:unknown;byteLength:unknown;storageKey:unknown}){const filename=required(input.filename,'Filename',240),contentType=required(input.contentType,'Content type',160),storageKey=required(input.storageKey,'Storage key',500),byteLength=Number(input.byteLength);if(!Number.isSafeInteger(byteLength)||byteLength<0||byteLength>100*1024*1024)throw new CreatorLibraryValidationError('File must be 100 MiB or smaller.');return this.executeOwnerCommand(envelope,async(client)=>{const row=(await client.query<{revision:number}>(`insert into creator_library_files(id,account_id,storage_key,name,mime_type,size_bytes) values($1,$2,$3,$4,$5,$6) returning revision`,[input.id,envelope.accountId,storageKey,filename,contentType,byteLength])).rows[0]!;return{resourceType:'library-file',resourceId:input.id,revision:row.revision};});}
  async deleteFile(envelope:CreatorCommandEnvelope,fileId:string){let storageKey='',cleanupId='';const receipt=await this.executeOwnerCommand(envelope,async(client)=>{await client.query("select pg_advisory_xact_lock(hashtext($1))",[`library-file:${fileId}`]);const refs=await client.query<{revision:number;storage_key:string;work_count:number|string;checklist_count:number|string}>(`select f.revision,f.storage_key,(select count(*) from creator_library_works w where w.account_id=f.account_id and w.metadata->>'fileId'=f.id) work_count,(select count(*) from tracker_checklist_items i where i.account_id=f.account_id and i.file_id=f.id) checklist_count from creator_library_files f where f.id=$1 and f.account_id=$2 for update`,[fileId,envelope.accountId]);const row=refs.rows[0];if(!row)throw new CreatorLibraryValidationError('File not found.');if(row.revision!==envelope.expectedRevision)throw new CreatorConflictError('library-file',fileId,envelope.expectedRevision,row.revision);if(count(row.work_count)||count(row.checklist_count))throw new CreatorLibraryConflictError('This file is still linked to a Work or checklist. Detach it before deleting the stored file.');storageKey=row.storage_key;const cleanup=await client.query<{id:string}>(`insert into creator_library_file_deletions(account_id,file_id,storage_key) values($1,$2,$3) returning id`,[envelope.accountId,fileId,storageKey]);cleanupId=cleanup.rows[0]!.id;await client.query('delete from creator_library_files where id=$1 and account_id=$2',[fileId,envelope.accountId]);return{resourceType:'library-file',resourceId:fileId,revision:row.revision+1};});return{receipt,storageKey,cleanupId};}
  async settleFileDeletion(accountId:string,cleanupId:string,status:'deleted'|'failed',error?:string){await this.query(`update creator_library_file_deletions set status=$3,attempts=attempts+1,last_error=$4,updated_at=now() where id=$1 and account_id=$2`,[cleanupId,accountId,status,error?.slice(0,500)??null]);}
  async queueFileCleanup(accountId:string,fileId:string,storageKey:string,error?:string){await this.query(`insert into creator_library_file_deletions(account_id,file_id,storage_key,status,attempts,last_error) values($1,$2,$3,'failed',1,$4)`,[accountId,fileId,storageKey,error?.slice(0,500)??'Metadata creation failed']);}
  async createAnswer(envelope:CreatorCommandEnvelope,userId:string,input:{id:string;name:unknown;body:unknown}){const name=required(input.name,'Name',120),body=required(input.body,'Answer',20000);return this.executeOwnerCommand(envelope,async(client)=>{const row=(await client.query<{revision:number}>(`insert into creator_saved_answers(id,account_id,label,answer) values($1,$2,$3,$4) returning revision`,[input.id,envelope.accountId,name,body])).rows[0]!;return{resourceType:'saved-answer',resourceId:input.id,revision:row.revision};});}
  async updateAnswer(envelope:CreatorCommandEnvelope,answerId:string,input:{name?:unknown;body?:unknown}){return this.executeOwnerCommand(envelope,async(client)=>{const current=await client.query<{label:string;answer:string;revision:number}>(`select label,answer,revision from creator_saved_answers where id=$1 and account_id=$2 for update`,[answerId,envelope.accountId]);const row=current.rows[0];if(!row)throw new CreatorLibraryValidationError('Saved Answer not found.');if(row.revision!==envelope.expectedRevision)throw new CreatorConflictError('saved-answer',answerId,envelope.expectedRevision,row.revision);const updated=(await client.query<{revision:number}>(`update creator_saved_answers set label=$3,answer=$4,revision=revision+1,updated_at=now() where id=$1 and account_id=$2 and revision=$5 returning revision`,[answerId,envelope.accountId,input.name===undefined?row.label:required(input.name,'Name',120),input.body===undefined?row.answer:required(input.body,'Answer',20000),row.revision])).rows[0]!;return{resourceType:'saved-answer',resourceId:answerId,revision:updated.revision};});}
  async deleteAnswer(envelope:CreatorCommandEnvelope,answerId:string){return this.executeOwnerCommand(envelope,async(client)=>{await client.query("select pg_advisory_xact_lock(hashtext($1))",[`saved-answer:${answerId}`]);const refs=await client.query<{revision:number;checklist_count:number|string}>(`select a.revision,(select count(*) from tracker_checklist_items i where i.account_id=a.account_id and i.saved_answer_id=a.id) checklist_count from creator_saved_answers a where a.id=$1 and a.account_id=$2 for update`,[answerId,envelope.accountId]);const row=refs.rows[0];if(!row)throw new CreatorLibraryValidationError('Saved Answer not found.');if(row.revision!==envelope.expectedRevision)throw new CreatorConflictError('saved-answer',answerId,envelope.expectedRevision,row.revision);if(count(row.checklist_count))throw new CreatorLibraryConflictError('This Saved Answer is still linked to a checklist. Remove that link before deleting it.');await client.query('delete from creator_saved_answers where id=$1 and account_id=$2',[answerId,envelope.accountId]);return{resourceType:'saved-answer',resourceId:answerId,revision:row.revision+1};});}
  private async requireFile(client:PoolClient,accountId:string,fileId:string){await client.query("select pg_advisory_xact_lock(hashtext($1))",[`library-file:${fileId}`]);const file=await client.query('select id from creator_library_files where id=$1 and account_id=$2 for share',[fileId,accountId]);if(!file.rows[0])throw new CreatorLibraryValidationError('That file is not available in your Library.');}
}
