import { expandMany, org } from '../helpers.js';
import type { SourceRegistryEntry } from '../types.js';

export const CNF_SOURCES: SourceRegistryEntry[] = expandMany(
  [
    org('Creative Nonfiction', 'https://www.creativenonfiction.org/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Brevity CNF', 'https://brevitymag.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('River Teeth', 'https://www.riverteethjournal.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Hippocampus Magazine', 'https://www.hippocampusmagazine.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Sun CNF', 'https://www.thesunmagazine.org/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Fourth Genre', 'https://fourthgenre.msu.edu/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Seneca Review', 'https://www.hws.edu/academics/senecareview/submit.aspx', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Normal School CNF', 'https://thenormalschool.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Rumpus CNF', 'https://therumpus.net/submissions/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Guernica CNF', 'https://www.guernicamag.com/submissions/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Longreads', 'https://longreads.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Believer CNF', 'https://www.thebeliever.net/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Narrative CNF', 'https://www.narrativemagazine.com/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Orion Magazine', 'https://orionmagazine.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Emergence Magazine', 'https://emergencemagazine.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Terrain.org', 'https://www.terrain.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('High Country News', 'https://www.hcn.org/about/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Atlantic', 'https://www.theatlantic.com/contact/submissions/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Harper\'s Magazine', 'https://harpers.org/submissions/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The New Yorker', 'https://www.newyorker.com/about/contact', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('VQR', 'https://www.vqronline.org/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Missouri Review CNF', 'https://www.missourireview.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Colorado Review CNF', 'https://coloradoreview.colostate.edu/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Iowa Review CNF', 'https://iowareview.org/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Prairie Schooner CNF', 'https://prairieschooner.unl.edu/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('TriQuarterly CNF', 'https://www.triquarterly.org/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Georgia Review CNF', 'https://www.thegeorgiareview.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Cincinnati Review CNF', 'https://www.cincinnatireview.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Ecotone CNF', 'https://ecotonemagazine.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Common CNF', 'https://www.thecommononline.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Catapult CNF', 'https://catapult.co/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Electric Literature CNF', 'https://electricliterature.com/submissions/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Lit Hub CNF', 'https://lithub.com/about/submissions/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Offing CNF', 'https://theoffingmag.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Hazlitt', 'https://hazlitt.net/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Point CNF', 'https://thepointmag.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Drift CNF', 'https://www.thedriftmag.com/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Dial CNF', 'https://www.thedial.world/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Baffler', 'https://thebaffler.com/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('n+1 CNF', 'https://www.nplusonemag.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Millions', 'https://themillions.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Lapham\'s Quarterly', 'https://www.laphamsquarterly.org/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Threepenny Review CNF', 'https://www.threepennyreview.com/submissions.html', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('AGNI CNF', 'https://agnionline.bu.edu/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Ploughshares CNF', 'https://www.pshares.org/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Tin House CNF', 'https://tinhouse.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Conjunctions CNF', 'https://conjunctions.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Oxford American CNF', 'https://www.oxfordamerican.org/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Southern Review CNF', 'https://thesouthernreview.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Antioch Review CNF', 'https://antiochreview.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Hudson Review CNF', 'https://hudsonreview.com/submissions/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Yale Review CNF', 'https://yalereview.org/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('New England Review CNF', 'https://www.nereview.com/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Passages North CNF', 'https://www.passagesnorth.com/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Masters Review CNF', 'https://mastersreview.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('SmokeLong CNF', 'https://www.smokelong.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Wigleaf CNF', 'https://wigleaf.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Split Lip CNF', 'https://www.splitlipmagazine.com/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Hobart CNF', 'https://www.hobartpulp.com/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('PANK CNF', 'https://pankmagazine.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Craft Literary CNF', 'https://www.craftliterary.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Fractured Lit CNF', 'https://www.fracturedlit.com/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Grist CNF', 'https://gristjournal.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Heavy Feather CNF', 'https://heavyfeatherreview.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Joyland CNF', 'https://joylandmagazine.com/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Epiphany CNF', 'https://epiphanyzine.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Account CNF', 'https://theaccountmagazine.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Adroit Journal CNF', 'https://www.theadroitjournal.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Baltimore Review CNF', 'https://baltimorereview.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Forge CNF', 'https://forgelitmag.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Journal CNF', 'https://thejournalmag.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Literary Review CNF', 'https://www.theliteraryreview.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Los Angeles Review CNF', 'https://losangelesreview.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Massachusetts Review CNF', 'https://www.massreview.org/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Southeast Review CNF', 'https://southeastreview.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Third Coast CNF', 'https://thirdcoastmagazine.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Tupelo Quarterly CNF', 'https://www.tupeloquarterly.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('West Branch CNF', 'https://westbranch.psu.edu/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Willow Springs CNF', 'https://willowspringsmagazine.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Zone 3 CNF', 'https://zone3press.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Zyzzyva CNF', 'https://zyzzyva.org/submissions/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('A Public Space CNF', 'https://apublicspace.org/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Brick CNF', 'https://brickmag.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'], geography: ['CA'] }),
    org('Room CNF', 'https://roommagazine.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'], geography: ['CA'] }),
    org('The Fiddlehead CNF', 'https://fiddlehead.ca/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'], geography: ['CA'] }),
    org('Granta CNF', 'https://granta.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Wasafiri CNF', 'https://www.wasafiri.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'], geography: ['GB'] }),
    org('The White Review CNF', 'https://www.thewhitereview.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'], geography: ['GB'] }),
    org('Overland CNF', 'https://overland.org.au/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'], geography: ['AU'] }),
    org('Griffith Review CNF', 'https://www.griffithreview.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'], geography: ['AU'] }),
    org('Asymptote CNF', 'https://www.asymptotejournal.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Words Without Borders CNF', 'https://www.wordswithoutborders.org/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Margins CNF', 'https://aaww.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Hyphen CNF', 'https://hyphenmagazine.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Mizna CNF', 'https://mizna.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Florida Review CNF', 'https://www.floridareview.cah.ucf.edu/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Shenandoah CNF', 'https://shenandoahliterary.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Ninth Letter CNF', 'https://www.ninthletter.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Michigan Quarterly Review CNF', 'https://sites.lsa.umich.edu/mqr/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Mid-American Review CNF', 'https://www.midamericanreview.com/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('New Ohio Review CNF', 'https://www.ohio.edu/cas/nor/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Puerto del Sol CNF', 'https://www.puertodelsol.org/submit', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Quarterly West CNF', 'https://quarterlywest.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Redivider CNF', 'https://redivider.emerson.edu/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Salt Hill CNF', 'https://salthilljournal.net/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Sixth Finch CNF', 'https://sixthfinch.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Story CNF', 'https://storymagazine.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Subtropics CNF', 'https://subtropics.english.ufl.edu/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Tahoma Literary Review CNF', 'https://tahomaliteraryreview.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Timber Journal CNF', 'https://timberjournal.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Worcester Review CNF', 'https://www.theworcesterreview.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Yemassee CNF', 'https://yemassee.usc.edu/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Bat City Review CNF', 'https://www.batcityreview.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Breakwater Review CNF', 'https://breakwaterreview.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Cherry Tree CNF', 'https://www.cherrytreemag.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Cimarron Review CNF', 'https://cimarronreview.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Guesthouse CNF', 'https://guesthouselit.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Honey Literary CNF', 'https://honeyliterary.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Lantern Review CNF', 'https://lanternreview.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Porter House Review CNF', 'https://porterhousereview.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Raleigh Review CNF', 'https://raleighreview.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Solstice CNF', 'https://solsticelitmag.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Nashville Review CNF', 'https://nashvillereview.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('The Pinch CNF', 'https://pinchjournal.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Up the Staircase CNF', 'https://upthestaircase.org/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Wildness CNF', 'https://wildnesslit.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
    org('Winter Tangerine CNF', 'https://wintertangerine.com/submit/', 'creative-nonfiction', { opportunityTypes: ['magazine'] }),
  ],
  ['magazine'],
);
