import { expandMany, org } from '../helpers.js';
import type { SourceRegistryEntry } from '../types.js';

/** Tier-0 literary fiction magazines and journals with public submission pages. */
export const LITERARY_FICTION_SOURCES: SourceRegistryEntry[] = expandMany(
  [
    org('The Kenyon Review', 'https://kenyonreview.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('AGNI', 'https://agnionline.bu.edu/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Ploughshares', 'https://www.pshares.org/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Paris Review', 'https://www.theparisreview.org/submissions', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Tin House', 'https://tinhouse.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('One Story', 'https://www.one-story.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Glimmer Train', 'https://www.glimmertrain.com/submit.html', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Sun Magazine', 'https://www.thesunmagazine.org/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('American Short Fiction', 'https://americanshortfiction.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Threepenny Review', 'https://www.threepennyreview.com/submissions.html', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('ZYZZYVA', 'https://zyzzyva.org/submissions/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Southern Review', 'https://thesouthernreview.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Missouri Review', 'https://www.missourireview.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Colorado Review', 'https://coloradoreview.colostate.edu/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Iowa Review', 'https://iowareview.org/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('New England Review', 'https://www.nereview.com/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Narrative Magazine', 'https://www.narrativemagazine.com/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Conjunctions', 'https://conjunctions.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('McSweeney\'s', 'https://www.mcsweeneys.net/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Cincinnati Review', 'https://www.cincinnatireview.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Georgia Review', 'https://www.thegeorgiareview.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Antioch Review', 'https://antiochreview.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Hudson Review', 'https://hudsonreview.com/submissions/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Yale Review', 'https://yalereview.org/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Common', 'https://www.thecommononline.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('A Public Space', 'https://apublicspace.org/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Granta', 'https://granta.com/contact/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The New Yorker Fiction', 'https://www.newyorker.com/about/contact', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Electric Literature', 'https://electricliterature.com/submissions/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Lit Hub', 'https://lithub.com/about/submissions/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Rumpus', 'https://therumpus.net/submissions/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Guernica', 'https://www.guernicamag.com/submissions/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Catapult', 'https://catapult.co/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Offing', 'https://theoffingmag.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('BOMB Magazine', 'https://bombmagazine.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('NOON', 'https://www.noonannual.com/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('NOVEMBER', 'https://novembermag.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Fence', 'https://fenceportal.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('N+1', 'https://www.nplusonemag.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Believer', 'https://www.thebeliever.net/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Masters Review', 'https://mastersreview.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('SmokeLong Quarterly', 'https://www.smokelong.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Wigleaf', 'https://wigleaf.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Passages North', 'https://www.passagesnorth.com/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Prairie Schooner', 'https://prairieschooner.unl.edu/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('TriQuarterly', 'https://www.triquarterly.org/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Malahat Review', 'https://www.malahatreview.ca/submit', 'literary-fiction', { opportunityTypes: ['magazine'], geography: ['CA'] }),
    org('Grain Magazine', 'https://grainmagazine.ca/submit/', 'literary-fiction', { opportunityTypes: ['magazine'], geography: ['CA'] }),
    org('Room Magazine', 'https://roommagazine.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'], geography: ['CA'] }),
    org('The Fiddlehead', 'https://fiddlehead.ca/submit', 'literary-fiction', { opportunityTypes: ['magazine'], geography: ['CA'] }),
    org('Brick Magazine', 'https://brickmag.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'], geography: ['CA'] }),
    org('Granta Books', 'https://granta.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The White Review', 'https://www.thewhitereview.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'], geography: ['GB'] }),
    org('Wasafiri', 'https://www.wasafiri.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'], geography: ['GB'] }),
    org('Ambit Magazine', 'https://www.ambitmagazine.co.uk/submit/', 'literary-fiction', { opportunityTypes: ['magazine'], geography: ['GB'] }),
    org('The Stinging Fly', 'https://www.stingingfly.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'], geography: ['IE'] }),
    org('Banshee', 'https://bansheelit.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'], geography: ['IE'] }),
    org('The Dublin Review', 'https://thedublinreview.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'], geography: ['IE'] }),
    org('Overland', 'https://overland.org.au/submit/', 'literary-fiction', { opportunityTypes: ['magazine'], geography: ['AU'] }),
    org('Meanjin', 'https://meanjin.com.au/submit/', 'literary-fiction', { opportunityTypes: ['magazine'], geography: ['AU'] }),
    org('Griffith Review', 'https://www.griffithreview.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'], geography: ['AU'] }),
    org('Asymptote Journal', 'https://www.asymptotejournal.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'], disciplines: ['translation'] }),
    org('Words Without Borders', 'https://www.wordswithoutborders.org/submit', 'literary-fiction', { opportunityTypes: ['magazine'], disciplines: ['translation'] }),
    org('The Dial', 'https://www.thedial.world/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Drift', 'https://www.thedriftmag.com/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Point', 'https://thepointmag.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('n+1 Books', 'https://www.nplusonemag.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Epiphany', 'https://epiphanyzine.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Joyland', 'https://joylandmagazine.com/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Joyland Fiction', 'https://joylandmagazine.com/submit/fiction', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Split Lip Magazine', 'https://www.splitlipmagazine.com/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Hobart', 'https://www.hobartpulp.com/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('PANK', 'https://pankmagazine.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Brevity', 'https://brevitymag.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Craft Literary', 'https://www.craftliterary.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('CRAFT', 'https://www.craftliterary.com/submit/fiction/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Fractured Lit', 'https://www.fracturedlit.com/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Failed Haiku', 'https://failedhaiku.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Fiction Southeast', 'https://fictionsoutheast.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Fiction Writers Review', 'https://fictionwritersreview.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('F(r)iction', 'https://frictionlit.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Gigantic Sequins', 'https://giganticsequins.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Grist', 'https://gristjournal.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Heavy Feather Review', 'https://heavyfeatherreview.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Juked', 'https://juked.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Juxtaprose', 'https://juxtaprose.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Ligeia Magazine', 'https://www.ligeiamagazine.com/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Longleaf Review', 'https://www.longleafreview.com/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Maudlin House', 'https://maudlinhouse.net/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Michigan Quarterly Review', 'https://sites.lsa.umich.edu/mqr/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Mid-American Review', 'https://www.midamericanreview.com/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('New Ohio Review', 'https://www.ohio.edu/cas/nor/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('New World Writing', 'https://newworldwriting.net/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Pidgeonholes', 'https://pidgeonholes.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Pithead Chapel', 'https://pitheadchapel.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Prose Online', 'https://www.prose.online/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Puerto del Sol', 'https://www.puertodelsol.org/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Quarterly West', 'https://quarterlywest.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Redivider', 'https://redivider.emerson.edu/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Salt Hill Journal', 'https://salthilljournal.net/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Sixth Finch', 'https://sixthfinch.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Story Magazine', 'https://storymagazine.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Subtropics', 'https://subtropics.english.ufl.edu/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Sycamore Review', 'https://www.sycamorereview.com/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Tahoma Literary Review', 'https://tahomaliteraryreview.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Adroit Journal', 'https://www.theadroitjournal.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Account', 'https://theaccountmagazine.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Baltimore Review', 'https://baltimorereview.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Collagist', 'https://www.dzancbooks.org/the-collagist/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Collidescope', 'https://www.collidescope.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Forge', 'https://forgelitmag.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Journal', 'https://thejournalmag.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Literary Review', 'https://www.theliteraryreview.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Los Angeles Review', 'https://losangelesreview.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Massachusetts Review', 'https://www.massreview.org/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Normal School', 'https://thenormalschool.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Southeast Review', 'https://southeastreview.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Southampton Review', 'https://www.thesouthamptonreview.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Stockholm Review', 'https://thestockholmreview.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Tusculum Review', 'https://www.tusculumreview.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('The Wrong Quarterly', 'https://wrongquarterly.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Third Coast', 'https://thirdcoastmagazine.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Timber Journal', 'https://timberjournal.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Tupelo Quarterly', 'https://www.tupeloquarterly.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('West Branch', 'https://westbranch.psu.edu/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('West Trade Review', 'https://westtradereview.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Willow Springs', 'https://willowspringsmagazine.org/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Worcester Review', 'https://www.theworcesterreview.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Zone 3', 'https://zone3press.com/submit/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('Zoetrope All-Story', 'https://www.all-story.com/submit', 'literary-fiction', { opportunityTypes: ['magazine'] }),
    org('ZYZZYVA', 'https://zyzzyva.org/submissions/', 'literary-fiction', { opportunityTypes: ['magazine'] }),
  ],
  ['magazine'],
);
