import { expandMany, org } from '../helpers.js';
import type { SourceRegistryEntry } from '../types.js';

export const POETRY_SOURCES: SourceRegistryEntry[] = expandMany(
  [
    org('Poetry Magazine', 'https://www.poetryfoundation.org/poetrymagazine/submit', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Poetry Northwest', 'https://www.poetrynw.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('American Poetry Review', 'https://aprweb.org/submit', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The American Journal of Poetry', 'https://theamericanjournalofpoetry.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Rattle', 'https://www.rattle.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Copper Nickel', 'https://copper-nickel.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Pleiades', 'https://www.pleiadesmag.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Beloit Poetry Journal', 'https://www.bpj.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Bennington Review', 'https://benningtonreview.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Black Warrior Review', 'https://blackwarriorreview.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('BOAAT Press', 'https://boaatpress.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Bone Bouquet', 'https://bonebouquet.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Cider Press Review', 'https://ciderpressreview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Cincinnati Review Poetry', 'https://www.cincinnatireview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Colorado Review Poetry', 'https://coloradoreview.colostate.edu/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Columbia Poetry Review', 'https://columbiapoetryreview.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Conduit', 'https://www.conduit.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Cortland Review', 'https://www.cortlandreview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Diode Poetry Journal', 'https://diodepoetry.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Fairy Tale Review', 'https://www.fairytalereview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Four Way Review', 'https://fourwayreview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Frontier Poetry', 'https://www.frontierpoetry.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Gulf Coast', 'https://gulfcoastmag.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Hayden\'s Ferry Review', 'https://haydensferryreview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Indiana Review', 'https://indianareview.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Iron Horse Literary Review', 'https://ironhorsereview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Kenyon Review Poetry', 'https://kenyonreview.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Lana Turner', 'https://www.lanaturnerjournal.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Los Angeles Review of Books Poetry', 'https://lareviewofbooks.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Magma Poetry', 'https://magmapoetry.com/submit/', 'poetry', { opportunityTypes: ['magazine'], geography: ['GB'] }),
    org('Mizna', 'https://mizna.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('New Ohio Review Poetry', 'https://www.ohio.edu/cas/nor/submit', 'poetry', { opportunityTypes: ['magazine'] }),
    org('New York Quarterly', 'https://nyq.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('North American Review', 'https://northamericanreview.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Oxford American', 'https://www.oxfordamerican.org/submit', 'poetry', { opportunityTypes: ['magazine'] }),
    org('PANK Poetry', 'https://pankmagazine.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Parnassus', 'https://www.parnassuspoetry.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Poet Lore', 'https://www.poetlore.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Poetry Daily', 'https://poems.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Poetry International', 'https://www.poetryinternationalweb.net/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Poetry London', 'https://poetrylondon.co.uk/submit/', 'poetry', { opportunityTypes: ['magazine'], geography: ['GB'] }),
    org('Poetry Wales', 'https://www.poetrywales.co.uk/submit/', 'poetry', { opportunityTypes: ['magazine'], geography: ['GB'] }),
    org('Poetry Ireland Review', 'https://www.poetryireland.ie/submit/', 'poetry', { opportunityTypes: ['magazine'], geography: ['IE'] }),
    org('Poetry Is Currency', 'https://poetryiscurrency.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Poetry Society of America', 'https://poetrysociety.org/awards', 'poetry', { opportunityTypes: ['award', 'contest'] }),
    org('Poets Reading the News', 'https://www.poetsreadingthenews.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('RHINO Poetry', 'https://rhinopoetry.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Rusted Radishes', 'https://rustedradishes.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Salt Hill Poetry', 'https://salthilljournal.net/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Slice Magazine', 'https://www.slicemagazine.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Southampton Review Poetry', 'https://www.thesouthamptonreview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Southern Humanities Review', 'https://www.auburn.edu/academic/liberal_arts/shr/submit.html', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Spillway', 'https://spillway.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Sugar House Review', 'https://sugarhousereview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Swamp Pink', 'https://swamppink.submittable.com/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Account Poetry', 'https://theaccountmagazine.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Adroit Journal Poetry', 'https://www.theadroitjournal.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Cincinnati Review Poetry', 'https://www.cincinnatireview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Cortland Poetry Review', 'https://www.cortlandreview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Iowa Review Poetry', 'https://iowareview.org/submit', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Missouri Review Poetry', 'https://www.missourireview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Offing Poetry', 'https://theoffingmag.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Paris Review Poetry', 'https://www.theparisreview.org/submissions', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Shore Poetry', 'https://theshorepoetry.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Southeast Review Poetry', 'https://southeastreview.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Threepenny Review Poetry', 'https://www.threepennyreview.com/submissions.html', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Westchester Review', 'https://thewestchesterreview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Third Wednesday', 'https://thirdwednesdaymagazine.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Thrush Poetry Journal', 'https://www.thrushpoetryjournal.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Tupelo Press', 'https://www.tupelopress.org/submit/', 'poetry', { opportunityTypes: ['contest', 'magazine'] }),
    org('Under a Warm Green Linden', 'https://warmgreenlinden.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Verse Daily', 'https://www.versedaily.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Volt', 'https://volt.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Washington Square Review', 'https://www.washingtonsquarereview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('West Branch Poetry', 'https://westbranch.psu.edu/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Willow Springs Poetry', 'https://willowspringsmagazine.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Worcester Review Poetry', 'https://www.theworcesterreview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Yemassee', 'https://yemassee.usc.edu/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Zone 3 Poetry', 'https://zone3press.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Bat City Review', 'https://www.batcityreview.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Bear Review', 'https://bearreview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Bodega Magazine', 'https://bodegamagazine.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Breakwater Review', 'https://breakwaterreview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Broad River Review', 'https://broadriverreview.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Canary', 'https://canarylitmag.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Cherry Tree', 'https://www.cherrytreemag.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Cimarron Review', 'https://cimarronreview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Cotton Xenomorph', 'https://cottonxenomorph.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Dreginald', 'https://dreginald.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Ecotone', 'https://ecotonemagazine.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Empty Mirror', 'https://www.emptymirrorbooks.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Foglifter', 'https://foglifterjournal.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Guesthouse', 'https://guesthouselit.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Haven Spec', 'https://havenspec.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Honey Literary', 'https://honeyliterary.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Hyphen Magazine', 'https://hyphenmagazine.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Jubilat', 'https://jubilat.net/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Kenyon Review Young Writers', 'https://kenyonreview.org/young-writers/', 'poetry', { opportunityTypes: ['contest'] }),
    org('Lantern Review', 'https://lanternreview.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Muzzle Magazine', 'https://muzzlemagazine.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Ninth Letter', 'https://www.ninthletter.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Porter House Review', 'https://porterhousereview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Raleigh Review', 'https://raleighreview.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Red Wheelbarrow', 'https://redwheelbarrow.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Rising Phoenix Review', 'https://risingphoenixreview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Rust + Moth', 'https://rustandmoth.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Shenandoah', 'https://shenandoahliterary.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Solstice', 'https://solsticelitmag.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('South Florida Poetry Journal', 'https://www.southfloridapoetryjournal.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Spillway Poetry', 'https://spillway.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Tar River Poetry', 'https://tarriverpoetry.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Cincinnati Review MiCRo', 'https://www.cincinnatireview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Common Poetry', 'https://www.thecommononline.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Florida Review', 'https://www.floridareview.cah.ucf.edu/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Hopkins Review', 'https://hopkinsreview.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Margins', 'https://aaww.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Nashville Review', 'https://nashvillereview.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Pinch', 'https://pinchjournal.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Rumpus Poetry', 'https://therumpus.net/submissions/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Shore', 'https://theshorepoetry.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Spectacle', 'https://thespectacle.clmp.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('The Yale Review Poetry', 'https://yalereview.org/submit', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Tinderbox Poetry Journal', 'https://tinderboxpoetry.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Up the Staircase Quarterly', 'https://upthestaircase.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Voicemail Poems', 'https://voicemailpoems.org/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Wildness', 'https://wildnesslit.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Winter Tangerine', 'https://wintertangerine.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
    org('Wusgood Magazine', 'https://wusgoodmag.com/submit/', 'poetry', { opportunityTypes: ['magazine'] }),
  ],
  ['magazine'],
);
