import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getProfileRepository } from '@/lib/profileRepository';

export const dynamic = 'force-dynamic';

export default async function JournalDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const repository = getProfileRepository();
  if (!repository) notFound();
  const { id } = await params;
  const profile = await repository.getById(id);
  if (!profile) notFound();
  return <main className="mx-auto min-h-screen max-w-5xl px-6 py-16"><Link href="/journals" className="text-sm text-purple-800">← Journals & small presses</Link><header className="mt-8 flex flex-wrap items-start gap-6">{profile.mediaUrl ? <img src={profile.mediaUrl} alt="" className="h-28 w-28 rounded-xl object-cover" /> : null}<div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-purple-700">{profile.kind === 'small_press' ? 'Small press' : 'Literary journal'}</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">{profile.name}</h1>{profile.websiteUrl ? <a className="mt-3 inline-block text-purple-800 underline" href={profile.websiteUrl} target="_blank" rel="noreferrer">Official website ↗</a> : null}</div></header><div className="mt-10 grid gap-10 lg:grid-cols-[1fr_320px]"><section><h2 className="text-2xl font-semibold">About</h2><p className="mt-3 whitespace-pre-line text-slate-700">{profile.editorialFocus || profile.summary || 'No editorial focus has been published yet.'}</p>{profile.editorialTips ? <><h2 className="mt-8 text-2xl font-semibold">Editorial tips</h2><p className="mt-3 whitespace-pre-line text-slate-700">{profile.editorialTips}</p></> : null}<h2 className="mt-10 text-2xl font-semibold">Open calls and related opportunities</h2>{profile.opportunities.length ? <div className="mt-4 space-y-3">{profile.opportunities.map((opportunity) => <article key={opportunity.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold">{opportunity.title}</h3><p className="text-sm text-slate-500">{opportunity.deadline ? `Deadline ${opportunity.deadline}` : 'Deadline not listed'}</p></div><span className="text-sm capitalize text-slate-500">{opportunity.status}</span></div><Link href={`/opportunities/${encodeURIComponent(opportunity.id)}`} className="mt-3 inline-block text-sm font-medium text-purple-800">Open opportunity →</Link></article>)}</div> : <p className="mt-3 text-slate-600">No linked calls have been published yet.</p>}</section><aside className="h-fit rounded-xl border p-5"><h2 className="font-semibold">Submission facts</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-slate-500">Genres</dt><dd>{profile.genres.join(', ') || 'Not listed'}</dd></div><div><dt className="text-slate-500">Formats</dt><dd>{profile.formats.join(', ') || 'Not listed'}</dd></div><div><dt className="text-slate-500">Reading period</dt><dd>{profile.readingPeriod || 'Not listed'}</dd></div><div><dt className="text-slate-500">Reading fee</dt><dd>{profile.readingFee || 'Not listed'}</dd></div><div><dt className="text-slate-500">Unsolicited submissions</dt><dd>{profile.unsolicitedSubmissions || 'Not listed'}</dd></div><div><dt className="text-slate-500">Payment</dt><dd>{profile.payment || 'Not listed'}</dd></div></dl></aside></div></main>;
}
