import Link from 'next/link';
import { cookies } from 'next/headers';
import { notFound, redirect } from 'next/navigation';
import { getSessionAccountFromToken, SESSION_COOKIE } from '@/lib/auth';
import { getEngine } from '@/lib/engine';
import { getRelationalWorkspace, getWorkspaceEngine, workspaceRelationalAuthorityEnabled } from '@/lib/workspaceEngine';
import { decisionSummary, paymentLane, receiptLane, reviewLane, submissionNextAction } from '@/lib/organizationWorkflow';
import { AssignReviewerDialog, DeliveryTaskActions, RecordDecisionDialog } from '@/components/organization-submission-actions';
import { ORGANIZATION_ROLE_LABELS } from '@/lib/organizationPeople';
import styles from './dossier.module.css';
import { submissionHistory } from '@/lib/submissionHistory';
import { organizationIntakeFlags } from '@/lib/intakeData';

type Section = 'overview' | 'works' | 'answers' | 'reviews' | 'decisions' | 'delivery' | 'history';
const sections: Array<{ id: Section; label: string }> = [{ id: 'overview', label: 'Overview' }, { id: 'works', label: 'Works' }, { id: 'answers', label: 'Answers' }, { id: 'reviews', label: 'Reviews' }, { id: 'decisions', label: 'Decisions' }, { id: 'delivery', label: 'Delivery' }, { id: 'history', label: 'History' }];

export default async function OrganizationSubmissionDossierPage({ params, searchParams }: { params: Promise<{ organizationId: string; submissionId: string }>; searchParams: Promise<{ section?: string }> }) {
  const { organizationId, submissionId } = await params;
  const query = await searchParams;
  const session = await getSessionAccountFromToken((await cookies()).get(SESSION_COOKIE)?.value);
  if (!session) redirect(`/login?next=${encodeURIComponent(`/organization/${organizationId}/submissions/${submissionId}`)}`);
  const membership = session.memberships.find((item) => item.organizationId === organizationId);
  if (!membership || (membership.role !== 'owner' && membership.role !== 'admin')) notFound();
  const relationalWorkspace = workspaceRelationalAuthorityEnabled() ? await getRelationalWorkspace() : undefined;
  const workspace = relationalWorkspace ? undefined : await getWorkspaceEngine();
  const submission = relationalWorkspace
    ? (await relationalWorkspace.submissionsForOrganization(organizationId)).find((item) => item.id === submissionId)
    : workspace!.submissionsForOrganization(organizationId).find((item) => item.id === submissionId);
  if (!submission) notFound();
  const radar = await getEngine();
  const submitter = radar.store.accounts.get(submission.submitterAccountId);
  const submitterProfile = submitter?.userId ? radar.store.users.get(submitter.userId) : undefined;
  const path = relationalWorkspace ? await relationalWorkspace.publicSubmissionPath(submission.submissionPathId) : workspace!.store.submissionPaths.get(submission.submissionPathId);
  const works = 'works' in submission ? submission.works : workspace!.worksForSubmission(submissionId);
  const assignments = relationalWorkspace ? await relationalWorkspace.reviewAssignmentsForSubmission(organizationId, submissionId) : workspace!.reviewAssignmentsForSubmission(submissionId);
  const decisions = 'decisions' in submission ? submission.decisions : workspace!.decisionsForSubmission(organizationId, submissionId);
  const delivery = relationalWorkspace ? [] : workspace!.deliveryTasksForOrganization(organizationId).filter((task) => works.some((work) => work.id === task.workId));
  const receipt = receiptLane(submission.status, submission.paymentStatus);
  const review = reviewLane(assignments);
  const decision = decisionSummary(works, decisions);
  const payment = paymentLane(submission.paymentStatus);
  const next = submissionNextAction({ receipt, review, decision });
  const active = sections.some((item) => item.id === query.section) ? query.section as Section : 'overview';
  const base = `/organization/${encodeURIComponent(organizationId)}/submissions/${encodeURIComponent(submissionId)}`;
  const outcomeByWork = new Map(decisions.map((item) => [item.workId, item.outcome]));
  const taskByWork = new Map(delivery.map((item) => [item.workId, item]));
  const fieldById = new Map(path?.fields.map((field) => [field.id, field]) ?? []);
  const rounds = (relationalWorkspace ? await relationalWorkspace.reviewRoundsForOpenCall(organizationId, submission.openCallId) : workspace!.reviewRoundsForOpenCall(submission.openCallId)).map((round) => ({ id: round.id, name: round.name }));
  const reviewers = radar.store.memberships.filter((item) => item.organizationId === organizationId && item.accountId !== submission.submitterAccountId).flatMap((item) => { const account = radar.store.accounts.get(item.accountId); if (!account) return []; const profile = account.userId ? radar.store.users.get(account.userId) : undefined; return [{ accountId: item.accountId, label: `${profile?.displayName || account.displayName || account.email} · ${ORGANIZATION_ROLE_LABELS[item.role]}` }]; }).sort((a, b) => a.label.localeCompare(b.label));
  const assignmentFacts = assignments.map((assignment) => ({ ...(typeof assignment.reviewRoundId === 'string' ? { reviewRoundId: assignment.reviewRoundId } : {}), ...(typeof assignment.reviewerAccountId === 'string' ? { reviewerAccountId: assignment.reviewerAccountId } : {}), ...('recusedAt' in assignment && typeof assignment.recusedAt === 'string' ? { recusedAt: assignment.recusedAt } : {}) }));
  const history = workspace ? submissionHistory({ radar, workspace, organizationId, submissionId }) : undefined;
  const flags = workspace ? organizationIntakeFlags({ radar, workspace, organizationId }).get(submissionId) ?? [] : [];

  return <main id="organization-main" className={styles.main}><Link className={styles.back} href={`/organization/${encodeURIComponent(organizationId)}/submissions`}>← Submissions</Link><header className={styles.header}><div><p className={styles.eyebrow}>{submission.openCallTitle}</p><h1>{submitterProfile?.displayName || submitter?.displayName || submitter?.email || 'Submission dossier'}</h1><p>{submission.category || 'No category supplied'} · Received {new Intl.DateTimeFormat('en', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(submission.submittedAt))}</p></div><aside className={styles.nextAction}><span>Next safe action</span><strong>{next}</strong></aside></header><nav className={styles.tabs} aria-label="Submission dossier sections">{sections.map((item) => <Link key={item.id} href={`${base}?section=${item.id}`} aria-current={active === item.id ? 'page' : undefined}>{item.label}</Link>)}</nav>
    <section className={styles.content} aria-labelledby={`dossier-${active}`}>
      {active === 'overview' ? <><header><h2 id="dossier-overview">Overview</h2><p>Receipt, review, decision, and payment are independent states for this submitted packet.</p></header><dl className={styles.facts}><div><dt>Receipt</dt><dd>{receipt}</dd></div><div><dt>Review</dt><dd>{review}</dd></div><div><dt>Decision summary</dt><dd>{decision}</dd></div><div><dt>Payment</dt><dd>{payment}</dd></div></dl>{flags.length ? <section aria-labelledby="dossier-flags" className={styles.boundary}><h3 id="dossier-flags">Worth a look</h3><ul>{flags.map((flag) => <li key={`${flag.code}-${(flag.relatedSubmissionIds ?? []).join('-')}`}>{flag.message}{flag.relatedSubmissionIds?.length ? <> See {flag.relatedSubmissionIds.map((relatedId, index) => <span key={relatedId}>{index ? ', ' : ''}<Link href={`/organization/${encodeURIComponent(organizationId)}/submissions/${encodeURIComponent(relatedId)}`}>the other submission</Link></span>)}.</> : null}</li>)}</ul></section> : null}<div className={styles.boundary}>No eligibility conclusion is inferred here. Flags are prompts for a person; category, payment and review progress do not decide the creative outcome.</div></> : null}
      {active === 'works' ? <><header><h2 id="dossier-works">Works</h2><p>Each Work keeps its own material, review evidence, decision, and accepted-Work delivery state.</p></header><div className={styles.list}>{works.map((work) => { const files = work.fileUrls ?? (work.fileUrl ? [work.fileUrl] : []); return <article className={styles.item} key={work.id}><div><h3>{work.title}</h3><p>{files.length ? `${files.length} ${files.length === 1 ? 'file' : 'files'} available` : 'No file attached'}</p>{files.length ? <div className={styles.files}>{files.map((_, index) => <a key={index} href={`/api/orgs/${encodeURIComponent(organizationId)}/works/${encodeURIComponent(work.id)}/file?index=${index}`} target="_blank" rel="noreferrer">Open file {index + 1}</a>)}</div> : null}</div><span>{outcomeByWork.get(work.id) ?? 'No decision'}</span></article>; })}</div></> : null}
      {active === 'answers' ? <><header><h2 id="dossier-answers">Answers</h2><p>Original applicant answers are shown against the saved form field labels.</p></header>{Object.keys(submission.answers ?? {}).length ? <dl>{Object.entries(submission.answers ?? {}).map(([fieldId, value]) => <div className={styles.answer} key={fieldId}><dt>{fieldById.get(fieldId)?.label ?? 'Answer'}</dt><dd>{fieldById.get(fieldId)?.type === 'file-upload' ? 'File attached' : Array.isArray(value) ? value.join('\n') : value}</dd></div>)}</dl> : <div className={styles.boundary}>No saved answers are available for this submission.</div>}</> : null}
      {active === 'reviews' ? <><header><h2 id="dossier-reviews">Reviews</h2><p>Assignments and completed recommendations remain separate from decisions.</p></header><div className={styles.sectionActions}><AssignReviewerDialog organizationId={organizationId} submissionId={submission.id} openCallId={submission.openCallId} reviewers={reviewers} rounds={rounds} assignments={assignmentFacts} /></div><div className={styles.list}>{assignments.map((assignment) => { const reviewerId = typeof assignment.reviewerAccountId === 'string' ? assignment.reviewerAccountId : undefined; const reviewer = reviewerId ? radar.store.accounts.get(reviewerId) : undefined; const assignmentId = assignment.id as string; const recommendation = 'recommendation' in assignment && assignment.recommendation && typeof assignment.recommendation === 'object' ? assignment.recommendation as { score?: number } : workspace ? workspace.recommendationForAssignment(assignmentId) : undefined; return <article className={styles.item} key={assignmentId}><div><h3>{reviewer?.displayName || reviewer?.email || 'Reviewer'}</h3><p>{recommendation ? `Recommendation recorded${recommendation.score === undefined ? '' : ` · Score ${recommendation.score}`}` : 'Recommendation not submitted'}</p></div><span>{assignment.completedAt ? 'Complete' : 'In progress'}</span></article>; })}{assignments.length ? null : <div className={styles.boundary}>No review assignments are recorded for this submission.</div>}</div></> : null}
      {active === 'decisions' ? <><header><h2 id="dossier-decisions">Decisions</h2><p>Outcomes remain attached to individual Works. The packet summary is derived.</p></header><div className={styles.list}>{works.map((work) => <article className={styles.item} key={work.id}><div><h3>{work.title}</h3><p>{outcomeByWork.has(work.id) ? 'Work outcome recorded' : 'No Work decision recorded'}</p></div><div className={styles.itemActions}><span>{outcomeByWork.get(work.id) ?? 'No decision'}</span><RecordDecisionDialog organizationId={organizationId} work={{ id: work.id, title: work.title }} current={outcomeByWork.get(work.id)} reviewSummary={review} /></div></article>)}</div></> : null}
      {active === 'delivery' ? <><header><h2 id="dossier-delivery">Delivery</h2><p>Delivery begins only for accepted Work and remains separate from the decision itself.</p></header><div className={styles.list}>{works.filter((work) => outcomeByWork.get(work.id) === 'accepted').map((work) => { const task = taskByWork.get(work.id); return <article className={styles.item} key={work.id}><div><h3>{work.title}</h3><p>{task?.dueDate ? `Due ${new Intl.DateTimeFormat('en', { dateStyle: 'medium', timeZone: 'UTC' }).format(new Date(`${task.dueDate}T00:00:00Z`))}` : 'No delivery due date stored'}</p></div><div className={styles.itemActions}><span>{task?.status ?? 'Not started'}</span><DeliveryTaskActions organizationId={organizationId} work={{ id: work.id, title: work.title }} task={task ? { id: task.id, status: task.status } : undefined} /></div></article>; })}{works.some((work) => outcomeByWork.get(work.id) === 'accepted') ? null : <div className={styles.boundary}>No accepted Work requires delivery.</div>}</div></> : null}
      {active === 'history' ? <><header><h2 id="dossier-history">History</h2><p>What happened to this submission, newest first, from recorded reviews, decisions, letters and delivery.</p></header>{history ? <ol className={styles.list}>{history.map((event, index) => <li className={styles.item} key={`${event.at}-${index}`}><div><h3>{event.title}</h3>{event.detail ? <p>{event.detail}</p> : null}</div><span><time dateTime={event.at}>{new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(event.at))}</time></span></li>)}</ol> : <div className={styles.boundary}>The relational projection does not expose a readable event history for this submission yet.</div>}</> : null}
    </section>
  </main>;
}
